antioch-0.0.7: Antioch::CEAEvaluator< CoeffType > Class Template Reference
Antioch::CEAEvaluator< CoeffType > Class Template Reference
#include <cea_evaluator.h>
Public Member Functions
CEAEvaluator (const CEAThermoMixture< CoeffType > &cea_mixture)
~CEAEvaluator ()
const CEAThermoMixture
< CoeffType > & cea_mixture () const
template<typename StateType >
StateType cp (const TempCache< StateType > &cache, unsigned int species) const
We currently need different specializations for scalar vs vector inputs here.
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
StateType >::type cp (const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename StateType >
cv (const TempCache< StateType > &cache, unsigned int species) const ANTIOCH_AUTOFUNC(StateType
this cp (cache, species)-this-> chem_mixture().R(species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, StateType >::typecv(const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename StateType >
h (const TempCache< StateType > &cache, unsigned int species) const ANTIOCH_AUTOFUNC(StateType
this chem_mixture ().R(species)*cache.T *this-> h_over_RT(cache, species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, void >::typeh(const TempCache< StateType > &cache, VectorStateType &h) const
template<typename StateType >
StateType h_RT_minus_s_R (const TempCache< StateType > &cache, unsigned int species) const
We currently need different specializations for scalar vs vector inputs here.
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
void >::type h_RT_minus_s_R (const TempCache< StateType > &cache, VectorStateType &h_RT_minus_s_R) const
template<typename StateType >
StateType dh_RT_minus_s_R_dT (const TempCache< StateType > &cache, unsigned int species) const
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
void >::type dh_RT_minus_s_R_dT (const TempCache< StateType > &cache, VectorStateType &h_RT_minus_s_R) const
template<typename StateType >
StateType cp_over_R (const TempCache< StateType > &cache, unsigned int species) const
template<typename StateType >
StateType h_over_RT (const TempCache< StateType > &cache, unsigned int species) const
template<typename StateType >
StateType s_over_R (const TempCache< StateType > &cache, unsigned int species) const
Protected Member Functions
unsigned int n_species () const
Convenience function.
const ChemicalMixture
< CoeffType > & chem_mixture () const
Convenience function.
Protected Attributes
const CEAThermoMixture
< CoeffType > & _cea_mixture
Private Member Functions
CEAEvaluator ()
Default constructor.
Detailed Description
template<typename CoeffType = double>
class Antioch::CEAEvaluator< CoeffType >
Definition at line 43 of file cea_evaluator.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::CEAEvaluator< CoeffType >::CEAEvaluator (const CEAThermoMixture< CoeffType > & cea_mixture)
Definition at line 140 of file cea_evaluator.h.
     : _cea_mixture(cea_mixture)
   {
     return;
   }
template<typename CoeffType > Antioch::CEAEvaluator< CoeffType >::~CEAEvaluator ()
Definition at line 147 of file cea_evaluator.h.
   {
     return;
   }
template<typename CoeffType = double> Antioch::CEAEvaluator< CoeffType >::CEAEvaluator () private
Default constructor.
Private to force to user to supply a CEAThermoMixture object.
Member Function Documentation
template<typename CoeffType > const CEAThermoMixture< CoeffType > & Antioch::CEAEvaluator< CoeffType >::cea_mixture () const inline
Definition at line 155 of file cea_evaluator.h.
   {
     return _cea_mixture;
   }
template<typename CoeffType = double> this Antioch::CEAEvaluator< CoeffType >::chem_mixture () -> h_over_RT(cache, species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, void >::typeh(const TempCache< StateType > &cache, VectorStateType &h) const
template<typename CoeffType > const ChemicalMixture< CoeffType > & Antioch::CEAEvaluator< CoeffType >::chem_mixture () const inline protected
Convenience function.
Definition at line 169 of file cea_evaluator.h.
   {
     return _cea_mixture.chemical_mixture();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::CEAEvaluator< CoeffType >::cp (const TempCache< StateType > & cache, unsigned int species) const inline
We currently need different specializations for scalar vs vector inputs here.
Definition at line 178 of file cea_evaluator.h.
References Antioch::constant_clone(), Antioch::if_else(), and Antioch::TempCache< StateType >::T.
Referenced by test_cp().
   {
     typedef typename Antioch::value_type<StateType>::type ScalarType;
     // T < 200.1 ? cp_at_200p1 : R * cp_over_R
     return
       Antioch::if_else
         (cache.T < ScalarType(200.1),
          Antioch::constant_clone
            (cache.T,_cea_mixture.cp_at_200p1(species)),
          StateType
            (this->chem_mixture().R(species) *
             this->cp_over_R(cache, species)));
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > enable_if_c< has_size< VectorStateType >::value, StateType >::type Antioch::CEAEvaluator< CoeffType >::cp (const TempCache< StateType > & cache, const VectorStateType & mass_fractions) const inline
Definition at line 198 of file cea_evaluator.h.
References antioch_assert_equal_to, antioch_assert_greater, and cp().
   {
     antioch_assert_equal_to( mass_fractions.size(), this->n_species() );
     antioch_assert_greater( mass_fractions.size(), 0 );
     StateType cp = mass_fractions[0]*this->cp(cache,0);
     for( unsigned int s = 1; s < this->n_species(); s++ )
       {
         cp += mass_fractions[s]*this->cp(cache,s);
       }
     return cp;
   }
template<typename CoeffType = double> this Antioch::CEAEvaluator< CoeffType >::cp (cache , species) -> chem_mixture().R(species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, StateType >::typecv(const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename CoeffType > template<typename StateType > StateType Antioch::CEAEvaluator< CoeffType >::cp_over_R (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 238 of file cea_evaluator.h.
References antioch_assert_less, Antioch::if_else(), Antioch::max(), Antioch::min(), Antioch::TempCache< StateType >::T, Antioch::TempCache< StateType >::T2, Antioch::TempCache< StateType >::T3, Antioch::TempCache< StateType >::T4, and Antioch::zero_clone().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _cea_mixture.curve_fit(species).interval(cache.T),
     //                      _cea_mixture.curve_fit(species).n_intervals() );
     typedef typename
       Antioch::rebind<StateType, unsigned int>::type UIntType;
     const UIntType interval = this->_cea_mixture.curve_fit(species).interval(cache.T);
     const unsigned int begin_interval = Antioch::min(interval);
     const unsigned int end_interval = Antioch::max(interval)+1;
     // FIXME - this needs expression templates to be faster...
     StateType returnval = Antioch::zero_clone(cache.T);
     for (unsigned int i=begin_interval; i != end_interval; ++i)
       {
         const CoeffType * const a =
           this->_cea_mixture.curve_fit(species).coefficients(i);
         returnval = Antioch::if_else
           (interval == i,
            StateType(a[0]/cache.T2 + a[1]/cache.T + a[2] + a[3]*cache.T +
                      a[4]*cache.T2 + a[5]*cache.T3 + a[6]*cache.T4),
            returnval);
       }
     return returnval;
   }
template<typename CoeffType = double> template<typename StateType > enable_if_c< has_size< VectorStateType >::value, StateType >::type Antioch::CEAEvaluator< CoeffType >::cv (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 434 of file cea_evaluator.h.
References cp().
     {
       return this->cp(cache,mass_fractions) - this->chem_mixture().R(mass_fractions);
     }
template<typename CoeffType > template<typename StateType > StateType Antioch::CEAEvaluator< CoeffType >::dh_RT_minus_s_R_dT (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 372 of file cea_evaluator.h.
References antioch_assert_less, Antioch::if_else(), Antioch::TempCache< StateType >::lnT, Antioch::max(), Antioch::min(), Antioch::TempCache< StateType >::T, Antioch::TempCache< StateType >::T2, Antioch::TempCache< StateType >::T3, and Antioch::zero_clone().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _cea_mixture.curve_fit(species).interval(cache.T),
     //                      _cea_mixture.curve_fit(species).n_intervals() );
     typedef typename
       Antioch::rebind<StateType, unsigned int>::type UIntType;
     const UIntType interval = this->_cea_mixture.curve_fit(species).interval(cache.T);
     const unsigned int begin_interval = Antioch::min(interval);
     const unsigned int end_interval = Antioch::max(interval)+1;
     // FIXME - this needs expression templates to be faster...
     StateType returnval = Antioch::zero_clone(cache.T);
     /* h/RT = -a[0]/T2    + a[1]*lnT/T + a[2]     + a[3]*T/2. + a[4]*T2/3. + a[5]*T3/4. + a[6]*T4/5. + a[8]/T,
        s/R  = -a[0]/T2/2. - a[1]/T     + a[2]*lnT + a[3]*T    + a[4]*T2/2. + a[5]*T3/3. + a[6]*T4/4. + a[9]   */
     for (unsigned int i=begin_interval; i != end_interval; ++i)
       {
         const CoeffType * const a =
           this->_cea_mixture.curve_fit(species).coefficients(i);
         returnval = Antioch::if_else
           (interval == i,
            StateType(a[0]/cache.T3 - a[8]/cache.T2 -
                      a[1]*cache.lnT/cache.T2 - a[2]/cache.T -
                      a[3]/2.  - a[4]*cache.T/3. - a[5]*cache.T2/4. -
                      a[6]*cache.T3/5.),
            returnval);
       }
     return returnval;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > enable_if_c< has_size< VectorStateType >::value, void >::type Antioch::CEAEvaluator< CoeffType >::dh_RT_minus_s_R_dT (const TempCache< StateType > & cache, VectorStateType & h_RT_minus_s_R) const inline
Definition at line 414 of file cea_evaluator.h.
References antioch_assert_equal_to.
   {
     antioch_assert_equal_to( dh_RT_minus_s_R_dT.size(), this->n_species() );
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         dh_RT_minus_s_R_dT[s] = this->dh_RT_minus_s_R_dT(cache,s);
       }
     return;
   }
template<typename CoeffType = double> template<typename StateType > enable_if_c< has_size< VectorStateType >::value, void >::type Antioch::CEAEvaluator< CoeffType >::h (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 221 of file cea_evaluator.h.
References antioch_assert_equal_to, and Antioch::TempCache< StateType >::T.
Referenced by test_h().
   {
     antioch_assert_equal_to( h.size(), this->n_species() );
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         h[s] = this->chem_mixture().R(s)*cache.T*this->h_over_RT(cache,s);
       }
     return;
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::CEAEvaluator< CoeffType >::h_over_RT (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 273 of file cea_evaluator.h.
References antioch_assert_less, Antioch::TempCache< StateType >::lnT, Antioch::TempCache< StateType >::T, Antioch::TempCache< StateType >::T2, Antioch::TempCache< StateType >::T3, and Antioch::TempCache< StateType >::T4.
   {
     antioch_assert_less( species, this->n_species() );
     antioch_assert_less( _cea_mixture.curve_fit(species).interval(cache.T),
                          _cea_mixture.curve_fit(species).n_intervals() );
     const unsigned int interval = this->_cea_mixture.curve_fit(species).interval(cache.T);
     const CoeffType *a = this->_cea_mixture.curve_fit(species).coefficients(interval);
     /* h/RT = -a0*T^-2   + a1*T^-1*lnT + a2     + a3*T/2 + a4*T^2/3 + a5*T^3/4 + a6*T^4/5 + a8/T */
     return -a[0]/cache.T2 + a[1]*cache.lnT/cache.T + a[2] + a[3]*cache.T/2.0 + a[4]*cache.T2/3.0 + a[5]*cache.T3/4.0 + a[6]*cache.T4/5.0 + a[8]/cache.T;
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::CEAEvaluator< CoeffType >::h_RT_minus_s_R (const TempCache< StateType > & cache, unsigned int species) const inline
We currently need different specializations for scalar vs vector inputs here.
Definition at line 310 of file cea_evaluator.h.
References antioch_assert_less, Antioch::if_else(), Antioch::TempCache< StateType >::lnT, Antioch::max(), Antioch::min(), Antioch::TempCache< StateType >::T, Antioch::TempCache< StateType >::T2, Antioch::TempCache< StateType >::T3, Antioch::TempCache< StateType >::T4, and Antioch::zero_clone().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _cea_mixture.curve_fit(species).interval(cache.T),
     //                      _cea_mixture.curve_fit(species).n_intervals() );
     typedef typename
       Antioch::rebind<StateType, unsigned int>::type UIntType;
     const UIntType interval = this->_cea_mixture.curve_fit(species).interval(cache.T);
     const unsigned int begin_interval = Antioch::min(interval);
     const unsigned int end_interval = Antioch::max(interval)+1;
     // FIXME - this needs expression templates to be faster...
     StateType returnval = Antioch::zero_clone(cache.T);
     /* h/RT = -a[0]/T2    + a[1]*lnT/T + a[2]     + a[3]*T/2. + a[4]*T2/3. + a[5]*T3/4. + a[6]*T4/5. + a[8]/T,
        s/R  = -a[0]/T2/2. - a[1]/T     + a[2]*lnT + a[3]*T    + a[4]*T2/2. + a[5]*T3/3. + a[6]*T4/4. + a[9]   */
     for (unsigned int i=begin_interval; i != end_interval; ++i)
       {
         const CoeffType * const a =
           this->_cea_mixture.curve_fit(species).coefficients(i);
         returnval = Antioch::if_else
           (interval == i,
            StateType(-a[0]/cache.T2/2.0 + (a[1] + a[8])/cache.T +
                      a[1]*cache.lnT/cache.T - a[2]*cache.lnT +
                      (a[2] - a[9]) - a[3]*cache.T/2.0 -
                      a[4]*cache.T2/6.0 - a[5]*cache.T3/12.0 -
                      a[6]*cache.T4/20.0),
            returnval);
       }
     return returnval;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > enable_if_c< has_size< VectorStateType >::value, void >::type Antioch::CEAEvaluator< CoeffType >::h_RT_minus_s_R (const TempCache< StateType > & cache, VectorStateType & h_RT_minus_s_R) const inline
Definition at line 353 of file cea_evaluator.h.
References antioch_assert_equal_to.
   {
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         h_RT_minus_s_R[s] = this->h_RT_minus_s_R(cache,s);
       }
     return;
   }
template<typename CoeffType > unsigned int Antioch::CEAEvaluator< CoeffType >::n_species () const inline protected
Convenience function.
Definition at line 162 of file cea_evaluator.h.
   {
     return _cea_mixture.chemical_mixture().n_species();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::CEAEvaluator< CoeffType >::s_over_R (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 291 of file cea_evaluator.h.
References antioch_assert_less, Antioch::TempCache< StateType >::lnT, Antioch::TempCache< StateType >::T, Antioch::TempCache< StateType >::T2, Antioch::TempCache< StateType >::T3, and Antioch::TempCache< StateType >::T4.
   {
     antioch_assert_less( species, this->n_species() );
     antioch_assert_less( _cea_mixture.curve_fit(species).interval(cache.T),
                          _cea_mixture.curve_fit(species).n_intervals() );
     const unsigned int interval = this->_cea_mixture.curve_fit(species).interval(cache.T);
     const CoeffType *a = this->_cea_mixture.curve_fit(species).coefficients(interval);
     /* s/R = -a0*T^-2/2 - a1*T^-1     + a2*lnT + a3*T   + a4*T^2/2 + a5*T^3/3 + a6*T^4/4 + a9 */
     return -a[0]/cache.T2/2.0 - a[1]/cache.T + a[2]*cache.lnT + a[3]*cache.T + a[4]*cache.T2/2.0 + a[5]*cache.T3/3.0 + a[6]*cache.T4/4.0 + a[9];
   }
Member Data Documentation
template<typename CoeffType = double> const CEAThermoMixture<CoeffType>& Antioch::CEAEvaluator< CoeffType >::_cea_mixture protected
Definition at line 122 of file cea_evaluator.h.
The documentation for this class was generated from the following file:
src/thermo/include/antioch/cea_evaluator.h