antioch-0.0.7: Antioch::ElementaryReaction< CoeffType > Class Template Reference
Antioch::ElementaryReaction< CoeffType > Class Template Reference
A single reaction mechanism.
#include <elementary_reaction.h>
Public Member Functions
ElementaryReaction (const unsigned int n_species, const std::string &equation, const KineticsModel::KineticsModel kin=KineticsModel::KOOIJ)
Construct a single reaction mechanism.
~ElementaryReaction ()
template<typename StateType , typename VectorStateType >
StateType compute_forward_rate_coefficient (const VectorStateType &molar_densities, const StateType &T) const
template<typename StateType , typename VectorStateType >
void compute_forward_rate_coefficient_and_derivatives (const VectorStateType &molar_densities, const StateType &T, StateType &kfwd, StateType &dkfwd_dT, VectorStateType &dkfwd_dX) const
unsigned int n_species () const
std::string equation () const
ReactionType::ReactionType type () const
Type of reaction.
void set_type (const ReactionType::ReactionType type)
Set the type of reaction.
KineticsModel::KineticsModel kinetics_model () const
Model of kinetics.
void set_kinetics_model (const KineticsModel::KineticsModel kin)
Set the model of kinetics.
bool initialized () const
unsigned int n_reactants () const
unsigned int n_products () const
const std::string & reactant_name (const unsigned int r) const
const std::string & product_name (const unsigned int p) const
unsigned int reactant_id (const unsigned int r) const
unsigned int product_id (const unsigned int p) const
unsigned int reactant_stoichiometric_coefficient (const unsigned int r) const
unsigned int product_stoichiometric_coefficient (const unsigned int p) const
void add_reactant (const std::string &name, const unsigned int r_id, const unsigned int stoichiometric_coeff)
void add_product (const std::string &name, const unsigned int p_id, const unsigned int stoichiometric_coeff)
void set_efficiency (const std::string &, const unsigned int s, const CoeffType efficiency)
CoeffType efficiency (const unsigned int s) const
void initialize ()
Computes derived quantities.
int gamma () const
template<typename StateType , typename VectorStateType >
StateType equilibrium_constant (const StateType &P0_RT, const VectorStateType &h_RT_minus_s_R) const
template<typename StateType , typename VectorStateType >
void equilibrium_constant_and_derivative (const StateType &T, const StateType &P0_RT, const VectorStateType &h_RT_minus_s_R, const VectorStateType &ddT_h_RT_minus_s_R, StateType &keq, StateType &dkeq_dT) const
template<typename StateType , typename VectorStateType >
StateType compute_rate_of_progress (const VectorStateType &molar_densities, const StateType &T, const StateType &P0_RT, const VectorStateType &h_RT_minus_s_R) const
template<typename StateType , typename VectorStateType >
void compute_rate_of_progress_and_derivatives (const VectorStateType &molar_densities, const ChemicalMixture< CoeffType > &chem_mixture, const StateType &T, const StateType &P0_RT, const VectorStateType &h_RT_minus_s_R, const VectorStateType &dh_RT_minus_s_R_dT, StateType &net_reaction_rate, StateType &dnet_rate_dT, VectorStateType &dnet_rate_dX_s) const
const KineticsType< CoeffType > & forward_rate (unsigned int ir=0) const
Return const reference to the forward rate object.
KineticsType< CoeffType > & forward_rate (unsigned int ir=0)
Return writeable reference to the forward rate object.
void add_forward_rate (KineticsType< CoeffType > *rate)
Add a forward rate object.
void swap_forward_rates (unsigned int irate, unsigned int jrate)
Swap two forward rates object.
unsigned int n_rate_constants () const
Return the number of rate constant objects.
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Protected Attributes
unsigned int _n_species
std::string _equation
std::vector< std::string > _reactant_names
std::vector< std::string > _product_names
std::vector< unsigned int > _reactant_ids
std::vector< unsigned int > _product_ids
std::vector< unsigned int > _reactant_stoichiometry
std::vector< unsigned int > _product_stoichiometry
std::vector< CoeffType > _efficiencies
std::vector< unsigned int > _species_reactant_stoichiometry
std::vector< unsigned int > _species_product_stoichiometry
std::vector< int > _species_delta_stoichiometry
int _gamma
bool _initialized
ReactionType::ReactionType _type
KineticsModel::KineticsModel _kintype
std::vector< KineticsType
< CoeffType > * > _forward_rate
The forward reaction rate modified Arrhenius form.
Detailed Description
template<typename CoeffType = double>
class Antioch::ElementaryReaction< CoeffType >
A single reaction mechanism.
This class encapsulates an elementary reaction process. An elementary process rate constant is defined by the equation
with being a kinetics model (see base classes Reaction and KineticsType), and the mixture concentration (or pressure, it's equivalent, in an ideal gas model). All reactions are assumed to be reversible. By default, the kinetics model is a KooijRate.
We have:
with the concentration of species .
Definition at line 60 of file elementary_reaction.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::ElementaryReaction< CoeffType >::ElementaryReaction (const unsigned int n_species, const std::string & equation, const KineticsModel::KineticsModel kin = KineticsModel::KOOIJ) inline
Construct a single reaction mechanism.
Definition at line 91 of file elementary_reaction.h.
     :Reaction<CoeffType>(n_species,equation,ReactionType::ELEMENTARY,kin)
   {
     return;
   }
template<typename CoeffType > Antioch::ElementaryReaction< CoeffType >::~ElementaryReaction () inline
Definition at line 102 of file elementary_reaction.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType > void Antioch::Reaction< CoeffType >::add_forward_rate (KineticsType< CoeffType > * rate) inline inherited
Add a forward rate object.
Definition at line 334 of file reaction.h.
Referenced by Antioch::read_reaction_set_data_xml(), and tester().
   {
     _forward_rate.push_back(rate);
     return;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::add_product (const std::string & name, const unsigned int p_id, const unsigned int stoichiometric_coeff) inline inherited
Definition at line 448 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     antioch_assert_less(p_id, this->n_species());
     _product_names.push_back(name);
     _product_ids.push_back(p_id);
     _product_stoichiometry.push_back(stoichiometric_coeff);
     return;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::add_reactant (const std::string & name, const unsigned int r_id, const unsigned int stoichiometric_coeff) inline inherited
Definition at line 435 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     antioch_assert_less(r_id, this->n_species());
     _reactant_names.push_back(name);
     _reactant_ids.push_back(r_id);
     _reactant_stoichiometry.push_back(stoichiometric_coeff);
     return;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::ElementaryReaction< CoeffType >::compute_forward_rate_coefficient (const VectorStateType & molar_densities, const StateType & T) const inline
Definition at line 112 of file elementary_reaction.h.
References antioch_assert_equal_to.
Referenced by tester().
   {
     antioch_assert_equal_to(1, Reaction<CoeffType>::_forward_rate.size());
     //k(T,[M]) = alpha(T)
     return (*this->_forward_rate[0])(T);
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > void Antioch::ElementaryReaction< CoeffType >::compute_forward_rate_coefficient_and_derivatives (const VectorStateType & molar_densities, const StateType & T, StateType & kfwd, StateType & dkfwd_dT, VectorStateType & dkfwd_dX) const inline
Definition at line 124 of file elementary_reaction.h.
References antioch_assert_equal_to, and Antioch::set_zero().
Referenced by tester().
   {
     //dk_dT = dalpha_dT(T)
     this->_forward_rate[0]->compute_rate_and_derivative(T,kfwd,dkfwd_dT);
     //dk_dCi = 0.
     antioch_assert_equal_to(dkfwd_dX.size(),this->n_species());
     Antioch::set_zero(dkfwd_dX);
     return;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::Reaction< CoeffType >::compute_rate_of_progress (const VectorStateType & molar_densities, const StateType & T, const StateType & P0_RT, const VectorStateType & h_RT_minus_s_R) const inline inherited
Definition at line 784 of file reaction.h.
   {
     StateType kfwd_times_reactants = this->compute_forward_rate_coefficient(molar_densities,T);
     StateType Keq = this->equilibrium_constant( P0_RT, h_RT_minus_s_R );
     StateType kbkwd_times_products = kfwd_times_reactants/Keq;
     // Rfwd
     for (unsigned int ro=0; ro < this->n_reactants(); ro++)
       {
         kfwd_times_reactants     *=
           ant_pow( molar_densities[this->reactant_id(ro)],
             static_cast<int>(this->reactant_stoichiometric_coefficient(ro)) );
       }
     // Rbkwd
     for (unsigned int po=0; po< this->n_products(); po++)
       {
         kbkwd_times_products     *=
           ant_pow( molar_densities[this->product_id(po)],
             static_cast<int>(this->product_stoichiometric_coefficient(po)) );
       }
     return kfwd_times_reactants - kbkwd_times_products;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > void Antioch::Reaction< CoeffType >::compute_rate_of_progress_and_derivatives (const VectorStateType & molar_densities, const ChemicalMixture< CoeffType > & chem_mixture, const StateType & T, const StateType & P0_RT, const VectorStateType & h_RT_minus_s_R, const VectorStateType & dh_RT_minus_s_R_dT, StateType & net_reaction_rate, StateType & dnet_rate_dT, VectorStateType & dnet_rate_dX_s) const inline inherited
Todo:
Should we make this work arrays that get passed in so we aren't allocating/deallocating here?
Definition at line 816 of file reaction.h.
References antioch_assert_equal_to, Antioch::set_zero(), and Antioch::zero_clone().
   {
     antioch_assert_equal_to (molar_densities.size(), this->n_species());
     StateType kfwd = Antioch::zero_clone(T);
     StateType dkfwd_dT = Antioch::zero_clone(T);
     VectorStateType dkfwd_dX_s = Antioch::zero_clone(molar_densities);
     VectorStateType dkbkwd_dX_s = Antioch::zero_clone(molar_densities);
     compute_forward_rate_coefficient_and_derivatives(molar_densities, T, kfwd, dkfwd_dT ,dkfwd_dX_s);
     StateType keq = Antioch::zero_clone(T);
     StateType dkeq_dT = Antioch::zero_clone(T);
     equilibrium_constant_and_derivative( T, P0_RT, h_RT_minus_s_R,
                                          dh_RT_minus_s_R_dT,
                                          keq, dkeq_dT );
     const StateType kbkwd = kfwd/keq;
     const StateType dkbkwd_dT = (dkfwd_dT - kbkwd*dkeq_dT)/keq;
     for(unsigned int s = 0; s < this->n_species(); s++)
       {
         dkbkwd_dX_s[s] = dkfwd_dX_s[s]/keq;
       }
     // If users want to use valarrays, then the output reference sizes
     // had better already match the input value sizes...
     StateType Rfwd = Antioch::zero_clone(kfwd);
     StateType dRfwd_dT = Antioch::zero_clone(kbkwd);
     StateType Rbkwd = Antioch::zero_clone(dkfwd_dT);
     StateType dRbkwd_dT = Antioch::zero_clone(dkbkwd_dT);
     // We need to construct using an input StateType argument if we
     // want StateType==valarray to have the right sizes
     // valarray compatibility makes this a bit redundant, but not much
     // worse than the previous version
     VectorStateType dRfwd_dX_s(this->n_species(), kfwd);
     VectorStateType dRbkwd_dX_s(this->n_species(), kbkwd);
     Antioch::set_zero(dRfwd_dX_s);
     Antioch::set_zero(dRbkwd_dX_s);
     // pre-fill the participating species partials with the rates
     for (unsigned int r=0; r< this->n_reactants(); r++)
       {
         dRfwd_dX_s[this->reactant_id(r)] = kfwd;
       }
     for (unsigned int p=0; p < this->n_products(); p++)
       {
         dRbkwd_dX_s[this->product_id(p)] = kbkwd;
       }
     //init
     Rfwd = kfwd;
     dRfwd_dT = dkfwd_dT;
     Rbkwd = kbkwd;
     dRbkwd_dT = dkbkwd_dT;
     // Rfwd & derivatives
     for (unsigned int ro=0; ro < this->n_reactants(); ro++)
       {
         const StateType val =
           ant_pow( molar_densities[this->reactant_id(ro)],
             static_cast<int>(this->reactant_stoichiometric_coefficient(ro)) );
         const StateType dval =
           ( static_cast<CoeffType>(this->reactant_stoichiometric_coefficient(ro))*
             ant_pow( molar_densities[this->reactant_id(ro)],
               static_cast<int>(this->reactant_stoichiometric_coefficient(ro))-1 )
             );
         Rfwd     *= val;
         dRfwd_dT *= val;
         for (unsigned int ri=0; ri<this->n_reactants(); ri++)
           {
             dRfwd_dX_s[this->reactant_id(ri)] *= (ri == ro) ? dval : val;
           }
       }
     const StateType facfwd = Rfwd/kfwd;
     for (unsigned int s = 0; s < this->n_species(); s++)
       {
         dRfwd_dX_s[s] += facfwd * dkfwd_dX_s[s];
       }
     // Rbkwd & derivatives
     for (unsigned int po=0; po< this->n_products(); po++)
       {
         const StateType val =
           ant_pow( molar_densities[this->product_id(po)],
             static_cast<int>(this->product_stoichiometric_coefficient(po)) );
         const StateType dval =
           ( static_cast<CoeffType>(this->product_stoichiometric_coefficient(po))*
             ant_pow( molar_densities[this->product_id(po)],
               static_cast<int>(this->product_stoichiometric_coefficient(po))-1 )
             );
         Rbkwd     *= val;
         dRbkwd_dT *= val;
         for (unsigned int pi=0; pi<this->n_products(); pi++)
           {
             dRbkwd_dX_s[this->product_id(pi)] *= (pi == po) ? dval : val;
           }
       }
     const StateType facbkwd = Rbkwd/kbkwd;
     for (unsigned int s = 0; s < this->n_species(); s++)
       {
         dRbkwd_dX_s[s] += facbkwd * dkbkwd_dX_s[s];
       }
     net_reaction_rate = Rfwd - Rbkwd;
     dnet_rate_dT = dRfwd_dT - dRbkwd_dT;
     for (unsigned int s = 0; s < this->n_species(); s++)
       {
         dnet_rate_dX_s[s] = dRfwd_dX_s[s] - dRbkwd_dX_s[s];
       }
     return;
   }
template<typename CoeffType > CoeffType Antioch::Reaction< CoeffType >::efficiency (const unsigned int s) const inline inherited
Definition at line 474 of file reaction.h.
References antioch_assert_equal_to, antioch_assert_less, and Antioch::ReactionType::THREE_BODY.
   {
     antioch_assert_less(s, _efficiencies.size());
     antioch_assert_equal_to(_type, ReactionType::THREE_BODY);
     return _efficiencies[s];
   }
template<typename CoeffType > std::string Antioch::Reaction< CoeffType >::equation () const inline inherited
Returns
the equation for this reaction.
Definition at line 289 of file reaction.h.
   {
     return _equation;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::Reaction< CoeffType >::equilibrium_constant (const StateType & P0_RT, const VectorStateType & h_RT_minus_s_R) const inline inherited
Todo:
Make this assertion vector-compatible
Definition at line 587 of file reaction.h.
References antioch_assert, antioch_assert_equal_to, and antioch_assert_greater.
Referenced by Antioch::ReactionSet< CoeffType >::get_reactive_scheme().
   {
     using std::exp;
     antioch_assert( this->initialized() );
     // antioch_assert_greater( P0_RT, 0.0 );
     antioch_assert_greater( h_RT_minus_s_R.size(), 0 );
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     antioch_assert_equal_to( _species_delta_stoichiometry.size(), this->n_species() );
     StateType exppower = -( static_cast<CoeffType>(_species_delta_stoichiometry[0])*
                             h_RT_minus_s_R[0] );
     for (unsigned int s=1; s < this->n_species(); s++)
       {
         exppower += -( static_cast<CoeffType>(_species_delta_stoichiometry[s])*
                        h_RT_minus_s_R[s] );
       }
     return ant_pow( P0_RT, static_cast<CoeffType>(this->gamma()) )*exp(exppower);
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > void Antioch::Reaction< CoeffType >::equilibrium_constant_and_derivative (const StateType & T, const StateType & P0_RT, const VectorStateType & h_RT_minus_s_R, const VectorStateType & ddT_h_RT_minus_s_R, StateType & keq, StateType & dkeq_dT) const inline inherited
Todo:
Make these assertions vector-compatible
Definition at line 615 of file reaction.h.
References antioch_assert, antioch_assert_equal_to, and antioch_assert_greater.
   {
     antioch_assert(this->initialized());
     // antioch_assert_greater( P0_RT, 0.0 );
     // antioch_assert_greater( T, 0.0 );
     antioch_assert_greater( h_RT_minus_s_R.size(), 0 );
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     antioch_assert_equal_to( ddT_h_RT_minus_s_R.size(), this->n_species() );
     antioch_assert_equal_to( _species_delta_stoichiometry.size(), this->n_species() );
     // get the equilibrium constant
     keq = this->equilibrium_constant( P0_RT, h_RT_minus_s_R );
     StateType ddT_exppower = -( static_cast<CoeffType>(_species_delta_stoichiometry[0])*
                                 ddT_h_RT_minus_s_R[0] );
     for (unsigned int s=1; s<this->n_species(); s++)
       ddT_exppower += -( static_cast<CoeffType>(_species_delta_stoichiometry[s])*
                          ddT_h_RT_minus_s_R[s] );
     // compute its derivative
     dkeq_dT = keq*(-static_cast<CoeffType>(this->gamma())/T + ddT_exppower);
     return;
   }
template<typename CoeffType > const KineticsType< CoeffType > & Antioch::Reaction< CoeffType >::forward_rate (unsigned int ir = 0) const inline inherited
Return const reference to the forward rate object.
Definition at line 490 of file reaction.h.
References antioch_assert_less.
   {
     antioch_assert_less(ir,_forward_rate.size());
     return *_forward_rate[ir];
   }
template<typename CoeffType > KineticsType< CoeffType > & Antioch::Reaction< CoeffType >::forward_rate (unsigned int ir = 0) inline inherited
Return writeable reference to the forward rate object.
Definition at line 498 of file reaction.h.
References antioch_assert_less.
   {
     antioch_assert_less(ir,_forward_rate.size());
     return *_forward_rate[ir];
   }
template<typename CoeffType > int Antioch::Reaction< CoeffType >::gamma () const inline inherited
Definition at line 483 of file reaction.h.
   {
     return _gamma;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::initialize () inline inherited
Computes derived quantities.
Definition at line 538 of file reaction.h.
   {
     // Stoichiometric coefficients, by species id
     {
       _species_reactant_stoichiometry.resize(this->n_species());
       _species_product_stoichiometry.resize(this->n_species());
       _species_delta_stoichiometry.resize(this->n_species());
       std::fill( _species_reactant_stoichiometry.begin(),
                  _species_reactant_stoichiometry.end(),
                  0 );
       std::fill( _species_product_stoichiometry.begin(),
                  _species_product_stoichiometry.end(),
                  0);
     }
     for (unsigned int r=0; r< this->n_reactants(); r++)
       {
         _species_reactant_stoichiometry[this->reactant_id(r)] =
           this->reactant_stoichiometric_coefficient(r);
       }
     for (unsigned int p=0; p < this->n_products(); p++)
       {
         _species_product_stoichiometry[this->product_id(p)] =
           this->product_stoichiometric_coefficient(p);
       }
     // find the delta stoichiometric coefficient for each species,
     // and the sum of the deltas
     _gamma = 0;
     for (unsigned int s=0; s<this->n_species(); s++)
       {
         _species_delta_stoichiometry[s] =
           ( _species_product_stoichiometry[s] -
             _species_reactant_stoichiometry[s] );
         _gamma += _species_delta_stoichiometry[s];
       }
     // set initialization flag
     _initialized = true;
   }
template<typename CoeffType > bool Antioch::Reaction< CoeffType >::initialized () const inline inherited
Definition at line 326 of file reaction.h.
   {
     return _initialized;
   }
template<typename CoeffType > KineticsModel::KineticsModel Antioch::Reaction< CoeffType >::kinetics_model () const inline inherited
Model of kinetics.
Definition at line 311 of file reaction.h.
   {
     return _kintype;
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::n_products () const inline inherited
Returns
the number of products.
Definition at line 373 of file reaction.h.
References antioch_assert_equal_to, and antioch_assert_less.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::ReactionSet< CoeffType >::print_chemical_scheme().
   {
     antioch_assert_less(_product_ids.size(), this->n_species());
     antioch_assert_equal_to(_product_ids.size(), _product_stoichiometry.size());
     antioch_assert_equal_to(_product_ids.size(),  _product_names.size());
     return _product_ids.size();
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::n_rate_constants () const inline inherited
Return the number of rate constant objects.
Definition at line 342 of file reaction.h.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     return _forward_rate.size();
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::n_reactants () const inline inherited
Returns
the number of reactants.
Definition at line 363 of file reaction.h.
References antioch_assert_equal_to, and antioch_assert_less.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::ReactionSet< CoeffType >::print_chemical_scheme().
   {
     antioch_assert_less(_reactant_ids.size(), this->n_species());
     antioch_assert_equal_to(_reactant_ids.size(), _reactant_stoichiometry.size());
     antioch_assert_equal_to(_reactant_ids.size(), _reactant_names.size());
     return _reactant_ids.size();
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::n_species () const inline inherited
Definition at line 282 of file reaction.h.
   {
     return _n_species;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::print (std::ostream & os = std::cout) const inline inherited
Formatted print, by default to std::cout.
Definition at line 651 of file reaction.h.
References Antioch::ReactionType::THREE_BODY.
   {
     os << "# Gas-Phase Reaction \"" << _equation << "\":\n";
     if (this->n_species())
       {
         os << "#   reactants: ";
         for (unsigned int r=0; r<this->n_reactants(); r++)
           os << this->reactant_name(r) << ":"
              << this->reactant_stoichiometric_coefficient(r) << " ";
         os << "\n"
            << "#   products:  ";
         for (unsigned int p=0; p<this->n_products(); p++)
           os << this->product_name(p) << ":"
              << this->product_stoichiometric_coefficient(p) << " ";
       }
     for(unsigned int ir = 0; ir < _forward_rate.size(); ir++)
       {
         os << "\n#   forward rate eqn: " << *_forward_rate[ir];
       }
     if (_type == ReactionType::THREE_BODY)
       {
         os << "\n#   efficiencies: ";
         for (unsigned int s=0; s<this->n_species(); s++)
           os << s << ":" << this->efficiency(s) << " ";
       }
     os << "\n#";
     return;
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::product_id (const unsigned int p) const inline inherited
Definition at line 408 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::ReactionSet< CoeffType >::print_chemical_scheme().
   {
     antioch_assert_less(p, _product_ids.size());
     antioch_assert_less(_product_ids[p], this->n_species());
     return _product_ids[p];
   }
template<typename CoeffType > const std::string & Antioch::Reaction< CoeffType >::product_name (const unsigned int p) const inline inherited
Returns
the name of the p th product.
Definition at line 391 of file reaction.h.
References antioch_assert_less.
   {
     antioch_assert_less(p, _product_names.size());
     return _product_names[p];
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::product_stoichiometric_coefficient (const unsigned int p) const inline inherited
Definition at line 426 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::ReactionSet< CoeffType >::print_chemical_scheme().
   {
     antioch_assert_less(p, _product_stoichiometry.size());
     antioch_assert_less(_product_ids[p], this->n_species());
     return _product_stoichiometry[p];
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::reactant_id (const unsigned int r) const inline inherited
Definition at line 399 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::ReactionSet< CoeffType >::print_chemical_scheme().
   {
     antioch_assert_less(r, _reactant_ids.size());
     antioch_assert_less(_reactant_ids[r], this->n_species());
     return _reactant_ids[r];
   }
template<typename CoeffType > const std::string & Antioch::Reaction< CoeffType >::reactant_name (const unsigned int r) const inline inherited
Returns
the name of the r th reactant.
Definition at line 383 of file reaction.h.
References antioch_assert_less.
   {
     antioch_assert_less(r, _reactant_names.size());
     return _reactant_names[r];
   }
template<typename CoeffType > unsigned int Antioch::Reaction< CoeffType >::reactant_stoichiometric_coefficient (const unsigned int r) const inline inherited
Definition at line 417 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::ReactionSet< CoeffType >::print_chemical_scheme().
   {
     antioch_assert_less(r, _reactant_stoichiometry.size());
     antioch_assert_less(_reactant_ids[r], this->n_species());
     return _reactant_stoichiometry[r];
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::set_efficiency (const std::string & , const unsigned int s, const CoeffType efficiency) inline inherited
Definition at line 461 of file reaction.h.
References antioch_assert_equal_to, antioch_assert_less, and Antioch::ReactionType::THREE_BODY.
Referenced by Antioch::read_reaction_set_data_xml(), and tester().
   {
     antioch_assert_less(s, this->n_species());
     antioch_assert_less(s, _efficiencies.size());
     antioch_assert_equal_to(_type, ReactionType::THREE_BODY);
     _efficiencies[s] = efficiency;
     return;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::set_kinetics_model (const KineticsModel::KineticsModel kin) inline inherited
Set the model of kinetics.
Definition at line 318 of file reaction.h.
   {
     _kintype = kin;
     return;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::set_type (const ReactionType::ReactionType type) inline inherited
Set the type of reaction.
reversible reactions are considered.
Definition at line 303 of file reaction.h.
   {
     _type = type;
     return;
   }
template<typename CoeffType > void Antioch::Reaction< CoeffType >::swap_forward_rates (unsigned int irate, unsigned int jrate) inline inherited
Swap two forward rates object.
Definition at line 349 of file reaction.h.
References antioch_assert_less.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     antioch_assert_less(irate,_forward_rate.size());
     antioch_assert_less(jrate,_forward_rate.size());
     KineticsType<CoeffType>* rate_tmp = _forward_rate[jrate];
     _forward_rate[jrate] = _forward_rate[irate];
     _forward_rate[irate] = rate_tmp;
     return;
   }
template<typename CoeffType > ReactionType::ReactionType Antioch::Reaction< CoeffType >::type () const inline inherited
Type of reaction.
reversible reactions are considered.
Definition at line 296 of file reaction.h.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     return _type;
   }
Member Data Documentation
template<typename CoeffType = double> std::vector<CoeffType> Antioch::Reaction< CoeffType >::_efficiencies protected inherited
Definition at line 265 of file reaction.h.
Referenced by Antioch::Reaction< CoeffType >::Reaction().
template<typename CoeffType = double> std::string Antioch::Reaction< CoeffType >::_equation protected inherited
Definition at line 258 of file reaction.h.
template<typename CoeffType = double> std::vector<KineticsType<CoeffType>* > Antioch::Reaction< CoeffType >::_forward_rate protected inherited
The forward reaction rate modified Arrhenius form.
Definition at line 275 of file reaction.h.
template<typename CoeffType = double> int Antioch::Reaction< CoeffType >::_gamma protected inherited
Definition at line 269 of file reaction.h.
template<typename CoeffType = double> bool Antioch::Reaction< CoeffType >::_initialized protected inherited
Definition at line 270 of file reaction.h.
template<typename CoeffType = double> KineticsModel::KineticsModel Antioch::Reaction< CoeffType >::_kintype protected inherited
Definition at line 272 of file reaction.h.
template<typename CoeffType = double> unsigned int Antioch::Reaction< CoeffType >::_n_species protected inherited
Definition at line 257 of file reaction.h.
Referenced by Antioch::Reaction< CoeffType >::Reaction().
template<typename CoeffType = double> std::vector<unsigned int> Antioch::Reaction< CoeffType >::_product_ids protected inherited
Definition at line 262 of file reaction.h.
template<typename CoeffType = double> std::vector<std::string> Antioch::Reaction< CoeffType >::_product_names protected inherited
Definition at line 260 of file reaction.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::Reaction< CoeffType >::_product_stoichiometry protected inherited
Definition at line 264 of file reaction.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::Reaction< CoeffType >::_reactant_ids protected inherited
Definition at line 261 of file reaction.h.
template<typename CoeffType = double> std::vector<std::string> Antioch::Reaction< CoeffType >::_reactant_names protected inherited
Definition at line 259 of file reaction.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::Reaction< CoeffType >::_reactant_stoichiometry protected inherited
Definition at line 263 of file reaction.h.
template<typename CoeffType = double> std::vector<int> Antioch::Reaction< CoeffType >::_species_delta_stoichiometry protected inherited
Definition at line 268 of file reaction.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::Reaction< CoeffType >::_species_product_stoichiometry protected inherited
Definition at line 267 of file reaction.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::Reaction< CoeffType >::_species_reactant_stoichiometry protected inherited
Definition at line 266 of file reaction.h.
template<typename CoeffType = double> ReactionType::ReactionType Antioch::Reaction< CoeffType >::_type protected inherited
Definition at line 271 of file reaction.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/elementary_reaction.h