antioch-0.0.7: Antioch::CEAThermoMixture< NumericType > Class Template Reference
Antioch::CEAThermoMixture< NumericType > Class Template Reference
#include <cea_mixture_ascii_parsing.h>
Public Member Functions
CEAThermoMixture (const ChemicalMixture< CoeffType > &chem_mixture)
virtual ~CEAThermoMixture ()
Destructor.
void add_curve_fit (const std::string &species_name, const std::vector< CoeffType > &coeffs)
const CEACurveFit< CoeffType > & curve_fit (unsigned int s) const
CoeffType cp_at_200p1 (unsigned int s) const
bool check () const
Checks that curve fits have been specified for all species in the mixture.
const ChemicalMixture
< CoeffType > & chemical_mixture () const
Protected Attributes
const ChemicalMixture
< CoeffType > & _chem_mixture
std::vector< CEACurveFit
< CoeffType > * > _species_curve_fits
std::vector< CoeffType > _cp_at_200p1
Private Member Functions
CEAThermoMixture ()
Default constructor.
Detailed Description
template<class NumericType>
class Antioch::CEAThermoMixture< NumericType >
Definition at line 45 of file cea_mixture_ascii_parsing.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::CEAThermoMixture< CoeffType >::CEAThermoMixture (const ChemicalMixture< CoeffType > & chem_mixture)
Definition at line 90 of file cea_mixture.h.
     : _chem_mixture(chem_mixture),
       _species_curve_fits(chem_mixture.n_species(), NULL),
       _cp_at_200p1( _species_curve_fits.size() )
   {
     return;
   }
template<typename CoeffType > Antioch::CEAThermoMixture< CoeffType >::~CEAThermoMixture () virtual
Destructor.
virtual so this can be subclassed by the user.
Definition at line 100 of file cea_mixture.h.
   {
     // Clean up all the CEACurveFits we created
     for( typename std::vector<CEACurveFit<CoeffType>* >::iterator it = _species_curve_fits.begin();
          it < _species_curve_fits.end(); ++it )
       {
         delete (*it);
       }
     return;
   }
template<class NumericType> Antioch::CEAThermoMixture< NumericType >::CEAThermoMixture () private
Default constructor.
Private to force to user to supply a ChemicalMixture object.
Member Function Documentation
template<typename CoeffType > void Antioch::CEAThermoMixture< CoeffType >::add_curve_fit (const std::string & species_name, const std::vector< CoeffType > & coeffs) inline
Definition at line 115 of file cea_mixture.h.
References antioch_assert, and antioch_assert_less_equal.
Referenced by Antioch::read_cea_mixture_data_ascii().
   {
     antioch_assert( _chem_mixture.active_species_name_map().find(species_name) !=
                     _chem_mixture.active_species_name_map().end() );
     unsigned int s = _chem_mixture.active_species_name_map().find(species_name)->second;
     antioch_assert_less_equal( s, _species_curve_fits.size() );
     antioch_assert( !_species_curve_fits[s] );
     _species_curve_fits[s] = new CEACurveFit<CoeffType>(coeffs);
     CEAEvaluator<CoeffType> evaluator( *this );
     _cp_at_200p1[s] = evaluator.cp( TempCache<CoeffType>(200.1), s );
     return;
   }
template<typename CoeffType > bool Antioch::CEAThermoMixture< CoeffType >::check () const inline
Checks that curve fits have been specified for all species in the mixture.
Definition at line 137 of file cea_mixture.h.
Referenced by Antioch::read_cea_mixture_data_ascii().
   {
     bool valid = true;
     for( typename std::vector<CEACurveFit<CoeffType>* >::const_iterator it = _species_curve_fits.begin();
          it != _species_curve_fits.end(); ++ it )
       {
         if( !(*it) )
           valid = false;
       }
     return valid;
   }
template<typename CoeffType > const ChemicalMixture< CoeffType > & Antioch::CEAThermoMixture< CoeffType >::chemical_mixture () const inline
Definition at line 169 of file cea_mixture.h.
Referenced by Antioch::read_cea_mixture_data_ascii().
   {
     return _chem_mixture;
   }
template<typename CoeffType > CoeffType Antioch::CEAThermoMixture< CoeffType >::cp_at_200p1 (unsigned int s) const inline
Definition at line 161 of file cea_mixture.h.
References antioch_assert_less.
   {
     antioch_assert_less( s, _cp_at_200p1.size() );
     return _cp_at_200p1[s];
   }
template<typename CoeffType > const CEACurveFit< CoeffType > & Antioch::CEAThermoMixture< CoeffType >::curve_fit (unsigned int s) const inline
Definition at line 153 of file cea_mixture.h.
References antioch_assert_less.
   {
     antioch_assert_less( s, _species_curve_fits.size() );
     return *_species_curve_fits[s];
   }
Member Data Documentation
template<class NumericType> const ChemicalMixture<CoeffType>& Antioch::CEAThermoMixture< NumericType >::_chem_mixture protected
Definition at line 74 of file cea_mixture.h.
template<class NumericType> std::vector<CoeffType> Antioch::CEAThermoMixture< NumericType >::_cp_at_200p1 protected
Definition at line 78 of file cea_mixture.h.
template<class NumericType> std::vector<CEACurveFit<CoeffType>* > Antioch::CEAThermoMixture< NumericType >::_species_curve_fits protected
Definition at line 76 of file cea_mixture.h.
The documentation for this class was generated from the following files:
src/parsing/include/antioch/cea_mixture_ascii_parsing.h
src/thermo/include/antioch/cea_mixture.h