antioch-0.0.7: Antioch::KineticsType< CoeffType > Class Template Reference
Antioch::KineticsType< CoeffType > Class Template Reference abstract
base class for kinetics models
#include <kinetics_type.h>
Public Member Functions
KineticsType (const KineticsModel::KineticsModel type)
virtual ~KineticsType ()
template<typename StateType >
StateType operator() (const StateType &T) const
template<typename StateType >
StateType derivative (const StateType &T) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &T, StateType &rate, StateType &drate_dT) const
virtual const std::string numeric () const =0
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Private Attributes
KineticsModel::KineticsModel my_type
Friends
std::ostream & operator<< (std::ostream &os, const KineticsType &rate)
Formatted print.
Detailed Description
template<typename CoeffType>
class Antioch::KineticsType< CoeffType >
base class for kinetics models
Definition at line 62 of file kinetics_type.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::KineticsType< CoeffType >::KineticsType (const KineticsModel::KineticsModel type) inline
Definition at line 105 of file kinetics_type.h.
                                                                             :
     my_type(type)
   {
     return;
   }
template<typename CoeffType > Antioch::KineticsType< CoeffType >::~KineticsType () inline virtual
Definition at line 113 of file kinetics_type.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType >::compute_rate_and_derivative (const StateType & T, StateType & rate, StateType & drate_dT) const inline
Returns
error because I cannot make it pure virtual.
Definition at line 229 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::derivative (const StateType & T) const inline
Returns
error because I cannot make it pure virtual.
Definition at line 175 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by tester(), and vectester().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType> virtual const std::string Antioch::KineticsType< CoeffType >::numeric () const pure virtual
Implemented in Antioch::VantHoffRate< CoeffType >, Antioch::KooijRate< CoeffType >, Antioch::ArrheniusRate< CoeffType >, Antioch::BerthelotHercourtEssenRate< CoeffType >, Antioch::HercourtEssenRate< CoeffType >, and Antioch::BerthelotRate< CoeffType >.
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::operator() (const StateType & T) const inline
Returns
error because I cannot make it pure virtual.
Definition at line 121 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > void Antioch::KineticsType< CoeffType >::print (std::ostream & os = std::cout) const inline
Formatted print, by default to std::cout.
Definition at line 98 of file kinetics_type.h.
   {
     os << numeric();
   }
Friends And Related Function Documentation
template<typename CoeffType> std::ostream& operator<< (std::ostream & os, const KineticsType< CoeffType > & rate) friend
Formatted print.
Definition at line 85 of file kinetics_type.h.
     {
       rate.print(os);
       return os;
     }
Member Data Documentation
template<typename CoeffType> KineticsModel::KineticsModel Antioch::KineticsType< CoeffType >::my_type private
Definition at line 92 of file kinetics_type.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/kinetics_type.h