antioch-0.0.7: Antioch::HercourtEssenRate< CoeffType > Class Template Reference
Antioch::HercourtEssenRate< CoeffType > Class Template Reference
Hercourt-Essen rate equation.
#include <hercourtessen_rate.h>
Public Member Functions
HercourtEssenRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType Tref=1.)
~HercourtEssenRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_Tref (const CoeffType Tref)
CoeffType Cf () const
CoeffType eta () const
CoeffType Tref () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_pow (T, _eta))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
template<typename StateType >
StateType operator() (const StateType &T) const
template<typename StateType >
StateType derivative (const StateType &T) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &T, StateType &rate, StateType &drate_dT) const
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)/T *(_eta)) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _Tref
Detailed Description
template<typename CoeffType = double>
class Antioch::HercourtEssenRate< CoeffType >
Hercourt-Essen rate equation.
Hercourt-Essen is a kinetics model of the form:
Thus
Internally, we use the reduced pre-exponential factor
Definition at line 53 of file hercourtessen_rate.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::HercourtEssenRate< CoeffType >::HercourtEssenRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType Tref = 1.)
Definition at line 108 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::compute_cf().
     : KineticsType<CoeffType>(KineticsModel::HERCOURT_ESSEN),
       _raw_Cf(Cf),
       _eta(eta),
       _Tref(Tref)
   {
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::HercourtEssenRate< CoeffType >::~HercourtEssenRate ()
Definition at line 120 of file hercourtessen_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::HercourtEssenRate< CoeffType >::ant_pow (T , _eta) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::Cf () const inline
Definition at line 166 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_Cf.
Referenced by Antioch::HercourtEssenRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::compute_cf () inline private
Definition at line 193 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_Cf, Antioch::HercourtEssenRate< CoeffType >::_eta, Antioch::HercourtEssenRate< CoeffType >::_raw_Cf, Antioch::HercourtEssenRate< CoeffType >::_Tref, and std::pow().
Referenced by Antioch::HercourtEssenRate< CoeffType >::HercourtEssenRate(), Antioch::HercourtEssenRate< CoeffType >::set_Cf(), and Antioch::HercourtEssenRate< CoeffType >::set_Tref().
   {
     _Cf = _raw_Cf * pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
template<typename CoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType >::compute_rate_and_derivative (const StateType & T, StateType & rate, StateType & drate_dT) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 229 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::derivative (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 175 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by tester(), and vectester().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::eta () const inline
Definition at line 171 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_eta.
Referenced by Antioch::HercourtEssenRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > const std::string Antioch::HercourtEssenRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 126 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_eta, Antioch::HercourtEssenRate< CoeffType >::_raw_Cf, and Antioch::HercourtEssenRate< CoeffType >::_Tref.
   {
     std::stringstream os;
     os << _raw_Cf;
     os << "*(T/" << _Tref << ")^" << _eta;
     return os.str();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::operator() (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 121 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > void Antioch::KineticsType< CoeffType >::print (std::ostream & os = std::cout) const inline inherited
Formatted print, by default to std::cout.
Definition at line 98 of file kinetics_type.h.
   {
     os << numeric();
   }
template<typename CoeffType = double> template<typename StateType > Antioch::HercourtEssenRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 138 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_raw_Cf, Antioch::HercourtEssenRate< CoeffType >::Cf(), and Antioch::HercourtEssenRate< CoeffType >::compute_cf().
   {
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 148 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_eta, and Antioch::HercourtEssenRate< CoeffType >::eta().
   {
     _eta = eta;
     return;
   }
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 156 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_Tref, Antioch::HercourtEssenRate< CoeffType >::compute_cf(), and Antioch::HercourtEssenRate< CoeffType >::Tref().
   {
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::Tref () const inline
Definition at line 176 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_Tref.
Referenced by Antioch::HercourtEssenRate< CoeffType >::set_Tref().
   { return _Tref; }
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_Cf private
Definition at line 59 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::Cf(), and Antioch::HercourtEssenRate< CoeffType >::compute_cf().
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_eta private
Definition at line 60 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::compute_cf(), Antioch::HercourtEssenRate< CoeffType >::eta(), Antioch::HercourtEssenRate< CoeffType >::numeric(), and Antioch::HercourtEssenRate< CoeffType >::set_eta().
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_raw_Cf private
Definition at line 58 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::compute_cf(), Antioch::HercourtEssenRate< CoeffType >::numeric(), and Antioch::HercourtEssenRate< CoeffType >::set_Cf().
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_Tref private
Definition at line 61 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::compute_cf(), Antioch::HercourtEssenRate< CoeffType >::numeric(), Antioch::HercourtEssenRate< CoeffType >::set_Tref(), and Antioch::HercourtEssenRate< CoeffType >::Tref().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::HercourtEssenRate< CoeffType >::const)
Definition at line 96 of file hercourtessen_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::HercourtEssenRate< CoeffType >::rate)
Definition at line 96 of file hercourtessen_rate.h.
template<typename CoeffType = double> _Cf(* Antioch::HercourtEssenRate< CoeffType >::this)(T)/T *(_eta))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 92 of file hercourtessen_rate.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/hercourtessen_rate.h