antioch-0.0.7: Antioch::CEACurveFit< CoeffType > Class Template Reference
Antioch::CEACurveFit< CoeffType > Class Template Reference
#include <cea_curve_fit.h>
Public Member Functions
CEACurveFit (const std::vector< CoeffType > &coeffs)
~CEACurveFit ()
unsigned int n_intervals () const
The number of intervals for this CEA curve fit.
template<typename StateType >
Antioch::rebind< StateType,
unsigned int >::type interval (const StateType &T) const
The interval the input temperature lies in.
const CoeffType * coefficients (const unsigned int interval) const
The CEA-style equilibrium curve fits are defined in terms of _n_coeffs coefficients for each range fit.
Protected Attributes
const unsigned int _n_coeffs
The number of coefficients in each interval.
const std::vector< CoeffType > _coefficients
The coefficient data.
Detailed Description
template<typename CoeffType = double>
class Antioch::CEACurveFit< CoeffType >
Definition at line 42 of file cea_curve_fit.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::CEACurveFit< CoeffType >::CEACurveFit (const std::vector< CoeffType > & coeffs) inline
Definition at line 89 of file cea_curve_fit.h.
     : _n_coeffs(10),
       _coefficients(coeffs)
   {
     return;
   }
template<typename CoeffType > Antioch::CEACurveFit< CoeffType >::~CEACurveFit () inline
Definition at line 99 of file cea_curve_fit.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType > const CoeffType * Antioch::CEACurveFit< CoeffType >::coefficients (const unsigned int interval) const inline
The CEA-style equilibrium curve fits are defined in terms of _n_coeffs coefficients for each range fit.
Returns
a pointer to the coefficients in the interval specified.
Definition at line 141 of file cea_curve_fit.h.
References antioch_assert_less, and antioch_assert_less_equal.
   {
     antioch_assert_less( interval, this->n_intervals() );
     antioch_assert_less_equal( _n_coeffs*(interval+1), _coefficients.size() );
     return &_coefficients[_n_coeffs*interval];
   }
template<typename CoeffType > template<typename StateType > Antioch::rebind< StateType, unsigned int >::type Antioch::CEACurveFit< CoeffType >::interval (const StateType & T) const inline
The interval the input temperature lies in.
Returns
which curve fit interval the input temperature lies in. The CEA thermodynamic intervals are [200-1,000], [1,000-6,000], [6,000-20,000] K
Definition at line 109 of file cea_curve_fit.h.
References Antioch::constant_clone(), Antioch::if_else(), and Antioch::zero_clone().
   {
     typedef typename
       Antioch::rebind<StateType, unsigned int>::type UIntType;
     UIntType interval;
     Antioch::zero_clone(interval, T);
     typedef typename Antioch::value_type<StateType>::type ScalarType;
     /* CEA thermodynamic intervals are:
        [200-1,000], [1,000-6,000], [6,000-20,000] K */
     interval = Antioch::if_else
       (T > ScalarType(6000.),
        Antioch::constant_clone(interval,2),
        UIntType
          (Antioch::if_else
             (T > ScalarType(1000.),
              Antioch::constant_clone(interval,1),
              Antioch::constant_clone(interval,0))));
     return interval;
   }
template<typename CoeffType > unsigned int Antioch::CEACurveFit< CoeffType >::n_intervals () const inline
The number of intervals for this CEA curve fit.
Definition at line 135 of file cea_curve_fit.h.
   { return _coefficients.size() / _n_coeffs; }
Member Data Documentation
template<typename CoeffType = double> const std::vector<CoeffType> Antioch::CEACurveFit< CoeffType >::_coefficients protected
The coefficient data.
The coeffcients are packed in linear ordering. That is, a0-a9 for the first interval, a0-a9 for the second interval, and so on.
Definition at line 81 of file cea_curve_fit.h.
template<typename CoeffType = double> const unsigned int Antioch::CEACurveFit< CoeffType >::_n_coeffs protected
The number of coefficients in each interval.
Definition at line 73 of file cea_curve_fit.h.
The documentation for this class was generated from the following file:
src/thermo/include/antioch/cea_curve_fit.h