antioch-0.0.7: Antioch::ReactionSet< CoeffType > Class Template Reference
Antioch::ReactionSet< CoeffType > Class Template Reference
This class encapsulates all the reaction mechanisms considered in a chemical nonequilibrium simulation.
#include <kinetics_evaluator.h>
Public Member Functions
ReactionSet (const ChemicalMixture< CoeffType > &chem_mixture)
Constructor.
~ReactionSet ()
unsigned int n_species () const
unsigned int n_reactions () const
void add_reaction (Reaction< CoeffType > *reaction)
Add a reaction to the system.
const Reaction< CoeffType > & reaction (const unsigned int r) const
const ChemicalMixture
< CoeffType > & chemical_mixture () const
template<typename StateType , typename VectorStateType , typename VectorReactionsType >
void compute_reaction_rates (const StateType &T, const VectorStateType &molar_densities, const VectorStateType &h_RT_minus_s_R, VectorReactionsType &net_reaction_rates) const
Compute the rates of progress for each reaction.
template<typename StateType , typename VectorStateType , typename VectorReactionsType , typename MatrixReactionsType >
void compute_reaction_rates_and_derivs (const StateType &T, const VectorStateType &molar_densities, const VectorStateType &h_RT_minus_s_R, const VectorStateType &dh_RT_minus_s_R_dT, VectorReactionsType &net_reaction_rates, VectorReactionsType &dnet_rate_dT, MatrixReactionsType &dnet_rate_dX_s) const
Compute the rates of progress and derivatives for each reaction.
template<typename StateType , typename VectorStateType >
void print_chemical_scheme (std::ostream &output, const StateType &T, const VectorStateType &molar_densities, const VectorStateType &h_RT_minus_s_R, std::vector< VectorStateType > &lossMatrix, std::vector< VectorStateType > &prodMatrix, std::vector< VectorStateType > &netMatrix) const
template<typename StateType , typename VectorStateType >
void get_reactive_scheme (const StateType &T, const VectorStateType &molar_densities, const VectorStateType &h_RT_minus_s_R, VectorStateType &netRates, VectorStateType &kfwdCoeff, VectorStateType &kbkwdCoeff, VectorStateType &kfwd, VectorStateType &kbkwd, VectorStateType &fwdC, VectorStateType &bkwdC) const
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Private Member Functions
ReactionSet ()
Private Attributes
const ChemicalMixture
< CoeffType > & _chem_mixture
std::vector< Reaction
< CoeffType > * > _reactions
const CoeffType _P0_R
Scaling for equilibrium constant.
Friends
std::ostream & operator<< (std::ostream &os, const ReactionSet< CoeffType > &rset)
Formatted print.
Detailed Description
template<typename CoeffType>
class Antioch::ReactionSet< CoeffType >
This class encapsulates all the reaction mechanisms considered in a chemical nonequilibrium simulation.
Definition at line 38 of file kinetics_evaluator.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::ReactionSet< CoeffType >::ReactionSet (const ChemicalMixture< CoeffType > & chem_mixture) inline
Constructor.
Definition at line 189 of file reaction_set.h.
     : _chem_mixture(chem_mixture),
       _P0_R(1.0e5/Constants::R_universal<CoeffType>())
   {
     return;
   }
template<typename CoeffType > Antioch::ReactionSet< CoeffType >::~ReactionSet () inline
Definition at line 199 of file reaction_set.h.
   {
     for(unsigned int ir = 1; ir < _reactions.size(); ir++)delete _reactions[ir];
     return;
   }
template<typename CoeffType> Antioch::ReactionSet< CoeffType >::ReactionSet () private
Member Function Documentation
template<typename CoeffType > void Antioch::ReactionSet< CoeffType >::add_reaction (Reaction< CoeffType > * reaction) inline
Add a reaction to the system.
Definition at line 161 of file reaction_set.h.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     _reactions.push_back(reaction);
     // and make sure it is initialized!
     _reactions.back()->initialize();
     return;
   }
template<typename CoeffType > const ChemicalMixture< CoeffType > & Antioch::ReactionSet< CoeffType >::chemical_mixture () const inline
Definition at line 181 of file reaction_set.h.
Referenced by Antioch::read_reaction_set_data_xml().
   {
     return _chem_mixture;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType , typename VectorReactionsType > void Antioch::ReactionSet< CoeffType >::compute_reaction_rates (const StateType & T, const VectorStateType & molar_densities, const VectorStateType & h_RT_minus_s_R, VectorReactionsType & net_reaction_rates) const inline
Compute the rates of progress for each reaction.
Todo:
Make these assertions vector-compatible
Definition at line 209 of file reaction_set.h.
References antioch_assert_equal_to.
   {
     antioch_assert_equal_to( net_reaction_rates.size(), this->n_reactions() );
     // antioch_assert_greater(T, 0.0);
     antioch_assert_equal_to( molar_densities.size(), this->n_species() );
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     // useful constants
     const StateType P0_RT = _P0_R/T; // used to transform equilibrium constant from pressure units
     // compute reaction forward rates & other reaction-sized arrays
     for (unsigned int rxn=0; rxn<this->n_reactions(); rxn++)
       {
         net_reaction_rates[rxn] = this->reaction(rxn).compute_rate_of_progress(molar_densities, T, P0_RT, h_RT_minus_s_R);
       }
     return;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType , typename VectorReactionsType , typename MatrixReactionsType > void Antioch::ReactionSet< CoeffType >::compute_reaction_rates_and_derivs (const StateType & T, const VectorStateType & molar_densities, const VectorStateType & h_RT_minus_s_R, const VectorStateType & dh_RT_minus_s_R_dT, VectorReactionsType & net_reaction_rates, VectorReactionsType & dnet_rate_dT, MatrixReactionsType & dnet_rate_dX_s) const inline
Compute the rates of progress and derivatives for each reaction.
Todo:
Make these assertions vector-compatible
Definition at line 237 of file reaction_set.h.
References antioch_assert_equal_to.
   {
     antioch_assert_equal_to( net_reaction_rates.size(), this->n_reactions() );
     antioch_assert_equal_to( dnet_rate_dT.size(), this->n_reactions() );
     antioch_assert_equal_to( dnet_rate_dX_s.size(), this->n_reactions() );
 #ifdef NDEBUG
 #else
     for (unsigned int r=0; r < this->n_reactions(); r++)
       {
         antioch_assert_equal_to( dnet_rate_dX_s[r].size(), this->n_species() );
       }
 #endif
     // antioch_assert_greater(T, 0.0);
     antioch_assert_equal_to( molar_densities.size(), this->n_species() );
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     // useful constants
     const StateType P0_RT = _P0_R/T; // used to transform equilibrium constant from pressure units
     // compute reaction forward rates & other reaction-sized arrays
     for (unsigned int rxn=0; rxn<this->n_reactions(); rxn++)
       {
         this->reaction(rxn).compute_rate_of_progress_and_derivatives( molar_densities, _chem_mixture,
                                                                       T, P0_RT, h_RT_minus_s_R, dh_RT_minus_s_R_dT,
                                                                       net_reaction_rates[rxn],
                                                                       dnet_rate_dT[rxn],
                                                                       dnet_rate_dX_s[rxn] );
       }
     return;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > void Antioch::ReactionSet< CoeffType >::get_reactive_scheme (const StateType & T, const VectorStateType & molar_densities, const VectorStateType & h_RT_minus_s_R, VectorStateType & netRates, VectorStateType & kfwdCoeff, VectorStateType & kbkwdCoeff, VectorStateType & kfwd, VectorStateType & kbkwd, VectorStateType & fwdC, VectorStateType & bkwdC) const inline
Todo:
Make these assertions vector-compatible
Definition at line 527 of file reaction_set.h.
References antioch_assert_equal_to, Antioch::Reaction< CoeffType >::compute_forward_rate_coefficient(), Antioch::Reaction< CoeffType >::equilibrium_constant(), Antioch::Reaction< CoeffType >::n_products(), Antioch::Reaction< CoeffType >::n_reactants(), std::pow(), Antioch::Reaction< CoeffType >::product_id(), Antioch::Reaction< CoeffType >::product_stoichiometric_coefficient(), Antioch::Reaction< CoeffType >::reactant_id(), and Antioch::Reaction< CoeffType >::reactant_stoichiometric_coefficient().
   {
     // antioch_assert_greater(T, 0.0);
     antioch_assert_equal_to( molar_densities.size(), this->n_species() );
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     // useful constants
     const StateType P0_RT = _P0_R/T; // used to transform equilibrium constant from pressure units
     netRates.resize(this->n_reactions(),0.);
     kfwdCoeff.resize(this->n_reactions(),0.);
     kfwd.resize(this->n_reactions(),0.);
     kbkwdCoeff.resize(this->n_reactions(),0.);
     kbkwd.resize(this->n_reactions(),0.);
     fwdC.resize(this->n_reactions(),1.);
     bkwdC.resize(this->n_reactions(),1.);
     // compute reaction forward rates & other reaction-sized arrays
     for (unsigned int rxn=0; rxn<this->n_reactions(); rxn++)
       {
         const Reaction<CoeffType>& reaction = this->reaction(rxn);
         kfwdCoeff[rxn] = reaction.compute_forward_rate_coefficient(molar_densities,T);
         kfwd[rxn] = kfwdCoeff[rxn];
         StateType keq = reaction.equilibrium_constant( P0_RT, h_RT_minus_s_R );
         kbkwdCoeff[rxn] = kfwdCoeff[rxn]/keq;
         kbkwd[rxn] = kbkwdCoeff[rxn];
         for (unsigned int r=0; r<reaction.n_reactants(); r++)
           {
             fwdC[rxn] *= pow( molar_densities[reaction.reactant_id(r)],
                               static_cast<int>(reaction.reactant_stoichiometric_coefficient(r)) );
           }
         kfwd[rxn] *= fwdC[rxn];
         for (unsigned int p=0; p<reaction.n_products(); p++)
           {
             bkwdC[rxn] *= pow( molar_densities[reaction.product_id(p)],
                                static_cast<int>(reaction.product_stoichiometric_coefficient(p)) );
           }
         kbkwd[rxn] *= bkwdC[rxn];
         netRates[rxn] = kfwd[rxn] - kbkwd[rxn];
       }
     return;
   }
template<typename CoeffType > unsigned int Antioch::ReactionSet< CoeffType >::n_reactions () const inline
Returns
the number of reactions.
Definition at line 154 of file reaction_set.h.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::KineticsEvaluator().
   {
     return _reactions.size();
   }
template<typename CoeffType > unsigned int Antioch::ReactionSet< CoeffType >::n_species () const inline
Returns
the number of species.
Definition at line 147 of file reaction_set.h.
Referenced by Antioch::KineticsEvaluator< CoeffType, StateType >::KineticsEvaluator().
   {
     return _chem_mixture.n_species();
   }
template<typename CoeffType > void Antioch::ReactionSet< CoeffType >::print (std::ostream & os = std::cout) const inline
Formatted print, by default to std::cout.
Definition at line 589 of file reaction_set.h.
   {
     os << "# Number of reactions: " << this->n_reactions() << "\n";
     for (unsigned int r=0; r < this->n_reactions(); r++)
       {
         os << "# " << r << '\n'
            << (*this->reaction(r)) << "\n";
       }
     return;
   }
template<typename CoeffType > template<typename StateType , typename VectorStateType > void Antioch::ReactionSet< CoeffType >::print_chemical_scheme (std::ostream & output, const StateType & T, const VectorStateType & molar_densities, const VectorStateType & h_RT_minus_s_R, std::vector< VectorStateType > & lossMatrix, std::vector< VectorStateType > & prodMatrix, std::vector< VectorStateType > & netMatrix) const inline
Definition at line 281 of file reaction_set.h.
References Antioch::Reaction< CoeffType >::n_products(), Antioch::Reaction< CoeffType >::n_reactants(), Antioch::Reaction< CoeffType >::product_id(), Antioch::Reaction< CoeffType >::product_stoichiometric_coefficient(), Antioch::Reaction< CoeffType >::reactant_id(), and Antioch::Reaction< CoeffType >::reactant_stoichiometric_coefficient().
Referenced by tester_N2N().
   {
     //filling matrixes
     VectorStateType netRate,kfwdCoeff,kbkwdCoeff,kfwd,kbkwd,fwdC,bkwdC;
     //getting reaction infos
     get_reactive_scheme(T,molar_densities,h_RT_minus_s_R,netRate,kfwdCoeff,kbkwdCoeff,kfwd,kbkwd,fwdC,bkwdC);
     lossMatrix.resize(this->n_species());
     prodMatrix.resize(this->n_species());
     netMatrix.resize(this->n_species());
     for(unsigned int s = 0; s < this->n_species(); s++)
       {
         lossMatrix[s].resize(this->n_reactions(),0.);
         prodMatrix[s].resize(this->n_reactions(),0.);
         netMatrix[s].resize(this->n_reactions(),0.);
       }
     //filling matrixes
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         const Reaction<CoeffType>& reaction = this->reaction(rxn);
         for (unsigned int r=0; r<reaction.n_reactants(); r++)
           {
             lossMatrix[reaction.reactant_id(r)][rxn] += - static_cast<CoeffType>(reaction.reactant_stoichiometric_coefficient(r)) * kfwd[rxn];
             prodMatrix[reaction.reactant_id(r)][rxn] +=   static_cast<CoeffType>(reaction.reactant_stoichiometric_coefficient(r)) * kbkwd[rxn];
             netMatrix[reaction.reactant_id(r)][rxn]  +=   lossMatrix[reaction.reactant_id(r)][rxn] + prodMatrix[reaction.reactant_id(r)][rxn];
           }
         for (unsigned int p=0; p<reaction.n_products(); p++)
           {
             lossMatrix[reaction.product_id(p)][rxn] += - static_cast<CoeffType>(reaction.product_stoichiometric_coefficient(p)) * kbkwd[rxn];
             prodMatrix[reaction.product_id(p)][rxn] +=   static_cast<CoeffType>(reaction.product_stoichiometric_coefficient(p)) * kfwd[rxn];
             netMatrix[reaction.product_id(p)][rxn]  +=   lossMatrix[reaction.product_id(p)][rxn] + prodMatrix[reaction.product_id(p)][rxn];
           }
       }
     //explanation of header
     output << "# molar units considered for those budgets (kmol, m3, s)" << std::endl;
     output << "# formatted as follow:" << std::endl;
     output << "# rows: species, columns: reactions" << std::endl;
     output << "#" << std::endl;
     output << "#         |                        equation" << std::endl;
     output << "#         |  rate coefficient forward , rate coefficient backward" << std::endl;
     output << "#         |  forward concentrations   , backward concentrations" << std::endl;
     output << "#         |  rate forward             , rate backward" << std::endl;
     output << "# ------------------------------------------------------------------" << std::endl;
     output << "# species |  production term          ,  loss term" << std::endl;
     output << "# species |  net production/loss term" << std::endl;
     output << "#" << std::endl << std::endl;
     //header
     // // equation
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << this->_reactions[rxn]->equation();
       }
     output << std::endl;
     // // coeffs
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(15) << kfwdCoeff[rxn] << "," << std::setw(15) << kbkwdCoeff[rxn];
       }
     output << std::endl;
     // // conc
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(15) << fwdC[rxn] << "," << std::setw(15) << bkwdC[rxn];
       }
     output << std::endl;
     // // rates
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(15) << kfwd[rxn] << "," << std::setw(15) << kbkwd[rxn];
       }
     output << std::endl;
     output << "----------------------------" << std::endl;
     //species
     for(unsigned int isp = 0; isp < this->n_species(); isp++)
       {
         output << std::setw(10) << _chem_mixture.chemical_species()[isp]->species();
         for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
           {
             output << std::setw(15) << std::scientific << std::setprecision(6) << prodMatrix[isp][rxn] << ","
                    << std::setw(15) << std::scientific << std::setprecision(6) << lossMatrix[isp][rxn];
           }
         output << std::endl;
         // // net
         output << std::setw(10) << "";
         for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
           {
             output << std::setw(31) << std::scientific << std::setprecision(16) << netMatrix[isp][rxn];
           }
         output << std::endl;
       }
     output << std::endl;
     output << std::endl;
     output << std::endl;
     output << "# production table" << std::endl << std::endl;
     //header
     // // equation
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << this->_reactions[rxn]->equation();
       }
     output << std::setw(31) << "Total" << std::endl;
     for(unsigned int isp = 0; isp < this->n_species(); isp++)
       {
         output << std::setw(10) << _chem_mixture.chemical_species()[isp]->species();
         CoeffType rowTotal(0.);
         for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
           {
             output << std::setw(31) << std::scientific << std::setprecision(16) << prodMatrix[isp][rxn];
             rowTotal += prodMatrix[isp][rxn];
           }
         output << std::setw(31) << std::scientific << std::setprecision(16) << rowTotal << std::endl;
       }
     output << std::endl << std::endl;
     output << "# loss table" << std::endl << std::endl;
     //header
     // // equation
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << this->_reactions[rxn]->equation();
       }
     output << std::setw(31) << "Total" << std::endl;
     for(unsigned int isp = 0; isp < this->n_species(); isp++)
       {
         output << std::setw(10) << _chem_mixture.chemical_species()[isp]->species();
         CoeffType rowTotal(0.);
         for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
           {
             output << std::setw(31) << std::scientific << std::setprecision(16) << lossMatrix[isp][rxn];
             rowTotal += lossMatrix[isp][rxn];
           }
         output << std::setw(31) << std::scientific << std::setprecision(16) << rowTotal << std::endl;
       }
     output << std::endl << std::endl;
     output << "# net table" << std::endl << std::endl;
     //header
     // // equation
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << this->_reactions[rxn]->equation();
       }
     output << std::setw(31) << "Total" << std::endl;
     CoeffType columnTotal(0.);
     std::vector<CoeffType> columnSum;
     columnSum.resize(this->n_reactions(),0.);
     CoeffType netTotalRow(0.);
     for(unsigned int isp = 0; isp < this->n_species(); isp++)
       {
         output << std::setw(10) << _chem_mixture.chemical_species()[isp]->species();
         CoeffType rowTotal(0.);
         for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
           {
             output << std::setw(31) << std::scientific << std::setprecision(16) << netMatrix[isp][rxn];
             rowTotal += netMatrix[isp][rxn];
             columnSum[rxn] += netMatrix[isp][rxn];
           }
         output << std::setw(31) << std::scientific << std::setprecision(16) << rowTotal << std::endl;
         netTotalRow += rowTotal;
       }
     output << std::setw(10) << "Total";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << std::scientific << std::setprecision(16) << columnSum[rxn];
         columnTotal += columnSum[rxn];
       }
     output << std::endl << std::endl;
     output << "sum of row sums:    " << std::scientific << std::setprecision(16) << netTotalRow << std::endl;
     output << "sum of column sums: " << std::scientific << std::setprecision(16) << columnTotal << std::endl << std::endl;
     output << "# net table, mass here (kg, m3, s)" << std::endl << std::endl;
     //header
     // // equation
     output << std::setw(10) << " ";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << this->_reactions[rxn]->equation();
       }
     output << std::setw(31) << "Total" << std::endl;
     columnTotal = 0.;
     columnSum.resize(this->n_reactions(),0.);
     netTotalRow = 0.;
     for(unsigned int isp = 0; isp < this->n_species(); isp++)
       {
         output << std::setw(10) << _chem_mixture.chemical_species()[isp]->species();
         CoeffType rowTotal(0.);
         for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
           {
             output << std::setw(31) << std::scientific << std::setprecision(16) << netMatrix[isp][rxn];
             rowTotal += netMatrix[isp][rxn] * _chem_mixture.M(isp);
             columnSum[rxn] += netMatrix[isp][rxn] * _chem_mixture.M(isp);
           }
         output << std::setw(31) << std::scientific << std::setprecision(16) << rowTotal << std::endl;
         netTotalRow += rowTotal;
       }
     output << std::setw(10) << "Total";
     for(unsigned int rxn = 0; rxn < this->n_reactions(); rxn++)
       {
         output << std::setw(31) << std::scientific << std::setprecision(16) << columnSum[rxn];
         columnTotal += columnSum[rxn];
       }
     output << std::endl << std::endl;
     output << std::endl << std::endl;
     output << "# Mixture informations" << std::endl;
     output << "# species / concentration / molar mass" << std::endl;
     for(unsigned int isp = 0; isp < this->n_species(); isp++)
       {
         output << std::setw(10) << _chem_mixture.chemical_species()[isp]->species()
                << std::setw(31) << molar_densities[isp]
                << std::setw(31) << _chem_mixture.M(isp) << std::endl;
       }
     return;
   }
template<typename CoeffType > const Reaction< CoeffType > & Antioch::ReactionSet< CoeffType >::reaction (const unsigned int r) const inline
Returns
a constant reference to reaction r.
Definition at line 173 of file reaction_set.h.
References antioch_assert_less.
Referenced by tester().
   {
     antioch_assert_less(r, this->n_reactions());
     return *_reactions[r];
   }
Friends And Related Function Documentation
template<typename CoeffType> std::ostream& operator<< (std::ostream & os, const ReactionSet< CoeffType > & rset) friend
Formatted print.
Definition at line 125 of file reaction_set.h.
     {
       rset.print(os);
       return os;
     }
Member Data Documentation
template<typename CoeffType> const ChemicalMixture<CoeffType>& Antioch::ReactionSet< CoeffType >::_chem_mixture private
Definition at line 135 of file reaction_set.h.
template<typename CoeffType> const CoeffType Antioch::ReactionSet< CoeffType >::_P0_R private
Scaling for equilibrium constant.
Definition at line 140 of file reaction_set.h.
template<typename CoeffType> std::vector<Reaction<CoeffType>* > Antioch::ReactionSet< CoeffType >::_reactions private
Definition at line 137 of file reaction_set.h.
The documentation for this class was generated from the following files:
src/kinetics/include/antioch/kinetics_evaluator.h
src/kinetics/include/antioch/reaction_set.h