antioch-0.0.7: Antioch::BerthelotRate< CoeffType > Class Template Reference
Antioch::BerthelotRate< CoeffType > Class Template Reference
Berthelot rate equation.
#include <berthelot_rate.h>
Public Member Functions
BerthelotRate (const CoeffType Cf=0., const CoeffType D=0.)
~BerthelotRate ()
void set_Cf (const CoeffType Cf)
void set_D (const CoeffType D)
void scale_D (const CoeffType scale)
CoeffType Cf () const
CoeffType D () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (_D *T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
template<typename StateType >
StateType operator() (const StateType &T) const
template<typename StateType >
StateType derivative (const StateType &T) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &T, StateType &rate, StateType &drate_dT) const
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)*_D) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
Private Attributes
CoeffType _Cf
CoeffType _D
Detailed Description
template<typename CoeffType = double>
class Antioch::BerthelotRate< CoeffType >
Berthelot rate equation.
The Berthelot kinetics model is of the form:
thus
Definition at line 51 of file berthelot_rate.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::BerthelotRate< CoeffType >::BerthelotRate (const CoeffType Cf = 0., const CoeffType D = 0.)
Definition at line 99 of file berthelot_rate.h.
     : KineticsType<CoeffType>(KineticsModel::BERTHELOT),
       _Cf(Cf),
       _D(D)
   {
     return;
   }
template<typename CoeffType > Antioch::BerthelotRate< CoeffType >::~BerthelotRate ()
Definition at line 108 of file berthelot_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::BerthelotRate< CoeffType >::ant_exp (_D * T) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
template<typename CoeffType > CoeffType Antioch::BerthelotRate< CoeffType >::Cf () const inline
Definition at line 150 of file berthelot_rate.h.
References Antioch::BerthelotRate< CoeffType >::_Cf.
Referenced by Antioch::BerthelotRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType >::compute_rate_and_derivative (const StateType & T, StateType & rate, StateType & drate_dT) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 229 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType > CoeffType Antioch::BerthelotRate< CoeffType >::D () const inline
Definition at line 155 of file berthelot_rate.h.
References Antioch::BerthelotRate< CoeffType >::_D.
Referenced by Antioch::BerthelotRate< CoeffType >::set_D().
   { return _D; }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::derivative (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 175 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by tester(), and vectester().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > const std::string Antioch::BerthelotRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 114 of file berthelot_rate.h.
References Antioch::BerthelotRate< CoeffType >::_Cf, and Antioch::BerthelotRate< CoeffType >::_D.
   {
     std::stringstream os;
     os << _Cf;
     os << "*exp(" << _D << "*T)";
     return os.str();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::operator() (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 121 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > void Antioch::KineticsType< CoeffType >::print (std::ostream & os = std::cout) const inline inherited
Formatted print, by default to std::cout.
Definition at line 98 of file kinetics_type.h.
   {
     os << numeric();
   }
template<typename CoeffType = double> template<typename StateType > Antioch::BerthelotRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > void Antioch::BerthelotRate< CoeffType >::scale_D (const CoeffType scale) inline
Definition at line 142 of file berthelot_rate.h.
References Antioch::BerthelotRate< CoeffType >::_D.
   {
     _D *= scale;
     return;
   }
template<typename CoeffType > void Antioch::BerthelotRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 126 of file berthelot_rate.h.
References Antioch::BerthelotRate< CoeffType >::_Cf, and Antioch::BerthelotRate< CoeffType >::Cf().
   {
     _Cf = Cf;
     return;
   }
template<typename CoeffType > void Antioch::BerthelotRate< CoeffType >::set_D (const CoeffType D) inline
Definition at line 134 of file berthelot_rate.h.
References Antioch::BerthelotRate< CoeffType >::_D, and Antioch::BerthelotRate< CoeffType >::D().
   {
     _D = D;
     return;
   }
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::BerthelotRate< CoeffType >::_Cf private
Definition at line 56 of file berthelot_rate.h.
Referenced by Antioch::BerthelotRate< CoeffType >::Cf(), Antioch::BerthelotRate< CoeffType >::numeric(), and Antioch::BerthelotRate< CoeffType >::set_Cf().
template<typename CoeffType = double> CoeffType Antioch::BerthelotRate< CoeffType >::_D private
Definition at line 57 of file berthelot_rate.h.
Referenced by Antioch::BerthelotRate< CoeffType >::D(), Antioch::BerthelotRate< CoeffType >::numeric(), Antioch::BerthelotRate< CoeffType >::scale_D(), and Antioch::BerthelotRate< CoeffType >::set_D().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::BerthelotRate< CoeffType >::const)
Definition at line 92 of file berthelot_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::BerthelotRate< CoeffType >::rate)
Definition at line 92 of file berthelot_rate.h.
template<typename CoeffType = double> _Cf(* Antioch::BerthelotRate< CoeffType >::this)(T)*_D)template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 88 of file berthelot_rate.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/berthelot_rate.h