antioch-0.0.7: Antioch::ChemicalMixture< CoeffType > Class Template Reference
Antioch::ChemicalMixture< CoeffType > Class Template Reference
Class storing chemical mixture properties.
#include <chemical_mixture.h>
Public Member Functions
ChemicalMixture (const std::vector< std::string > &species_list)
~ChemicalMixture ()
unsigned int n_species () const
Returns the number of species in this mixture.
void add_species (const unsigned int index, const std::string &name, CoeffType mol_wght, CoeffType h_form, CoeffType n_tr_dofs, int charge)
void add_species_vibrational_data (const unsigned int index, const CoeffType theta_v, const unsigned int ndg_v)
void add_species_electronic_data (const unsigned int index, const CoeffType theta_e, const unsigned int ndg_e)
const std::vector
< ChemicalSpecies< CoeffType > * > & chemical_species () const
const std::vector< Species > & species_list () const
const std::map< Species,
unsigned int > & species_list_map () const
const std::map< std::string,
unsigned int > & active_species_name_map () const
const std::map< std::string,
Species > & species_name_map () const
const std::map< Species,
std::string > & species_inverse_name_map () const
CoeffType R (const unsigned int s) const
Gas constant for species s in [J/kg-K].
template<typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
typename Antioch::value_type
< VectorStateType >::type >
::type R (const VectorStateType &mass_fractions) const
Gas constant for mixture in [J/kg-K].
CoeffType M (const unsigned int s) const
Molecular weight (molar mass) for species s in [g/mol] or [kg/kmol].
template<typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
typename Antioch::value_type
< VectorStateType >::type >
::type M (const VectorStateType &mass_fractions) const
Molecular weight (molar mass) for mixture in [g/mol] or [kg/kmol].
Public Attributes
template<typename StateType >
X(const unsigned int species,
const StateType &M, const
StateType &mass_fraction)
const template< typename
VectorStateType > void X(typename
Antioch molar_density (const unsigned int species, const StateType &rho, const StateType &mass_fraction) const template< typename StateType
Species mole fraction.
X(const unsigned int species,
const StateType &M, const
StateType &mass_fraction)
const template< typename
VectorStateType > void X(typename
Antioch VectorStateType void molar_densities (const StateType &rho, const VectorStateType &mass_fractions, VectorStateType &molar_densities) const
Protected Member Functions
void init_species_name_map ()
void build_inverse_name_map ()
void read_species_data ()
void read_species_data (std::istream &in)
Protected Attributes
std::vector< Species > _species_list
std::map< Species, unsigned int > _species_list_map
std::map< std::string,
unsigned int > _active_species_name_map
std::vector< ChemicalSpecies
< CoeffType > * > _chemical_species
std::map< std::string, Species > _species_name_map
std::map< Species, std::string > _species_inv_name_map
Private Member Functions
ChemicalMixture ()
Detailed Description
template<typename CoeffType = double>
class Antioch::ChemicalMixture< CoeffType >
Class storing chemical mixture properties.
This class manages the list of ChemicalSpecies for a requested set of species from input.
Todo:
This should probably be a singleton class, but being lazy for now.
Definition at line 55 of file chemical_mixture.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::ChemicalMixture< CoeffType >::ChemicalMixture (const std::vector< std::string > & species_list) inline
Definition at line 267 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_active_species_name_map, Antioch::ChemicalMixture< CoeffType >::_species_list, Antioch::ChemicalMixture< CoeffType >::_species_list_map, Antioch::ChemicalMixture< CoeffType >::_species_name_map, antioch_error, Antioch::ChemicalMixture< CoeffType >::build_inverse_name_map(), Antioch::ChemicalMixture< CoeffType >::init_species_name_map(), Antioch::read_species_data_ascii_default(), Antioch::read_species_electronic_data_ascii_default(), and Antioch::read_species_vibrational_data_ascii_default().
     : _chemical_species( species_list.size(), NULL )
   {
     // Build up name map for all possible species
     this->init_species_name_map();
     // Build up inverse name map
     this->build_inverse_name_map();
     // Populate species list for requested species
     _species_list.reserve( species_list.size() );
     for( unsigned int s = 0; s < species_list.size(); s++ )
       {
         if( _species_name_map.find( species_list[s] ) == _species_name_map.end() )
           {
             std::cerr << "Error in ChemicalMixture: Unknown species " << species_list[s] << std::endl;
             antioch_error();
           }
         _species_list.push_back( _species_name_map.find( species_list[s] )->second );
         _species_list_map.insert( std::make_pair( _species_name_map.find( species_list[s] )->second, s ) );
         _active_species_name_map.insert( std::make_pair( species_list[s], s ) );
       }
     // Now read in chemical properties for the requested species and stash
     read_species_data_ascii_default(*this);
     //... and any vibrational data
     read_species_vibrational_data_ascii_default(*this);
     //... and any electronic data
     read_species_electronic_data_ascii_default(*this);
   }
template<typename CoeffType > Antioch::ChemicalMixture< CoeffType >::~ChemicalMixture () inline
Definition at line 304 of file chemical_mixture.h.
   {
     // Clean up all the ChemicalSpecies we stored
     for( typename std::vector<ChemicalSpecies<CoeffType>* >::iterator it = _chemical_species.begin();
          it < _chemical_species.end(); ++it )
       {
         delete (*it);
       }
     return;
   }
template<typename CoeffType = double> Antioch::ChemicalMixture< CoeffType >::ChemicalMixture () private
Member Function Documentation
template<typename CoeffType > const std::map< std::string, unsigned int > & Antioch::ChemicalMixture< CoeffType >::active_species_name_map () const inline
Definition at line 204 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_active_species_name_map.
Referenced by Antioch::read_blottner_data_ascii(), Antioch::read_cea_mixture_data_ascii(), Antioch::read_cea_thermo_data_ascii(), Antioch::read_reaction_set_data_xml(), Antioch::read_species_electronic_data_ascii(), Antioch::read_species_vibrational_data_ascii(), and Antioch::read_sutherland_data_ascii().
   {
     return _active_species_name_map;
   }
template<typename CoeffType > void Antioch::ChemicalMixture< CoeffType >::add_species (const unsigned int index, const std::string & name, CoeffType mol_wght, CoeffType h_form, CoeffType n_tr_dofs, int charge) inline
Definition at line 387 of file chemical_mixture.h.
Referenced by Antioch::read_species_data_ascii().
   {
     _chemical_species[index] =
       new ChemicalSpecies<CoeffType>(name, mol_wght, h_form, n_tr_dofs, charge);
     return;
   }
template<typename CoeffType > void Antioch::ChemicalMixture< CoeffType >::add_species_electronic_data (const unsigned int index, const CoeffType theta_e, const unsigned int ndg_e) inline
Definition at line 410 of file chemical_mixture.h.
Referenced by Antioch::read_species_electronic_data_ascii().
   {
     (_chemical_species[index])->add_electronic_data(theta_e, ndg_e);
   }
template<typename CoeffType > void Antioch::ChemicalMixture< CoeffType >::add_species_vibrational_data (const unsigned int index, const CoeffType theta_v, const unsigned int ndg_v) inline
Definition at line 401 of file chemical_mixture.h.
Referenced by Antioch::read_species_vibrational_data_ascii().
   {
     (_chemical_species[index])->add_vibrational_data(theta_v, ndg_v);
   }
template<typename CoeffType > void Antioch::ChemicalMixture< CoeffType >::build_inverse_name_map () inline protected
Definition at line 488 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
   {
     for( std::map<std::string,Species>::const_iterator it = _species_name_map.begin();
          it != _species_name_map.end(); ++it )
       {
         _species_inv_name_map.insert( std::make_pair( it->second, it->first ) );
       }
     return;
   }
template<typename CoeffType > const std::vector< ChemicalSpecies< CoeffType > * > & Antioch::ChemicalMixture< CoeffType >::chemical_species () const inline
Definition at line 211 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_chemical_species.
Referenced by Antioch::read_species_electronic_data_ascii(), Antioch::read_species_vibrational_data_ascii(), tester(), tester_N2N(), and vectester().
   {
     return _chemical_species;
   }
template<typename CoeffType > void Antioch::ChemicalMixture< CoeffType >::init_species_name_map () inline protected
Definition at line 419 of file chemical_mixture.h.
References Antioch::Air, Antioch::Ar, Antioch::Arp, Antioch::C, Antioch::C2, Antioch::C2H, Antioch::C2H2, Antioch::C3, Antioch::CF, Antioch::CF2, Antioch::CF3, Antioch::CF4, Antioch::CH, Antioch::CH2, Antioch::CH3, Antioch::CH4, Antioch::Cl, Antioch::Cl2, Antioch::CN, Antioch::CNp, Antioch::CO, Antioch::CO2, Antioch::COp, Antioch::Cp, Antioch::CPAir, Antioch::CPN2, Antioch::e, Antioch::F, Antioch::F2, Antioch::H, Antioch::H2, Antioch::H2O, Antioch::H2O2, Antioch::H2p, Antioch::HCl, Antioch::HCN, Antioch::He, Antioch::Hep, Antioch::HO2, Antioch::Hp, Antioch::N, Antioch::N2, Antioch::N2p, Antioch::NCO, Antioch::Ne, Antioch::NH, Antioch::NH2, Antioch::NH3, Antioch::NHp, Antioch::NO, Antioch::NO2, Antioch::NOp, Antioch::Np, Antioch::O, Antioch::O2, Antioch::O2p, Antioch::OH, Antioch::Op, Antioch::Si, and Antioch::SiO.
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
   {
     _species_name_map["Air"  ] = Air;
     _species_name_map["CPAir"] = CPAir;
     _species_name_map["Ar"   ] = Ar;
     _species_name_map["Ar+"  ] = Arp;
     _species_name_map["C"    ] = C;
     _species_name_map["C+"   ] = Cp;
     _species_name_map["C2"   ] = C2;
     _species_name_map["C2H"  ] = C2H;
     _species_name_map["C2H2" ] = C2H2;
     _species_name_map["C3"   ] = C3;
     _species_name_map["CF"   ] = CF;
     _species_name_map["CF2"  ] = CF2;
     _species_name_map["CF3"  ] = CF3;
     _species_name_map["CF4"  ] = CF4;
     _species_name_map["CH"   ] = CH;
     _species_name_map["CH2"  ] = CH2;
     _species_name_map["CH3"  ] = CH3;
     _species_name_map["CH4"  ] = CH4;
     _species_name_map["Cl"   ] = Cl;
     _species_name_map["Cl2"  ] = Cl2;
     _species_name_map["CN"   ] = CN;
     _species_name_map["CN+"  ] = CNp;
     _species_name_map["CO"   ] = CO;
     _species_name_map["CO+"  ] = COp;
     _species_name_map["CO2"  ] = CO2;
     _species_name_map["F"    ] = F;
     _species_name_map["F2"   ] = F2;
     _species_name_map["H"    ] = H;
     _species_name_map["H+"   ] = Hp;
     _species_name_map["H2"   ] = H2;
     _species_name_map["H2+"  ] = H2p;
     _species_name_map["H2O"  ] = H2O;
     _species_name_map["H2O2" ] = H2O2;
     _species_name_map["HCl"  ] = HCl;
     _species_name_map["HCN"  ] = HCN;
     _species_name_map["He"   ] = He;
     _species_name_map["He+"  ] = Hep;
     _species_name_map["HO2"  ] = HO2;
     _species_name_map["N"    ] = N;
     _species_name_map["N+"   ] = Np;
     _species_name_map["N2"   ] = N2;
     _species_name_map["CPN2" ] = CPN2;
     _species_name_map["N2+"  ] = N2p;
     _species_name_map["Ne"   ] = Ne;
     _species_name_map["NCO"  ] = NCO;
     _species_name_map["NH"   ] = NH;
     _species_name_map["NH+"  ] = NHp;
     _species_name_map["NH2"  ] = NH2;
     _species_name_map["NH3"  ] = NH3;
     _species_name_map["NO"   ] = NO;
     _species_name_map["NO+"  ] = NOp;
     _species_name_map["NO2"  ] = NO2;
     _species_name_map["O"    ] = O;
     _species_name_map["O+"   ] = Op;
     _species_name_map["O2"   ] = O2;
     _species_name_map["O2+"  ] = O2p;
     _species_name_map["OH"   ] = OH;
     _species_name_map["Si"   ] = Si;
     _species_name_map["SiO"  ] = SiO;
     _species_name_map["e"    ] = e;
     return;
   }
template<typename CoeffType > CoeffType Antioch::ChemicalMixture< CoeffType >::M (const unsigned int s) const inline
Molecular weight (molar mass) for species s in [g/mol] or [kg/kmol].
Definition at line 239 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_chemical_species.
Referenced by tester(), vectester(), and Antioch::WilkeMixture< CoeffType >::WilkeMixture().
   {
     return (_chemical_species[s])->molar_mass();
   }
template<typename CoeffType > template<typename VectorStateType > enable_if_c< has_size< VectorStateType >::value, typename Antioch::value_type< VectorStateType >::type >::type Antioch::ChemicalMixture< CoeffType >::M (const VectorStateType & mass_fractions) const inline
Molecular weight (molar mass) for mixture in [g/mol] or [kg/kmol].
where is the mass fraction of species and is the molecular weight (molar mass) of species
Definition at line 347 of file chemical_mixture.h.
References antioch_assert_equal_to.
   {
     antioch_assert_equal_to( mass_fractions.size(), _chemical_species.size() );
     typename Antioch::value_type<VectorStateType>::type
       M = mass_fractions[0]/this->M(0);
     for( unsigned int s = 1; s < mass_fractions.size(); s++ )
       {
         M += mass_fractions[s]/(this->M(s));
       }
     return CoeffType(1)/M;
   }
template<typename CoeffType > unsigned int Antioch::ChemicalMixture< CoeffType >::n_species () const inline
Returns the number of species in this mixture.
Definition at line 183 of file chemical_mixture.h.
Referenced by Antioch::read_reaction_set_data_xml(), and Antioch::WilkeMixture< CoeffType >::WilkeMixture().
   {
     return _species_list.size();
   }
template<typename CoeffType > CoeffType Antioch::ChemicalMixture< CoeffType >::R (const unsigned int s) const inline
Gas constant for species s in [J/kg-K].
Definition at line 232 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_chemical_species.
Referenced by tester(), tester_N2N(), and vectester().
   {
     return (_chemical_species[s])->gas_constant();
   }
template<typename CoeffType > template<typename VectorStateType > enable_if_c< has_size< VectorStateType >::value, typename Antioch::value_type< VectorStateType >::type >::type Antioch::ChemicalMixture< CoeffType >::R (const VectorStateType & mass_fractions) const inline
Gas constant for mixture in [J/kg-K].
Definition at line 324 of file chemical_mixture.h.
References antioch_assert_equal_to, and antioch_assert_greater.
   {
     antioch_assert_equal_to( mass_fractions.size(), _chemical_species.size() );
     antioch_assert_greater( mass_fractions.size(), 0);
     typename Antioch::value_type<VectorStateType>::type
       R = mass_fractions[0]*this->R(0);
     for( unsigned int s = 1; s < mass_fractions.size(); s++ )
       {
         R += mass_fractions[s]*this->R(s);
       }
     return R;
   }
template<typename CoeffType = double> void Antioch::ChemicalMixture< CoeffType >::read_species_data () protected
template<typename CoeffType = double> void Antioch::ChemicalMixture< CoeffType >::read_species_data (std::istream & in) protected
template<typename CoeffType > const std::map< Species, std::string > & Antioch::ChemicalMixture< CoeffType >::species_inverse_name_map () const inline
Definition at line 225 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_species_inv_name_map.
Referenced by tester(), and vectester().
   {
     return _species_inv_name_map;
   }
template<typename CoeffType > const std::vector< Species > & Antioch::ChemicalMixture< CoeffType >::species_list () const inline
Definition at line 190 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_species_list.
Referenced by Antioch::read_species_data_ascii(), tester(), and vectester().
   {
     return _species_list;
   }
template<typename CoeffType > const std::map< Species, unsigned int > & Antioch::ChemicalMixture< CoeffType >::species_list_map () const inline
Definition at line 197 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_species_list_map.
   {
     return _species_list_map;
   }
template<typename CoeffType > const std::map< std::string, Species > & Antioch::ChemicalMixture< CoeffType >::species_name_map () const inline
Definition at line 218 of file chemical_mixture.h.
References Antioch::ChemicalMixture< CoeffType >::_species_name_map.
Referenced by Antioch::read_species_data_ascii(), Antioch::read_species_electronic_data_ascii(), Antioch::read_species_vibrational_data_ascii(), tester(), and vectester().
   {
     return _species_name_map;
   }
Member Data Documentation
template<typename CoeffType = double> std::map<std::string,unsigned int> Antioch::ChemicalMixture< CoeffType >::_active_species_name_map protected
Definition at line 169 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), and Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
template<typename CoeffType = double> std::vector<ChemicalSpecies<CoeffType>*> Antioch::ChemicalMixture< CoeffType >::_chemical_species protected
Definition at line 170 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::chemical_species(), Antioch::ChemicalMixture< CoeffType >::M(), and Antioch::ChemicalMixture< CoeffType >::R().
template<typename CoeffType = double> std::map<Species,std::string> Antioch::ChemicalMixture< CoeffType >::_species_inv_name_map protected
Definition at line 172 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::species_inverse_name_map().
template<typename CoeffType = double> std::vector<Species> Antioch::ChemicalMixture< CoeffType >::_species_list protected
Definition at line 167 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture(), and Antioch::ChemicalMixture< CoeffType >::species_list().
template<typename CoeffType = double> std::map<Species,unsigned int> Antioch::ChemicalMixture< CoeffType >::_species_list_map protected
Definition at line 168 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture(), and Antioch::ChemicalMixture< CoeffType >::species_list_map().
template<typename CoeffType = double> std::map<std::string,Species> Antioch::ChemicalMixture< CoeffType >::_species_name_map protected
Definition at line 171 of file chemical_mixture.h.
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
template<typename CoeffType = double> void Antioch::ChemicalMixture< CoeffType >::molar_densities inline
Definition at line 156 of file chemical_mixture.h.
Referenced by tester(), tester_N2N(), and vectester().
template<typename CoeffType = double> template<typename StateType > X (const unsigned int species, const StateType& M, const StateType& mass_fraction) const template<typename VectorStateType> void X(typename Antioch Antioch::ChemicalMixture< CoeffType >::molar_density(const unsigned int species, const StateType &rho, const StateType &mass_fraction) const template< typename StateType
Species mole fraction.
Given mixture molar mass M and mass fraction for species, compute species mole fraction using the relationship All species mole fractions
The output argument mole_fractions should already be properly sized to hold the output.Species molar density
Given total density rho and mass fraction for species, compute species moles per unit volumeSpecies molar densities
Given total density rho and mass fractions for all species, compute moles per unit volume for all species
Definition at line 145 of file chemical_mixture.h.
The documentation for this class was generated from the following file:
src/core/include/antioch/chemical_mixture.h