antioch-0.0.7: Antioch::ArrheniusRate< CoeffType > Class Template Reference
Antioch::ArrheniusRate< CoeffType > Class Template Reference
Arrhenius rate equation.
#include <arrhenius_rate.h>
Public Member Functions
ArrheniusRate (const CoeffType Cf=0., const CoeffType Ea=0., const CoeffType rscale=Constants::R_universal< CoeffType >()/1000.)
~ArrheniusRate ()
void set_Cf (const CoeffType Cf)
void set_Ea (const CoeffType Ea)
void set_rscale (const CoeffType rscale)
CoeffType Cf () const
CoeffType Ea () const
CoeffType rscale () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (-_Ea/T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
template<typename StateType >
StateType operator() (const StateType &T) const
template<typename StateType >
StateType derivative (const StateType &T) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &T, StateType &rate, StateType &drate_dT) const
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)*(_Ea/(T *T))) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
Private Attributes
CoeffType _Cf
CoeffType _raw_Ea
CoeffType _Ea
CoeffType _rscale
Detailed Description
template<typename CoeffType = double>
class Antioch::ArrheniusRate< CoeffType >
Arrhenius rate equation.
The Arrhenius kinetics model is of the form:
with the ideal gas constant. We have:
Internally, we use the reduced activation energy
Definition at line 59 of file arrhenius_rate.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::ArrheniusRate< CoeffType >::ArrheniusRate (const CoeffType Cf = 0., const CoeffType Ea = 0., const CoeffType rscale = Constants::R_universal<CoeffType>()/1000.)
Definition at line 112 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Ea, Antioch::ArrheniusRate< CoeffType >::_raw_Ea, and Antioch::ArrheniusRate< CoeffType >::_rscale.
     : KineticsType<CoeffType>(KineticsModel::ARRHENIUS),
       _Cf(Cf),
       _raw_Ea(Ea),
       _rscale(rscale)
   {
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > Antioch::ArrheniusRate< CoeffType >::~ArrheniusRate ()
Definition at line 123 of file arrhenius_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::ArrheniusRate< CoeffType >::ant_exp (-_Ea/ T) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
template<typename CoeffType > CoeffType Antioch::ArrheniusRate< CoeffType >::Cf () const inline
Definition at line 166 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Cf.
Referenced by Antioch::ArrheniusRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType >::compute_rate_and_derivative (const StateType & T, StateType & rate, StateType & drate_dT) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 229 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::derivative (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 175 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by tester(), and vectester().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > CoeffType Antioch::ArrheniusRate< CoeffType >::Ea () const inline
Definition at line 171 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Ea.
Referenced by Antioch::ArrheniusRate< CoeffType >::set_Ea().
   { return _Ea; }
template<typename CoeffType > const std::string Antioch::ArrheniusRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 129 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Cf, and Antioch::ArrheniusRate< CoeffType >::_raw_Ea.
   {
     std::stringstream os;
     os << _Cf;
     os << "*exp(-" << _raw_Ea << "/(R*T))";
     return os.str();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::operator() (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 121 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > void Antioch::KineticsType< CoeffType >::print (std::ostream & os = std::cout) const inline inherited
Formatted print, by default to std::cout.
Definition at line 98 of file kinetics_type.h.
   {
     os << numeric();
   }
template<typename CoeffType = double> template<typename StateType > Antioch::ArrheniusRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > CoeffType Antioch::ArrheniusRate< CoeffType >::rscale () const inline
Definition at line 176 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_rscale.
Referenced by Antioch::ArrheniusRate< CoeffType >::set_rscale().
   { return _rscale; }
template<typename CoeffType > void Antioch::ArrheniusRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 140 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Cf, and Antioch::ArrheniusRate< CoeffType >::Cf().
   {
     _Cf = Cf;
     return;
   }
template<typename CoeffType > void Antioch::ArrheniusRate< CoeffType >::set_Ea (const CoeffType Ea) inline
Definition at line 148 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Ea, Antioch::ArrheniusRate< CoeffType >::_raw_Ea, Antioch::ArrheniusRate< CoeffType >::_rscale, and Antioch::ArrheniusRate< CoeffType >::Ea().
   {
     _raw_Ea = Ea;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::ArrheniusRate< CoeffType >::set_rscale (const CoeffType rscale) inline
Definition at line 157 of file arrhenius_rate.h.
References Antioch::ArrheniusRate< CoeffType >::_Ea, Antioch::ArrheniusRate< CoeffType >::_raw_Ea, Antioch::ArrheniusRate< CoeffType >::_rscale, and Antioch::ArrheniusRate< CoeffType >::rscale().
   {
     _rscale = rscale;
     _Ea = _raw_Ea / _rscale;
     return;
   }
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::ArrheniusRate< CoeffType >::_Cf private
Definition at line 65 of file arrhenius_rate.h.
Referenced by Antioch::ArrheniusRate< CoeffType >::Cf(), Antioch::ArrheniusRate< CoeffType >::numeric(), and Antioch::ArrheniusRate< CoeffType >::set_Cf().
template<typename CoeffType = double> CoeffType Antioch::ArrheniusRate< CoeffType >::_Ea private
Definition at line 67 of file arrhenius_rate.h.
Referenced by Antioch::ArrheniusRate< CoeffType >::ArrheniusRate(), Antioch::ArrheniusRate< CoeffType >::Ea(), Antioch::ArrheniusRate< CoeffType >::set_Ea(), and Antioch::ArrheniusRate< CoeffType >::set_rscale().
template<typename CoeffType = double> CoeffType Antioch::ArrheniusRate< CoeffType >::_raw_Ea private
Definition at line 66 of file arrhenius_rate.h.
Referenced by Antioch::ArrheniusRate< CoeffType >::ArrheniusRate(), Antioch::ArrheniusRate< CoeffType >::numeric(), Antioch::ArrheniusRate< CoeffType >::set_Ea(), and Antioch::ArrheniusRate< CoeffType >::set_rscale().
template<typename CoeffType = double> CoeffType Antioch::ArrheniusRate< CoeffType >::_rscale private
Definition at line 68 of file arrhenius_rate.h.
Referenced by Antioch::ArrheniusRate< CoeffType >::ArrheniusRate(), Antioch::ArrheniusRate< CoeffType >::rscale(), Antioch::ArrheniusRate< CoeffType >::set_Ea(), and Antioch::ArrheniusRate< CoeffType >::set_rscale().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::ArrheniusRate< CoeffType >::const)
Definition at line 103 of file arrhenius_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::ArrheniusRate< CoeffType >::rate)
Definition at line 103 of file arrhenius_rate.h.
template<typename CoeffType = double> _Cf(* Antioch::ArrheniusRate< CoeffType >::this)(T)*(_Ea/(T *T)))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 99 of file arrhenius_rate.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/arrhenius_rate.h