antioch-0.0.7: Antioch::BerthelotHercourtEssenRate< CoeffType > Class Template Reference
Antioch::BerthelotHercourtEssenRate< CoeffType > Class Template Reference
Berthelot Hercourt-Essen rate equation.
#include <berthelothercourtessen_rate.h>
Public Member Functions
BerthelotHercourtEssenRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType D=0., const CoeffType Tref=1.)
~BerthelotHercourtEssenRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_D (const CoeffType D)
void set_Tref (const CoeffType Tref)
CoeffType Cf () const
CoeffType eta () const
CoeffType D () const
CoeffType Tref () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_pow (T, _eta)*ant_exp(_D *T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
template<typename StateType >
StateType operator() (const StateType &T) const
template<typename StateType >
StateType derivative (const StateType &T) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &T, StateType &rate, StateType &drate_dT) const
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)*(_eta/T+_D)) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _D
CoeffType _Tref
Detailed Description
template<typename CoeffType = double>
class Antioch::BerthelotHercourtEssenRate< CoeffType >
Berthelot Hercourt-Essen rate equation.
The Berthelot Hercourt Essen kinetics model is of the form:
thus
Internally, we use the reduced temperature .
Definition at line 53 of file berthelothercourtessen_rate.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::BerthelotHercourtEssenRate< CoeffType >::BerthelotHercourtEssenRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType D = 0., const CoeffType Tref = 1.)
Definition at line 110 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), and std::pow().
     : KineticsType<CoeffType>(KineticsModel::BHE),
       _raw_Cf(Cf),
       _eta(eta),
       _D(D),
       _Tref(Tref)
   {
     using std::pow;
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::BerthelotHercourtEssenRate< CoeffType >::~BerthelotHercourtEssenRate ()
Definition at line 123 of file berthelothercourtessen_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::BerthelotHercourtEssenRate< CoeffType >::ant_pow (T , _eta) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf () const inline
Definition at line 178 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_Cf.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf () inline private
Definition at line 210 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_Cf, Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta, Antioch::BerthelotHercourtEssenRate< CoeffType >::_raw_Cf, Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref, and std::pow().
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::BerthelotHercourtEssenRate(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref().
   {
     _Cf = _raw_Cf * pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
template<typename CoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType >::compute_rate_and_derivative (const StateType & T, StateType & rate, StateType & drate_dT) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 229 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::D () const inline
Definition at line 188 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_D.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D().
   { return _D; }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::derivative (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 175 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by tester(), and vectester().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::eta () const inline
Definition at line 183 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > const std::string Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 129 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_D, Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta, Antioch::BerthelotHercourtEssenRate< CoeffType >::_raw_Cf, and Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref.
   {
     std::stringstream os;
     os << _raw_Cf;
     if (_eta != 0.) os << "*(T/" << _Tref << ")^" << _eta;
     os << "*exp(" << _D << "*T)";
     return os.str();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::operator() (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 121 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > void Antioch::KineticsType< CoeffType >::print (std::ostream & os = std::cout) const inline inherited
Formatted print, by default to std::cout.
Definition at line 98 of file kinetics_type.h.
   {
     os << numeric();
   }
template<typename CoeffType = double> template<typename StateType > Antioch::BerthelotHercourtEssenRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 142 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_raw_Cf, Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), and std::pow().
   {
     using std::pow;
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D (const CoeffType D) inline
Definition at line 170 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_D, and Antioch::BerthelotHercourtEssenRate< CoeffType >::D().
   {
     _D = D;
     return;
   }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 162 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta, and Antioch::BerthelotHercourtEssenRate< CoeffType >::eta().
   {
     _eta = eta;
     return;
   }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 152 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref, Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), std::pow(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref().
   {
     using std::pow;
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref () const inline
Definition at line 193 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref().
   { return _Tref; }
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_Cf private
Definition at line 59 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_D private
Definition at line 61 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::D(), Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta private
Definition at line 60 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::eta(), Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_raw_Cf private
Definition at line 58 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref private
Definition at line 62 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::BerthelotHercourtEssenRate< CoeffType >::const)
Definition at line 99 of file berthelothercourtessen_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::BerthelotHercourtEssenRate< CoeffType >::rate)
Definition at line 99 of file berthelothercourtessen_rate.h.
template<typename CoeffType = double> _Cf(* Antioch::BerthelotHercourtEssenRate< CoeffType >::this)(T)*(_eta/T+_D))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 95 of file berthelothercourtessen_rate.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/berthelothercourtessen_rate.h