antioch-0.0.7: Antioch::WilkeMixture< CoeffType > Class Template Reference
Antioch::WilkeMixture< CoeffType > Class Template Reference
#include <wilke_mixture.h>
Public Member Functions
WilkeMixture (const ChemicalMixture< CoeffType > &chem_mixture)
~WilkeMixture ()
CoeffType Mr_Ms_to_the_one_fourth (const unsigned int r, const unsigned int s) const
CoeffType denominator (const unsigned int r, const unsigned int s) const
const ChemicalMixture
< CoeffType > & chem_mixture () const
Protected Attributes
const ChemicalMixture
< CoeffType > & _chem_mixture
std::vector< std::vector
< CoeffType > > _Mr_Ms_to_the_one_fourth
Cache for numerator term.
std::vector< std::vector
< CoeffType > > _denom
Cache for denominator term.
Detailed Description
template<class CoeffType = double>
class Antioch::WilkeMixture< CoeffType >
Definition at line 42 of file wilke_mixture.h.
Constructor & Destructor Documentation
template<class CoeffType > Antioch::WilkeMixture< CoeffType >::WilkeMixture (const ChemicalMixture< CoeffType > & chem_mixture)
Definition at line 72 of file wilke_mixture.h.
References Antioch::WilkeMixture< CoeffType >::_denom, Antioch::WilkeMixture< CoeffType >::_Mr_Ms_to_the_one_fourth, Antioch::ChemicalMixture< CoeffType >::M(), Antioch::ChemicalMixture< CoeffType >::n_species(), and std::pow().
     : _chem_mixture(chem_mixture),
       _Mr_Ms_to_the_one_fourth(chem_mixture.n_species()),
       _denom(chem_mixture.n_species())
   {
     using std::pow;
     for( unsigned int r = 0; r < chem_mixture.n_species(); r++ )
       {
         _Mr_Ms_to_the_one_fourth[r].resize(chem_mixture.n_species());
         _denom[r].resize(chem_mixture.n_species());
         for( unsigned int s = 0; s < chem_mixture.n_species(); s++ )
           {
             const CoeffType Mr = chem_mixture.M(r);
             const CoeffType Ms = chem_mixture.M(s);
             _Mr_Ms_to_the_one_fourth[r][s] = pow( Mr/Ms, CoeffType(0.25) );
             _denom[r][s] = std::sqrt(8.0*(1.0+Ms/Mr));
           }
       }
     return;
   }
template<class CoeffType > Antioch::WilkeMixture< CoeffType >::~WilkeMixture ()
Definition at line 98 of file wilke_mixture.h.
   {
     return;
   }
Member Function Documentation
template<class CoeffType > const ChemicalMixture< CoeffType > & Antioch::WilkeMixture< CoeffType >::chem_mixture () const inline
Definition at line 123 of file wilke_mixture.h.
   {
     return _chem_mixture;
   }
template<class CoeffType > CoeffType Antioch::WilkeMixture< CoeffType >::denominator (const unsigned int r, const unsigned int s) const inline
Definition at line 115 of file wilke_mixture.h.
   {
     return _denom[r][s];
   }
template<class CoeffType > CoeffType Antioch::WilkeMixture< CoeffType >::Mr_Ms_to_the_one_fourth (const unsigned int r, const unsigned int s) const inline
Definition at line 106 of file wilke_mixture.h.
   {
     return _Mr_Ms_to_the_one_fourth[r][s];
   }
Member Data Documentation
template<class CoeffType = double> const ChemicalMixture<CoeffType>& Antioch::WilkeMixture< CoeffType >::_chem_mixture protected
Definition at line 59 of file wilke_mixture.h.
template<class CoeffType = double> std::vector<std::vector<CoeffType> > Antioch::WilkeMixture< CoeffType >::_denom protected
Cache for denominator term.
Todo:
We should use a more efficient data structure
Definition at line 67 of file wilke_mixture.h.
Referenced by Antioch::WilkeMixture< CoeffType >::WilkeMixture().
template<class CoeffType = double> std::vector<std::vector<CoeffType> > Antioch::WilkeMixture< CoeffType >::_Mr_Ms_to_the_one_fourth protected
Cache for numerator term.
Todo:
We should use a more efficient data structure
Definition at line 63 of file wilke_mixture.h.
Referenced by Antioch::WilkeMixture< CoeffType >::WilkeMixture().
The documentation for this class was generated from the following file:
src/transport/include/antioch/wilke_mixture.h