antioch-0.0.7: Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType > Class Template Reference
Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType > Class Template Reference
#include <wilke_evaluator.h>
Public Member Functions
WilkeEvaluator (const WilkeMixture< CoeffType > &mixture, const Viscosity &viscosity, const ThermalConductivity &conductivity)
~WilkeEvaluator ()
template<typename StateType , typename VectorStateType >
StateType mu (const StateType &T, const VectorStateType &mass_fractions) const
template<typename StateType , typename VectorStateType >
StateType k (const StateType &T, const VectorStateType &mass_fractions) const
template<typename StateType , typename VectorStateType >
void mu_and_k (const StateType &T, const VectorStateType &mass_fractions, StateType &mu, StateType &k) const
template<typename StateType , typename VectorStateType >
void compute_mu_chi (const StateType &T, const VectorStateType &mass_fractions, VectorStateType &mu, VectorStateType &chi) const
Helper function to reduce code duplication.
template<typename VectorStateType >
Antioch::value_type
< VectorStateType >::type compute_phi (const VectorStateType &mu, const VectorStateType &chi, const unsigned int s) const
Helper function to reduce code duplication.
Protected Attributes
const WilkeMixture< CoeffType > & _mixture
const Viscosity & _viscosity
const ThermalConductivity & _conductivity
Private Member Functions
WilkeEvaluator ()
Detailed Description
template<class Viscosity, class ThermalConductivity, class CoeffType = double>
class Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >
Definition at line 42 of file wilke_evaluator.h.
Constructor & Destructor Documentation
template<class Viscosity , class ThermalConductivity , class CoeffType > Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::WilkeEvaluator (const WilkeMixture< CoeffType > & mixture, const Viscosity & viscosity, const ThermalConductivity & conductivity)
Definition at line 98 of file wilke_evaluator.h.
     : _mixture(mixture),
       _viscosity(viscosity),
       _conductivity(conductivity)
   {
     return;
   }
template<class Viscosity , class ThermalConductivity , class CoeffType > Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::~WilkeEvaluator ()
Definition at line 109 of file wilke_evaluator.h.
   {
     return;
   }
template<class Viscosity, class ThermalConductivity, class CoeffType = double> Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::WilkeEvaluator () private
Member Function Documentation
template<class Viscosity , class ThermalConductivity , class CoeffType > template<typename StateType , typename VectorStateType > void Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::compute_mu_chi (const StateType & T, const VectorStateType & mass_fractions, VectorStateType & mu, VectorStateType & chi) const
Helper function to reduce code duplication.
Populates species viscosities and the intermediate variable needed for Wilke's mixing rule.
Definition at line 198 of file wilke_evaluator.h.
   {
     const StateType M = _viscosity.chemical_mixture().M(mass_fractions);
     // Precompute needed quantities
     // chi_s = w_s*M/M_s
     for( unsigned int s = 0; s < _mixture.chem_mixture().n_species(); s++ )
       {
         mu[s] = _viscosity(s,T);
         chi[s] = mass_fractions[s]*M/_viscosity.chemical_mixture().M(s);
       }
     return;
   }
template<class Viscosity , class ThermalConductivity , class CoeffType > template<typename VectorStateType > Antioch::value_type< VectorStateType >::type Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::compute_phi (const VectorStateType & mu, const VectorStateType & chi, const unsigned int s) const
Helper function to reduce code duplication.
Computes the intermediate variable needed for Wilke's mixing rule.
Definition at line 220 of file wilke_evaluator.h.
Referenced by tester().
   {
     using std::sqrt;
     typedef typename
       Antioch::value_type<VectorStateType>::type StateType;
     /* We initialize to the first iterate and loop starting from 1
        since some StateTypes have a hard time initializing from
        a constant. */
     // phi_s = sum_r (chi_r*(1+sqrt(mu_s/mu_r)*(Mr/Ms)^(1/4))^2)/sqrt(8*(1+Ms/Mr))
     const StateType dummy = 1 + sqrt(mu[s]/mu[0])*_mixture.Mr_Ms_to_the_one_fourth(0,s);
     StateType phi_s = chi[0]*dummy*dummy/_mixture.denominator(0,s);
     for(unsigned int r = 1; r < _mixture.chem_mixture().n_species(); r++ )
       {
         const StateType numerator = 1 + sqrt(mu[s]/mu[r])*_mixture.Mr_Ms_to_the_one_fourth(r,s);
         phi_s += chi[r]*numerator*numerator/_mixture.denominator(r,s);
       }
     return phi_s;
   }
template<class Viscosity , class ThermalConductivity , class CoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::k (const StateType & T, const VectorStateType & mass_fractions) const
Definition at line 138 of file wilke_evaluator.h.
References antioch_assert_equal_to, and Antioch::zero_clone().
Referenced by tester().
   {
     antioch_assert_equal_to(mass_fractions.size(), _mixture.chem_mixture().n_species());
     StateType k_mix = zero_clone(T);
     VectorStateType mu  = zero_clone(mass_fractions);
     VectorStateType chi = zero_clone(mass_fractions);
     this->compute_mu_chi( T, mass_fractions, mu, chi );
     for( unsigned int s = 0; s < _mixture.chem_mixture().n_species(); s++ )
       {
         StateType phi_s = this->compute_phi( mu, chi, s );
         StateType k_s = _conductivity.trans( s, mu[s] )
                       + _conductivity.rot( s, mu[s] )
                       + _conductivity.vib( s, mu[s], T )
                       + _conductivity.elec( s, mu[s], T );
         k_mix += k_s*chi[s]/phi_s;
       }
     return k_mix;
   }
template<class Viscosity , class ThermalConductivity , class CoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::mu (const StateType & T, const VectorStateType & mass_fractions) const
Definition at line 116 of file wilke_evaluator.h.
References Antioch::zero_clone().
Referenced by tester().
   {
     StateType mu_mix = zero_clone(T);
     VectorStateType mu  = zero_clone(mass_fractions);
     VectorStateType chi = zero_clone(mass_fractions);
     this->compute_mu_chi( T, mass_fractions, mu, chi );
     for( unsigned int s = 0; s < _mixture.chem_mixture().n_species(); s++ )
       {
         StateType phi_s = this->compute_phi( mu, chi, s );
         mu_mix += mu[s]*chi[s]/phi_s;
       }
     return mu_mix;
   }
template<class Viscosity , class ThermalConductivity , class CoeffType > template<typename StateType , typename VectorStateType > void Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::mu_and_k (const StateType & T, const VectorStateType & mass_fractions, StateType & mu, StateType & k) const
Definition at line 167 of file wilke_evaluator.h.
References Antioch::zero_clone().
Referenced by tester().
   {
     mu_mix = zero_clone(T);
     k_mix  = zero_clone(T);
     VectorStateType mu  = zero_clone(mass_fractions);
     VectorStateType chi = zero_clone(mass_fractions);
     this->compute_mu_chi( T, mass_fractions, mu, chi );
     for( unsigned int s = 0; s < _mixture.chem_mixture().n_species(); s++ )
       {
         StateType phi_s = this->compute_phi( mu, chi, s );
         StateType k_s = _conductivity.trans( s, mu[s] )
                       + _conductivity.rot( s, mu[s] )
                       + _conductivity.vib( s, mu[s], T )
                       + _conductivity.elec( s, mu[s], T );
         mu_mix += mu[s]*chi[s]/phi_s;
         k_mix += k_s*chi[s]/phi_s;
       }
     return;
   }
Member Data Documentation
template<class Viscosity, class ThermalConductivity, class CoeffType = double> const ThermalConductivity& Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::_conductivity protected
Definition at line 89 of file wilke_evaluator.h.
template<class Viscosity, class ThermalConductivity, class CoeffType = double> const WilkeMixture<CoeffType>& Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::_mixture protected
Definition at line 85 of file wilke_evaluator.h.
template<class Viscosity, class ThermalConductivity, class CoeffType = double> const Viscosity& Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::_viscosity protected
Definition at line 87 of file wilke_evaluator.h.
The documentation for this class was generated from the following file:
src/transport/include/antioch/wilke_evaluator.h