antioch-0.0.7: tinyxml2::XMLNode Class Reference
tinyxml2::XMLNode Class Reference abstract
#include <tinyxml2.h>
Public Member Functions
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *_value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *_value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
XMLElement * PreviousSiblingElement (const char *_value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
XMLElement * NextSiblingElement (const char *_value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
virtual XMLNode * ShallowClone (XMLDocument *document) const =0
virtual bool ShallowEqual (const XMLNode *compare) const =0
virtual bool Accept (XMLVisitor *visitor) const =0
virtual char * ParseDeep (char *, StrPair *)
Protected Member Functions
XMLNode (XMLDocument *)
virtual ~XMLNode ()
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Protected Attributes
XMLDocument * document
XMLNode * parent
StrPair value
XMLNode * firstChild
XMLNode * lastChild
XMLNode * prev
XMLNode * next
Private Member Functions
void Unlink (XMLNode *child)
Private Attributes
MemPool * memPool
Friends
class XMLDocument
class XMLElement
Detailed Description
XMLNode is a base class for every object that is in the XML Document Object Model (DOM), except XMLAttributes. Nodes have siblings, a parent, and children which can be navigated. A node is always in a XMLDocument. The type of a XMLNode can be queried, and it can be cast to its more defined type.
A XMLDocument allocates memory for all its Nodes. When the XMLDocument gets deleted, all its Nodes will also be deleted.
    A Document can contain:     Element (container or leaf)
                                                Comment (leaf)
                                                Unknown (leaf)
                                                Declaration( leaf )
    An Element can contain:     Element (container or leaf)
                                                Text    (leaf)
                                                Attributes (not on tree)
                                                Comment (leaf)
                                                Unknown (leaf)
Definition at line 448 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLNode::XMLNode (XMLDocument * doc) protected
Definition at line 571 of file tinyxml2.cpp.
                                    :
         document( doc ),
         parent( 0 ),
         firstChild( 0 ), lastChild( 0 ),
         prev( 0 ), next( 0 )
 {
 }
XMLNode::~XMLNode () protected virtual
Definition at line 580 of file tinyxml2.cpp.
References DeleteChildren(), parent, and Unlink().
 {
         DeleteChildren();
         if ( parent ) {
                 parent->Unlink( this );
         }
 }
tinyxml2::XMLNode::XMLNode (const XMLNode &) protected
Member Function Documentation
virtual bool tinyxml2::XMLNode::Accept (XMLVisitor * visitor) const pure virtual
Accept a hierarchical visit of the nodes in the TinyXML DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
    TiXmlPrinter printer;
    tinyxmlDoc.Accept( &printer );
    const char* xmlcstr = printer.CStr();
Implemented in tinyxml2::XMLDocument, tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
void XMLNode::DeleteChild (XMLNode * node)
Delete a child of this node.
Definition at line 628 of file tinyxml2.cpp.
References DELETE_NODE, parent, and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::DeleteNode().
 {
         TIXMLASSERT( node->parent == this );
         DELETE_NODE( node );
 }
void XMLNode::DeleteChildren ()
Delete all the children of this node.
Definition at line 598 of file tinyxml2.cpp.
References DELETE_NODE, firstChild, lastChild, and Unlink().
Referenced by tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::Parse(), tinyxml2::XMLDocument::~XMLDocument(), and ~XMLNode().
 {
         while( firstChild ) {
                 XMLNode* node = firstChild;
                 Unlink( node );
                 DELETE_NODE( node );
         }
         firstChild = lastChild = 0;
 }
const XMLNode* tinyxml2::XMLNode::FirstChild () const inline
Get the first child node, or null if none exists.
Definition at line 496 of file tinyxml2.h.
References firstChild.
Referenced by tinyxml2::XMLElement::Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLHandle::FirstChild(), tinyxml2::XMLConstHandle::FirstChild(), tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), and tinyxml2::XMLElement::QueryUnsignedText().
 { return firstChild; }
XMLNode* tinyxml2::XMLNode::FirstChild () inline
Definition at line 497 of file tinyxml2.h.
References firstChild.
 { return firstChild; }
const XMLElement * XMLNode::FirstChildElement (const char * value = 0) const
Get the first child element, or optionally the first child element with the specified name.
Definition at line 703 of file tinyxml2.cpp.
References firstChild, tinyxml2::XMLElement::Name(), next, tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLElement::ToElement(), and value.
Referenced by tinyxml2::XMLHandle::FirstChildElement(), tinyxml2::XMLConstHandle::FirstChildElement(), Antioch::read_reaction_set_data_xml(), and tinyxml2::XMLDocument::RootElement().
 {
         for( XMLNode* node=firstChild; node; node=node->next ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * _value = 0) inline
Definition at line 502 of file tinyxml2.h.
References FirstChildElement().
Referenced by FirstChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( _value )); }
const XMLDocument* tinyxml2::XMLNode::GetDocument () const inline
Get the XMLDocument that owns this XMLNode.
Definition at line 455 of file tinyxml2.h.
References document.
 { return document; }
XMLDocument* tinyxml2::XMLNode::GetDocument () inline
Get the XMLDocument that owns this XMLNode.
Definition at line 457 of file tinyxml2.h.
References document.
 { return document; }
XMLNode * XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis)
Add a node after the specified child node.
Definition at line 682 of file tinyxml2.cpp.
References InsertEndChild(), next, parent, prev, and TIXMLASSERT.
 {
         TIXMLASSERT( afterThis->parent == this );
         if ( afterThis->parent != this )
                 return 0;
         if ( afterThis->next == 0 ) {
                 // The last node or the only node.
                 return InsertEndChild( addThis );
         }
         addThis->prev = afterThis;
         addThis->next = afterThis->next;
         afterThis->next->prev = addThis;
         afterThis->next = addThis;
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertEndChild (XMLNode * addThis)
Add a child node as the last (right) child.
Definition at line 635 of file tinyxml2.cpp.
References firstChild, lastChild, next, parent, prev, and TIXMLASSERT.
Referenced by InsertAfterChild(), LinkEndChild(), and ParseDeep().
 {
         if ( lastChild ) {
                 TIXMLASSERT( firstChild );
                 TIXMLASSERT( lastChild->next == 0 );
                 lastChild->next = addThis;
                 addThis->prev = lastChild;
                 lastChild = addThis;
                 addThis->next = 0;
         }
         else {
                 TIXMLASSERT( firstChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertFirstChild (XMLNode * addThis)
Add a child node as the first (left) child.
Definition at line 658 of file tinyxml2.cpp.
References firstChild, lastChild, next, parent, prev, and TIXMLASSERT.
 {
         if ( firstChild ) {
                 TIXMLASSERT( lastChild );
                 TIXMLASSERT( firstChild->prev == 0 );
                 firstChild->prev = addThis;
                 addThis->next = firstChild;
                 firstChild = addThis;
                 addThis->prev = 0;
         }
         else {
                 TIXMLASSERT( lastChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
const XMLNode* tinyxml2::XMLNode::LastChild () const inline
Get the last child node, or null if none exists.
Definition at line 505 of file tinyxml2.h.
References lastChild.
Referenced by tinyxml2::XMLHandle::LastChild(), and tinyxml2::XMLConstHandle::LastChild().
 { return lastChild; }
XMLNode* tinyxml2::XMLNode::LastChild () inline
Definition at line 506 of file tinyxml2.h.
References LastChild().
Referenced by LastChild().
 { return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() ); }
const XMLElement * XMLNode::LastChildElement (const char * value = 0) const
Get the last child element or optionally the last child element with the specified name.
Definition at line 717 of file tinyxml2.cpp.
References lastChild, tinyxml2::XMLElement::Name(), prev, tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLElement::ToElement(), and value.
Referenced by tinyxml2::XMLHandle::LastChildElement(), and tinyxml2::XMLConstHandle::LastChildElement().
 {
         for( XMLNode* node=lastChild; node; node=node->prev ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * _value = 0) inline
Definition at line 512 of file tinyxml2.h.
References LastChildElement().
Referenced by LastChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(_value) ); }
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) inline
Definition at line 535 of file tinyxml2.h.
References InsertEndChild().
 { return InsertEndChild( addThis ); }
const XMLNode* tinyxml2::XMLNode::NextSibling () const inline
Get the next (right) sibling node of this node.
Definition at line 523 of file tinyxml2.h.
References next.
Referenced by tinyxml2::XMLElement::Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLHandle::NextSibling(), and tinyxml2::XMLConstHandle::NextSibling().
 { return next; }
XMLNode* tinyxml2::XMLNode::NextSibling () inline
Definition at line 524 of file tinyxml2.h.
References next.
 { return next; }
const XMLElement * XMLNode::NextSiblingElement (const char * value = 0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
Definition at line 731 of file tinyxml2.cpp.
References next, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLHandle::NextSiblingElement(), tinyxml2::XMLConstHandle::NextSiblingElement(), and Antioch::read_reaction_set_data_xml().
 {
         for( XMLNode* element=this->next; element; element = element->next ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * _value = 0) inline
Definition at line 528 of file tinyxml2.h.
References NextSiblingElement().
Referenced by NextSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( _value ) ); }
bool tinyxml2::XMLNode::NoChildren () const inline
Returns true if this node has no children.
Definition at line 493 of file tinyxml2.h.
References firstChild.
 { return !firstChild; }
XMLNode& tinyxml2::XMLNode::operator= (const XMLNode &) protected
const XMLNode* tinyxml2::XMLNode::Parent () const inline
Get the parent of this node on the DOM.
Definition at line 489 of file tinyxml2.h.
References parent.
 { return parent; }
XMLNode* tinyxml2::XMLNode::Parent () inline
Definition at line 490 of file tinyxml2.h.
References parent.
 { return parent; }
char * XMLNode::ParseDeep (char * p, StrPair * parentEnd) virtual
Reimplemented in tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
Definition at line 757 of file tinyxml2.cpp.
References tinyxml2::XMLElement::CLOSING, tinyxml2::XMLElement::ClosingType(), DELETE_NODE, document, tinyxml2::StrPair::Empty(), tinyxml2::XMLDocument::Error(), tinyxml2::StrPair::GetStr(), tinyxml2::XMLDocument::Identify(), InsertEndChild(), tinyxml2::XMLElement::OPEN, ParseDeep(), tinyxml2::XMLDocument::SetError(), tinyxml2::XMLUtil::StringEqual(), ToElement(), Value(), value, tinyxml2::XML_ERROR_MISMATCHED_ELEMENT, and tinyxml2::XML_ERROR_PARSING.
Referenced by tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::Parse(), ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
 {
         // This is a recursive method, but thinking about it "at the current level"
         // it is a pretty simple flat list:
         //              <foo/>
         //              <!-- comment -->
         //
         // With a special case:
         //              <foo>
         //              </foo>
         //              <!-- comment -->
         //
         // Where the closing element (/foo) *must* be the next thing after the opening
         // element, and the names must match. BUT the tricky bit is that the closing
         // element will be read by the child.
         //
         // 'endTag' is the end tag for this node, it is returned by a call to a child.
         // 'parentEnd' is the end tag for the parent, which is filled in and returned.
         while( p && *p ) {
                 XMLNode* node = 0;
                 p = document->Identify( p, &node );
                 if ( p == 0 || node == 0 ) {
                         break;
                 }
                 StrPair endTag;
                 p = node->ParseDeep( p, &endTag );
                 if ( !p ) {
                         DELETE_NODE( node );
                         node = 0;
                         if ( !document->Error() ) {
                                 document->SetError( XML_ERROR_PARSING, 0, 0 );
                         }
                         break;
                 }
                 // We read the end tag. Return it to the parent.
                 if ( node->ToElement() && node->ToElement()->ClosingType() == XMLElement::CLOSING ) {
                         if ( parentEnd ) {
                                 *parentEnd = static_cast<XMLElement*>(node)->value;
                         }
                         DELETE_NODE( node );
                         return p;
                 }
                 // Handle an end tag returned to this level.
                 // And handle a bunch of annoying errors.
                 XMLElement* ele = node->ToElement();
                 if ( ele ) {
                         if ( endTag.Empty() && ele->ClosingType() == XMLElement::OPEN ) {
                                 document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                                 p = 0;
                         }
                         else if ( !endTag.Empty() && ele->ClosingType() != XMLElement::OPEN ) {
                                 document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                                 p = 0;
                         }
                         else if ( !endTag.Empty() ) {
                                 if ( !XMLUtil::StringEqual( endTag.GetStr(), node->Value() )) {
                                         document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                                         p = 0;
                                 }
                         }
                 }
                 if ( p == 0 ) {
                         DELETE_NODE( node );
                         node = 0;
                 }
                 if ( node ) {
                         this->InsertEndChild( node );
                 }
         }
         return 0;
 }
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const inline
Get the previous (left) sibling node of this node.
Definition at line 515 of file tinyxml2.h.
References prev.
Referenced by tinyxml2::XMLHandle::PreviousSibling(), and tinyxml2::XMLConstHandle::PreviousSibling().
 { return prev; }
XMLNode* tinyxml2::XMLNode::PreviousSibling () inline
Definition at line 516 of file tinyxml2.h.
References prev.
 { return prev; }
const XMLElement * XMLNode::PreviousSiblingElement (const char * value = 0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
Definition at line 744 of file tinyxml2.cpp.
References prev, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLHandle::PreviousSiblingElement(), and tinyxml2::XMLConstHandle::PreviousSiblingElement().
 {
         for( XMLNode* element=this->prev; element; element = element->prev ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * _value = 0) inline
Definition at line 520 of file tinyxml2.h.
References PreviousSiblingElement().
Referenced by PreviousSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( _value ) ); }
void XMLNode::SetValue (const char * val, bool staticMem = false)
Set the Value of an XML node.
See Also
Value()
Definition at line 589 of file tinyxml2.cpp.
References tinyxml2::StrPair::SetInternedStr(), tinyxml2::StrPair::SetStr(), and value.
Referenced by tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLDocument::NewUnknown(), and tinyxml2::XMLElement::SetName().
 {
         if ( staticMem )
                 value.SetInternedStr( str );
         else
                 value.SetStr( str );
 }
virtual XMLNode* tinyxml2::XMLNode::ShallowClone (XMLDocument * document) const pure virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implemented in tinyxml2::XMLDocument, tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
virtual bool tinyxml2::XMLNode::ShallowEqual (const XMLNode * compare) const pure virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implemented in tinyxml2::XMLDocument, tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
virtual XMLComment* tinyxml2::XMLNode::ToComment () inline virtual
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 461 of file tinyxml2.h.
Referenced by tinyxml2::XMLComment::ShallowEqual().
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const inline virtual
Reimplemented in tinyxml2::XMLComment.
Definition at line 468 of file tinyxml2.h.
 { return 0; }
virtual XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () inline virtual
Safely cast to a Declaration, or null.
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 463 of file tinyxml2.h.
Referenced by tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLHandle::ToDeclaration(), and tinyxml2::XMLConstHandle::ToDeclaration().
virtual const XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () const inline virtual
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 470 of file tinyxml2.h.
 { return 0; }
virtual XMLDocument* tinyxml2::XMLNode::ToDocument () inline virtual
Safely cast to a Document, or null.
Reimplemented in tinyxml2::XMLDocument.
Definition at line 462 of file tinyxml2.h.
virtual const XMLDocument* tinyxml2::XMLNode::ToDocument () const inline virtual
Reimplemented in tinyxml2::XMLDocument.
Definition at line 469 of file tinyxml2.h.
 { return 0; }
virtual XMLElement* tinyxml2::XMLNode::ToElement () inline virtual
Safely cast to an Element, or null.
Reimplemented in tinyxml2::XMLElement.
Definition at line 459 of file tinyxml2.h.
Referenced by ParseDeep(), tinyxml2::XMLElement::ShallowEqual(), tinyxml2::XMLHandle::ToElement(), and tinyxml2::XMLConstHandle::ToElement().
virtual const XMLElement* tinyxml2::XMLNode::ToElement () const inline virtual
Reimplemented in tinyxml2::XMLElement.
Definition at line 466 of file tinyxml2.h.
 { return 0; }
virtual XMLText* tinyxml2::XMLNode::ToText () inline virtual
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 460 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLHandle::ToText(), and tinyxml2::XMLConstHandle::ToText().
virtual const XMLText* tinyxml2::XMLNode::ToText () const inline virtual
Reimplemented in tinyxml2::XMLText.
Definition at line 467 of file tinyxml2.h.
 { return 0; }
virtual XMLUnknown* tinyxml2::XMLNode::ToUnknown () inline virtual
Safely cast to an Unknown, or null.
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 464 of file tinyxml2.h.
Referenced by tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLHandle::ToUnknown(), and tinyxml2::XMLConstHandle::ToUnknown().
virtual const XMLUnknown* tinyxml2::XMLNode::ToUnknown () const inline virtual
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 471 of file tinyxml2.h.
 { return 0; }
void XMLNode::Unlink (XMLNode * child) private
Definition at line 610 of file tinyxml2.cpp.
References firstChild, lastChild, next, parent, prev, and TIXMLASSERT.
Referenced by DeleteChildren(), and ~XMLNode().
 {
         TIXMLASSERT( child->parent == this );
         if ( child == firstChild )
                 firstChild = firstChild->next;
         if ( child == lastChild )
                 lastChild = lastChild->prev;
         if ( child->prev ) {
                 child->prev->next = child->next;
         }
         if ( child->next ) {
                 child->next->prev = child->prev;
         }
         child->parent = 0;
 }
const char* tinyxml2::XMLNode::Value () const inline
The meaning of 'value' changes for the specific type.
    Document:   empty
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:               the text string
Definition at line 482 of file tinyxml2.h.
References tinyxml2::StrPair::GetStr(), and value.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::Name(), ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
 { return value.GetStr(); }
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 450 of file tinyxml2.h.
friend class XMLElement friend
Definition at line 451 of file tinyxml2.h.
Member Data Documentation
XMLDocument* tinyxml2::XMLNode::document protected
Definition at line 607 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), GetDocument(), tinyxml2::XMLElement::ParseAttributes(), ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), and tinyxml2::XMLDocument::XMLDocument().
XMLNode* tinyxml2::XMLNode::firstChild protected
Definition at line 611 of file tinyxml2.h.
Referenced by DeleteChildren(), FirstChild(), FirstChildElement(), InsertEndChild(), InsertFirstChild(), NoChildren(), and Unlink().
XMLNode* tinyxml2::XMLNode::lastChild protected
Definition at line 612 of file tinyxml2.h.
Referenced by DeleteChildren(), InsertEndChild(), InsertFirstChild(), LastChild(), LastChildElement(), and Unlink().
MemPool* tinyxml2::XMLNode::memPool private
Definition at line 618 of file tinyxml2.h.
Referenced by tinyxml2::XMLDocument::Identify().
XMLNode* tinyxml2::XMLNode::next protected
Definition at line 615 of file tinyxml2.h.
Referenced by FirstChildElement(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), NextSibling(), NextSiblingElement(), Unlink(), and tinyxml2::XMLElement::~XMLElement().
XMLNode* tinyxml2::XMLNode::parent protected
Definition at line 608 of file tinyxml2.h.
Referenced by DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), Parent(), Unlink(), and ~XMLNode().
XMLNode* tinyxml2::XMLNode::prev protected
Definition at line 614 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), LastChildElement(), PreviousSibling(), PreviousSiblingElement(), and Unlink().
StrPair tinyxml2::XMLNode::value mutable protected
Definition at line 609 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::Attribute(), FirstChildElement(), LastChildElement(), ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLElement::ParseDeep(), SetValue(), and Value().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/src/tinyxml2.cpp