antioch-0.0.7: Antioch::VantHoffRate< CoeffType > Class Template Reference
Antioch::VantHoffRate< CoeffType > Class Template Reference
Van't Hoff rate equation.
#include <kinetics_type.h>
Public Member Functions
VantHoffRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType Ea=0., const CoeffType D=0., const CoeffType Tref=1., const CoeffType rscale=Constants::R_universal< CoeffType >()/1000.)
~VantHoffRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_Ea (const CoeffType Ea)
void set_D (const CoeffType D)
void set_Tref (const CoeffType Tref)
void set_rscale (const CoeffType rscale)
CoeffType Cf () const
CoeffType eta () const
CoeffType Ea () const
CoeffType D () const
CoeffType Tref () const
CoeffType rscale () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_pow (T, _eta)*ant_exp(-_Ea/T+_D *T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
template<typename StateType >
StateType operator() (const StateType &T) const
template<typename StateType >
StateType derivative (const StateType &T) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &T, StateType &rate, StateType &drate_dT) const
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)*(_D+_eta/T+_Ea/(T *T))) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _raw_Ea
CoeffType _Ea
CoeffType _D
CoeffType _Tref
CoeffType _rscale
Detailed Description
template<typename CoeffType>
class Antioch::VantHoffRate< CoeffType >
Van't Hoff rate equation.
The Van't Hoff kinetics model is of the form:
thus
Internally, we use the reduced pre-exponential parameter and the reduced activation energy
Definition at line 54 of file kinetics_type.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::VantHoffRate< CoeffType >::VantHoffRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType Ea = 0., const CoeffType D = 0., const CoeffType Tref = 1., const CoeffType rscale = Constants::R_universal<CoeffType>()/1000.)
Definition at line 123 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Ea, Antioch::VantHoffRate< CoeffType >::_raw_Ea, Antioch::VantHoffRate< CoeffType >::_rscale, Antioch::VantHoffRate< CoeffType >::compute_cf(), and std::pow().
     : KineticsType<CoeffType>(KineticsModel::VANTHOFF),
       _raw_Cf(Cf),
       _eta(eta),
       _raw_Ea(Ea),
       _D(D),
       _Tref(Tref),
       _rscale(rscale)
   {
     using std::pow;
     _Ea = _raw_Ea / _rscale;
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::VantHoffRate< CoeffType >::~VantHoffRate ()
Definition at line 141 of file vanthoff_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType> _Cf* Antioch::VantHoffRate< CoeffType >::ant_pow (T , _eta) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::Cf () const inline
Definition at line 219 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Cf.
Referenced by Antioch::VantHoffRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::compute_cf () inline private
Definition at line 256 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Cf, Antioch::VantHoffRate< CoeffType >::_eta, Antioch::VantHoffRate< CoeffType >::_raw_Cf, Antioch::VantHoffRate< CoeffType >::_Tref, and std::pow().
Referenced by Antioch::VantHoffRate< CoeffType >::set_Cf(), Antioch::VantHoffRate< CoeffType >::set_Tref(), and Antioch::VantHoffRate< CoeffType >::VantHoffRate().
   {
     _Cf = _raw_Cf * pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
template<typename CoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType >::compute_rate_and_derivative (const StateType & T, StateType & rate, StateType & drate_dT) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 229 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(T,rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::D () const inline
Definition at line 234 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_D.
Referenced by Antioch::VantHoffRate< CoeffType >::set_D().
   { return _D; }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::derivative (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 175 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by tester(), and vectester().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::Ea () const inline
Definition at line 229 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Ea.
Referenced by Antioch::VantHoffRate< CoeffType >::set_Ea().
   { return _Ea; }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::eta () const inline
Definition at line 224 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_eta.
Referenced by Antioch::VantHoffRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > const std::string Antioch::VantHoffRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 147 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_D, Antioch::VantHoffRate< CoeffType >::_eta, Antioch::VantHoffRate< CoeffType >::_raw_Cf, Antioch::VantHoffRate< CoeffType >::_raw_Ea, and Antioch::VantHoffRate< CoeffType >::_Tref.
   {
     std::stringstream os;
     os << _raw_Cf;
     if (_eta != 0.) os << "*(T/" << _Tref << ")^" << _eta;
     os << "*exp(-" << _raw_Ea << "/(R*T) + " << _D << "*T)";
     return os.str();
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType >::operator() (const StateType & T) const inline inherited
Returns
error because I cannot make it pure virtual.
Definition at line 121 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(T);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(T);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(T);
   }
template<typename CoeffType > void Antioch::KineticsType< CoeffType >::print (std::ostream & os = std::cout) const inline inherited
Formatted print, by default to std::cout.
Definition at line 98 of file kinetics_type.h.
   {
     os << numeric();
   }
template<typename CoeffType> template<typename StateType > Antioch::VantHoffRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::rscale () const inline
Definition at line 239 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_rscale.
Referenced by Antioch::VantHoffRate< CoeffType >::set_rscale().
   { return _rscale; }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 160 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_raw_Cf, Antioch::VantHoffRate< CoeffType >::Cf(), Antioch::VantHoffRate< CoeffType >::compute_cf(), and std::pow().
   {
     using std::pow;
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_D (const CoeffType D) inline
Definition at line 210 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_D, and Antioch::VantHoffRate< CoeffType >::D().
   {
     _D = D;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_Ea (const CoeffType Ea) inline
Definition at line 192 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Ea, Antioch::VantHoffRate< CoeffType >::_raw_Ea, Antioch::VantHoffRate< CoeffType >::_rscale, and Antioch::VantHoffRate< CoeffType >::Ea().
   {
     _raw_Ea = Ea;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 184 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_eta, and Antioch::VantHoffRate< CoeffType >::eta().
   {
     _eta = eta;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_rscale (const CoeffType rscale) inline
Definition at line 201 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Ea, Antioch::VantHoffRate< CoeffType >::_raw_Ea, Antioch::VantHoffRate< CoeffType >::_rscale, and Antioch::VantHoffRate< CoeffType >::rscale().
   {
     _rscale = rscale;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 172 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Tref, Antioch::VantHoffRate< CoeffType >::compute_cf(), std::pow(), and Antioch::VantHoffRate< CoeffType >::Tref().
   {
     using std::pow;
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::Tref () const
Referenced by Antioch::VantHoffRate< CoeffType >::set_Tref().
Member Data Documentation
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_Cf private
Definition at line 61 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::Cf(), and Antioch::VantHoffRate< CoeffType >::compute_cf().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_D private
Definition at line 65 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::D(), Antioch::VantHoffRate< CoeffType >::numeric(), and Antioch::VantHoffRate< CoeffType >::set_D().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_Ea private
Definition at line 64 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::Ea(), Antioch::VantHoffRate< CoeffType >::set_Ea(), Antioch::VantHoffRate< CoeffType >::set_rscale(), and Antioch::VantHoffRate< CoeffType >::VantHoffRate().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_eta private
Definition at line 62 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::compute_cf(), Antioch::VantHoffRate< CoeffType >::eta(), Antioch::VantHoffRate< CoeffType >::numeric(), and Antioch::VantHoffRate< CoeffType >::set_eta().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_raw_Cf private
Definition at line 60 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::compute_cf(), Antioch::VantHoffRate< CoeffType >::numeric(), and Antioch::VantHoffRate< CoeffType >::set_Cf().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_raw_Ea private
Definition at line 63 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::numeric(), Antioch::VantHoffRate< CoeffType >::set_Ea(), Antioch::VantHoffRate< CoeffType >::set_rscale(), and Antioch::VantHoffRate< CoeffType >::VantHoffRate().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_rscale private
Definition at line 67 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::rscale(), Antioch::VantHoffRate< CoeffType >::set_Ea(), Antioch::VantHoffRate< CoeffType >::set_rscale(), and Antioch::VantHoffRate< CoeffType >::VantHoffRate().
template<typename CoeffType> CoeffType Antioch::VantHoffRate< CoeffType >::_Tref private
Definition at line 66 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::compute_cf(), Antioch::VantHoffRate< CoeffType >::numeric(), and Antioch::VantHoffRate< CoeffType >::set_Tref().
template<typename CoeffType> _Cf(*) StateType StateType& drate_d Antioch::VantHoffRate< CoeffType >::const)
Definition at line 111 of file vanthoff_rate.h.
template<typename CoeffType> _Cf(*) StateType Antioch::VantHoffRate< CoeffType >::rate)
Definition at line 111 of file vanthoff_rate.h.
template<typename CoeffType> _Cf(* Antioch::VantHoffRate< CoeffType >::this)(T)*(_D+_eta/T+_Ea/(T *T)))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 107 of file vanthoff_rate.h.
The documentation for this class was generated from the following files:
src/kinetics/include/antioch/kinetics_type.h
src/kinetics/include/antioch/vanthoff_rate.h