antioch-0.0.7: test/wilke_transport_unit.C File Reference
wilke_transport_unit.C File Reference
#include <iostream>
#include <cmath>
#include "antioch/vector_utils_decl.h"
#include "antioch/chemical_mixture.h"
#include "antioch/stat_mech_thermo.h"
#include "antioch/eucken_thermal_conductivity.h"
#include "antioch/blottner_viscosity.h"
#include "antioch/wilke_mixture.h"
#include "antioch/wilke_evaluator.h"
#include "antioch/blottner_parsing.h"
#include "antioch/vector_utils.h"
Functions
template<typename Scalar >
int test_val (const Scalar val, const Scalar val_exact, const Scalar tol, const std::string &val_name)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
int main ()
Definition at line 156 of file wilke_transport_unit.C.
 {
   return ( tester<double>()  ||
            tester<long double>() ||
            tester<float>()
            );
 }
template<typename Scalar > int test_val (const Scalar val, const Scalar val_exact, const Scalar tol, const std::string & val_name)
Definition at line 47 of file wilke_transport_unit.C.
 {
   using std::abs;
   int return_flag = 0;
   const Scalar rel_error = abs( (val - val_exact)/val_exact);
   if( rel_error  > tol )
     {
       std::cerr << "Error: Mismatch in " << val_name << std::endl
                 << val_name << "    = " << val << std::endl
                 << val_name+"_exact = " << val_exact << std::endl
                 << "rel_error = " << rel_error << std::endl
                 << "tol = " << tol << std::endl;
       return_flag = 1;
     }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 69 of file wilke_transport_unit.C.
References Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::compute_phi(), Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::k(), Antioch::ChemicalMixture< CoeffType >::M(), Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::mu(), Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::mu_and_k(), std::pow(), Antioch::read_blottner_data_ascii_default(), and test_val().
 {
   using std::pow;
   std::vector<std::string> species_str_list;
   const unsigned int n_species = 5;
   species_str_list.reserve(n_species);
   species_str_list.push_back( "N2" );
   species_str_list.push_back( "O2" );
   species_str_list.push_back( "N" );
   species_str_list.push_back( "O" );
   species_str_list.push_back( "NO" );
   Antioch::ChemicalMixture<Scalar> chem_mixture( species_str_list );
   Antioch::WilkeMixture<Scalar> wilke_mixture( chem_mixture );
   Antioch::StatMechThermodynamics<Scalar> thermo( chem_mixture );
   Antioch::EuckenThermalConductivity<Antioch::StatMechThermodynamics<Scalar> > k( thermo );
   Antioch::MixtureViscosity<Antioch::BlottnerViscosity<Scalar>, Scalar> mu( chem_mixture );
   Antioch::read_blottner_data_ascii_default( mu );
   Antioch::WilkeEvaluator< Antioch::MixtureViscosity<Antioch::BlottnerViscosity<Scalar>, Scalar>,
                            Antioch::EuckenThermalConductivity<Antioch::StatMechThermodynamics<Scalar> >,
                            Scalar > wilke( wilke_mixture, mu, k );
   int return_flag = 0;
   const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 2;
   // First check phi calculation
   // phi_s = sum_r (chi_r*(1+sqrt(mu_s/mu_r)*(Mr/Ms)^(1/4))^2)/sqrt(8*(1+Ms/Mr))
   {
     std::vector<Scalar> mu( 5 );
     mu[0] = 0.1L;
     mu[1] = 0.2L;
     mu[2] = 0.3L;
     mu[3] = 0.15L;
     mu[4] = 0.25L;
     std::vector<Scalar> chi( 5 );
     chi[0] = 0.1L;
     chi[1] = 0.2L;
     chi[2] = 0.3L;
     chi[3] = 0.15L;
     chi[4] = 0.25L;
     Scalar phi_N_exact = 0.0L;
     unsigned int N_index = 2;
     Scalar M_N = chem_mixture.M(N_index);
     for( unsigned int r = 0; r < 5; r++ )
       {
         Scalar M_r = chem_mixture.M(r);
         Scalar dummy = 1.0L + std::sqrt(mu[N_index]/mu[r])*pow( M_r/M_N, Scalar(0.25L) );
         phi_N_exact += chi[r]*dummy*dummy/std::sqrt(8.0L*( 1.0L + M_N/M_r ) );
       }
     Scalar phi_N;
     phi_N = wilke.compute_phi( mu, chi, N_index );
     return_flag = test_val( phi_N, phi_N_exact, tol, std::string("phi") );
   }
   std::vector<Scalar> mass_fractions( 5, 0.2L);
   // Currently dummy
   //const Scalar mu_exact = ;
   const Scalar T = 1000.0L;
   Scalar wilke_mu = wilke.mu(T, mass_fractions );
   Scalar wilke_k = wilke.k(T, mass_fractions );
   wilke.mu_and_k(T,mass_fractions,wilke_mu,wilke_k);
   int return_flag_temp = 0;
   //return_flag_temp = test_mu( wilke.mu(T, mass_fractions ), mu_exact, tol );
   if( return_flag_temp != 0 ) return_flag = 1;
   return return_flag;
 }