antioch-0.0.7: Antioch Namespace Reference
Antioch Namespace Reference
The parameters are reduced parameters.
Namespaces
Constants
KineticsModel
ReactionType
Classes
class ChemicalMixture
Class storing chemical mixture properties.
class ChemicalSpecies
Class to encapsulate data for each chemical species.
class ArrheniusRate
Arrhenius rate equation.
class BerthelotRate
Berthelot rate equation.
class BerthelotHercourtEssenRate
Berthelot Hercourt-Essen rate equation.
class DuplicateReaction
A single reaction mechanism.
class ElementaryReaction
A single reaction mechanism.
class FalloffReaction
Base class for falloff processes.
class HercourtEssenRate
Hercourt-Essen rate equation.
class ReactionSet
This class encapsulates all the reaction mechanisms considered in a chemical nonequilibrium simulation.
class KineticsEvaluator
Class to handle computing mass source terms for a given ReactionSet.
class KooijRate
Kooij rate equation.
class VantHoffRate
Van't Hoff rate equation.
class KineticsType
base class for kinetics models
class LindemannFalloff
Simplest falloff model ()
class ThreeBodyReaction
A single reaction mechanism.
class TroeFalloff
The Troe falloff model is defined by:
with
The derivatives are therefore:
.
class Reaction
A single reaction mechanism.
class CEAThermoMixture
class CEAThermodynamics
class CEACurveFit
class CEAEvaluator
class StatMechThermodynamics
class TempCache
class BlottnerViscosity
class ConstantLewisDiffusivity
class EuckenThermalConductivity
class MixtureViscosity
class SutherlandViscosity
class WilkeEvaluator
class WilkeMixture
class LogicError
A class to represent the internal "this should never happen" errors, to be thrown by "antioch_error();".
class NotImplemented
A class to stub for features that should be in Antioch, but haven't been written yet, to be thrown by "antioch_not_implemented();".
class FileError
A class representing a failed attempt by the library to open a file (or construct an fstream, etc), to be thrown by "antioch_file_error(filename);" For ease of debugging, "filename" should include any (absolute or relative or implicit) pathname that was part of the failed open.
class FailedNewtonTTvInversion
A class representing failed Newton convergence in T/Tv inversion.
struct has_size< T, typename Antioch::enable_if_c< is_eigen< T >::value, void >::type >
struct return_auto< T, typename Antioch::enable_if_c< is_eigen< T >::value, void >::type >
struct size_type< T, typename Antioch::enable_if_c< is_eigen< T >::value, void >::type >
struct value_type< _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct raw_value_type< _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct is_eigen
struct state_type< T, typename enable_if_c< is_eigen< T >::value, void >::type >
struct eigen_library_tag
struct is_eigen< _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct rebind< _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, NewScalar >
struct has_size< T, typename Antioch::enable_if_c< is_metaphysicl< T >::value, void >::type >
struct return_auto< T, typename Antioch::enable_if_c< is_metaphysicl< T >::value, void >::type >
struct size_type< T, typename Antioch::enable_if_c< is_metaphysicl< T >::value, void >::type >
struct value_type< T, typename Antioch::enable_if_c< is_metaphysicl< T >::value, void >::type >
struct raw_value_type< T, typename Antioch::enable_if_c< is_metaphysicl< T >::value, void >::type >
struct is_metaphysicl
struct is_metaphysicl< MetaPhysicL::NumberArray< size, T > >
struct metaphysicl_library_tag
struct state_type< T, typename enable_if_c< is_metaphysicl< T >::value, void >::type >
struct rebind< MetaPhysicL::NumberArray< size, T >, NewScalar >
struct enable_if_c
struct enable_if_c< false, T >
struct if_else_type
struct if_else_type< false, T1, T2 >
struct numeric_library_tag
struct has_size
struct return_auto
struct size_type
struct value_type
struct state_type
struct raw_value_type
struct rebind
struct value_type< const T >
struct raw_value_type< const T >
struct return_auto< T, typename Antioch::enable_if_c< is_valarray< T >::value, void >::type >
struct has_size< std::valarray< T > >
struct size_type< std::valarray< T > >
struct value_type< std::valarray< T > >
struct raw_value_type< std::valarray< T > >
struct is_valarray
struct is_valarray< std::valarray< T > >
struct state_type< T, typename enable_if_c< is_valarray< T >::value, void >::type >
struct valarray_library_tag
struct rebind< std::valarray< T >, NewScalar >
struct rebind< std::vector< T >, NewScalar >
struct has_size< std::vector< T > >
struct return_auto< std::vector< T > >
struct size_type< std::vector< T > >
struct value_type< std::vector< T > >
struct raw_value_type< std::vector< T > >
struct vector_library_tag
struct return_auto< vex::vector< T > >
struct has_size< vex::vector< T > >
struct size_type< vex::vector< T > >
struct value_type< vex::vector< T > >
struct raw_value_type< vex::vector< T > >
struct vexcl_library_tag
struct rebind< vex::vector< T >, NewScalar >
Enumerations
enum Species {
Air = 0, CPAir, Ar, Arp,
C, Cp, C2, C2H,
C2H2, C3, CF, CF2,
CF3, CF4, CH, CH2,
CH3, CH4, Cl, Cl2,
CN, CNp, CO, COp,
CO2, F, F2, H,
Hp, H2, H2p, H2O,
H2O2, HCl, HCN, He,
Hep, HO2, N, Np,
N2, N2p, CPN2, Ne,
NCO, NH, NHp, NH2,
NH3, NO, NOp, NO2,
O, Op, O2, O2p,
OH, Si, SiO, e
}
Simple species enumeration list.
Functions
template<typename CoeffType >
KineticsType< CoeffType > * build_rate (const std::vector< CoeffType > &data, const KineticsModel::KineticsModel &kin)
cross-road to kinetics model
template<typename CoeffType >
Reaction< CoeffType > * build_reaction (const unsigned int n_species, const std::string &equation, const ReactionType::ReactionType &type, const KineticsModel::KineticsModel &kin)
template<class NumericType >
void read_blottner_data_ascii (MixtureViscosity< BlottnerViscosity< NumericType >, NumericType > &mu, std::istream &in)
template<class NumericType >
void read_blottner_data_ascii_default (MixtureViscosity< BlottnerViscosity< NumericType >, NumericType > &mu)
template<class NumericType >
void read_cea_mixture_data_ascii (CEAThermoMixture< NumericType > &thermo, std::istream &in)
template<class NumericType >
void read_cea_mixture_data_ascii_default (CEAThermoMixture< NumericType > &thermo)
template<class NumericType >
void read_cea_thermo_data_ascii (CEAThermodynamics< NumericType > &thermo, std::istream &in)
template<class NumericType >
void read_cea_thermo_data_ascii_default (CEAThermodynamics< NumericType > &thermo)
template<class NumericType >
void read_reaction_set_data_xml (const std::string &filename, const bool verbose, ReactionSet< NumericType > &reaction_set)
template<class NumericType >
void read_species_data_ascii (ChemicalMixture< NumericType > &chem_mixture, std::istream &in)
template<class NumericType >
void read_species_data_ascii_default (ChemicalMixture< NumericType > &chem_mixture)
template<class NumericType >
void read_species_vibrational_data_ascii (ChemicalMixture< NumericType > &chem_mixture, std::istream &in)
template<class NumericType >
void read_species_vibrational_data_ascii_default (ChemicalMixture< NumericType > &chem_mixture)
template<class NumericType >
void read_species_electronic_data_ascii (ChemicalMixture< NumericType > &chem_mixture, std::istream &in)
template<class NumericType >
void read_species_electronic_data_ascii_default (ChemicalMixture< NumericType > &chem_mixture)
template<class NumericType >
void read_sutherland_data_ascii (MixtureViscosity< SutherlandViscosity< NumericType >, NumericType > &mu, std::istream &in)
template<class NumericType >
void read_sutherland_data_ascii_default (MixtureViscosity< SutherlandViscosity< NumericType >, NumericType > &mu)
template void read_blottner_data_ascii< double > (MixtureViscosity< BlottnerViscosity< double >, double > &, std::istream &in)
template void read_blottner_data_ascii_default< double > (MixtureViscosity< BlottnerViscosity< double >, double > &mu)
void antioch_version_stdout ()
int get_antioch_version ()
template<typename T >
Antioch::enable_if_c< is_eigen
< T >::value, typename
value_type< T >::type >::type max (const T &in)
template<typename T >
Antioch::enable_if_c< is_eigen
< T >::value, typename
value_type< T >::type >::type min (const T &in)
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
_Matrix< _Scalar, _Rows, _Cols,
_Options, _MaxRows, _MaxCols > zero_clone (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &ex)
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols, typename Scalar2 >
void zero_clone (_Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &output, const _Matrix< Scalar2, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &ex)
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols, typename Scalar >
_Matrix< _Scalar, _Rows, _Cols,
_Options, _MaxRows, _MaxCols > constant_clone (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &ex, const Scalar &value)
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
void set_zero (_Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &a)
template<typename Condition , typename T1 , typename T2 >
enable_if_c< is_eigen< T1 >
::value &&is_eigen< T2 >
::value, typename state_type
< T1 >::type >::type if_else (const Condition &condition, const T1 &if_true, const T2 &if_false)
void skip_comment_lines (std::istream &in, const char comment_start)
Skip comment lines in the header of an ASCII text file prefixed with the comment character 'comment_start'.
template<typename T >
Antioch::enable_if_c
< is_metaphysicl< T >::value,
typename value_type< T >::type >
::type max (const T &in)
template<typename T >
Antioch::enable_if_c
< is_metaphysicl< T >::value,
typename value_type< T >::type >
::type min (const T &in)
template<typename Tbool , typename Ttrue , typename Tfalse >
Antioch::enable_if_c
< is_metaphysicl< Tbool >
::value &&is_metaphysicl
< Ttrue >::value
&&is_metaphysicl< Tfalse >
::value, typename state_type
< Ttrue >::type >::type if_else (const Tbool &condition, const Ttrue &if_true, const Tfalse &if_false)
ANTIOCH_PLAIN_SCALAR (float)
ANTIOCH_PLAIN_SCALAR (double)
ANTIOCH_PLAIN_SCALAR (long double)
ANTIOCH_PLAIN_SCALAR (short)
ANTIOCH_PLAIN_SCALAR (int)
ANTIOCH_PLAIN_SCALAR (unsigned short)
template<typename T >
void set_zero (T &output)
template<typename T >
T zero_clone (const T &)
template<typename T , typename T2 >
void zero_clone (T &output, const T2 &)
template<typename T >
void init_clone (T &output, const T &example)
template<typename Vector , typename Scalar >
void init_constant (Vector &output, const Scalar &example)
template<typename T , typename Scalar >
T constant_clone (const T &example, const Scalar &value)
template<typename T1 , typename T2 >
void zero_clone (T1 &output, const T2 &example)
template<typename T >
T if_else (bool condition, T if_true, T if_false)
std::pair< std::string, int > split_string_int_on_colon (const std::string &token)
Split on colon, and return name, int value pair.
std::pair< std::string, double > split_string_double_on_colon (const std::string &token)
Split on colon, and return name, double value pair.
int SplitString (const std::string &input, const std::string &delimiter, std::vector< std::string > &results, bool includeEmpties=true)
Taken from FIN-S for XML parsing.
template<typename T >
T max (const std::valarray< T > &in)
template<typename T >
T min (const std::valarray< T > &in)
template<typename T >
std::valarray< T > zero_clone (const std::valarray< T > &example)
template<typename T1 , typename T2 >
void zero_clone (std::valarray< T1 > &output, const std::valarray< T2 > &example)
template<typename T , typename Scalar >
std::valarray< T > constant_clone (const std::valarray< T > &example, const Scalar &value)
template<typename T >
void init_clone (std::valarray< T > &output, const std::valarray< T > &example)
template<typename T >
std::valarray< T > if_else (const std::valarray< bool > &condition, const std::valarray< T > &if_true, const std::valarray< T > &if_false)
template<typename T >
std::vector< T > zero_clone (const std::vector< T > &example)
template<typename T1 , typename T2 >
void zero_clone (std::vector< T1 > &output, const std::vector< T2 > &example)
template<typename T , typename Scalar >
std::vector< T > zero_clone (const std::vector< T > &example, const Scalar &value)
template<typename T >
void set_zero (std::vector< T > &a)
template<typename T , typename Scalar >
std::vector< T > constant_clone (const std::vector< T > &example, const Scalar &value)
template<typename T >
T max (const vex::vector< T > &in)
template<typename T >
T min (const vex::vector< T > &in)
template<typename T >
vex::vector< T > zero_clone (const vex::vector< T > &example)
template<typename T1 , typename T2 >
void zero_clone (vex::vector< T1 > &output, const vex::vector< T2 > &example)
template<typename T , typename Scalar >
vex::vector< T > constant_clone (const vex::vector< T > &example, const Scalar &value)
template<typename T >
void init_clone (vex::vector< T > &output, const vex::vector< T > &example)
template<typename BoolInput , typename IfValue , typename ElseValue >
boost::proto::result_of::make_expr
< boost::proto::tag::if_else_,
boost::proto::deduce_domain,
const vex::vector_expression
< BoolInput > &, const IfValue
&, const ElseValue & >::type
const if_else (const vex::vector_expression< BoolInput > &condition, const IfValue &if_true, const ElseValue &if_false)
Detailed Description
The parameters are reduced parameters.
The complete Van't Hoff equation is (all the others are deductible from it) with being a reference temperature and the ideal gas constant. The reduced parameters are:
This library is intended for performances, thus the reference temperature is taken equal to one in order to skip the division step (). This is not an option, this is an obligation: the kinetics equations are coded without the division step.
Enumeration Type Documentation
enum Antioch::Species
Simple species enumeration list.
By convention, standard periodic-table names are used, and for charged particles 'm' replaces '-', and 'p' replaces '+'. For example, 'NO+' is represented as 'NOp'. Originally taken from FIN-S.
Enumerator
Air
CPAir
Ar
Arp
C
Cp
C2
C2H
C2H2
C3
CF
CF2
CF3
CF4
CH
CH2
CH3
CH4
Cl
Cl2
CN
CNp
CO
COp
CO2
F
F2
H
Hp
H2
H2p
H2O
H2O2
HCl
HCN
He
Hep
HO2
N
Np
N2
N2p
CPN2
Ne
NCO
NH
NHp
NH2
NH3
NO
NOp
NO2
O
Op
O2
O2p
OH
Si
SiO
e
Definition at line 41 of file species_enum.h.
     {
       Air = 0,  // Thermally perfect air (Cv=Cv(T))
       CPAir,    // Calorically perfect air (Cv=constant)
       Ar,  Arp, // Argon and its positively charged ion
       C,   Cp,  // Atomic Carbon and its positively charged ion
       C2,
       C2H,
       C2H2,
       C3,
       CF,
       CF2,
       CF3,
       CF4,
       CH,
       CH2,
       CH3,
       CH4,
       Cl,
       Cl2,
       CN,  CNp,
       CO,  COp,
       CO2,
       F,
       F2,
       H,  Hp,
       H2, H2p,
       H2O,
       H2O2,
       HCl,
       HCN,
       He, Hep, // Helium and its positively charged ion
       HO2,
       N,  Np,  // Atomic Nitrogen and its positively charged ion
       N2, N2p, // Molecular Nitrogen and its positively charged ion
       CPN2,    // Calorically perfect N2 (Cv=constant)
       Ne,        // Neon
       NCO,
       NH, NHp,
       NH2,
       NH3,
       NO, NOp, // Nitric Oxide and its positively charged ion
       NO2,
       O,  Op,  // Atomic Oxygen and its positively charged ion
       O2, O2p, // Molecular Oxygen and its positively charged ion
       OH,
       Si,
       SiO,
       e        // Free electron
     };
Function Documentation
Antioch::ANTIOCH_PLAIN_SCALAR (float)
Antioch::ANTIOCH_PLAIN_SCALAR (double)
Antioch::ANTIOCH_PLAIN_SCALAR (long double)
Antioch::ANTIOCH_PLAIN_SCALAR (short)
Antioch::ANTIOCH_PLAIN_SCALAR (int)
Antioch::ANTIOCH_PLAIN_SCALAR (unsigned short)
void Antioch::antioch_version_stdout ()
Definition at line 38 of file antioch_version.C.
References ANTIOCH_BUILD_ARCH, ANTIOCH_BUILD_DATE, ANTIOCH_BUILD_HOST, ANTIOCH_BUILD_USER, ANTIOCH_BUILD_VERSION, ANTIOCH_CXX, ANTIOCH_CXXFLAGS, ANTIOCH_LIB_RELEASE, ANTIOCH_LIB_VERSION, and get_antioch_version().
Referenced by main().
   {
     std::cout << "--------------------------------------------------------" << std::endl;
     std::cout << "antioch Package: Version = " << ANTIOCH_LIB_VERSION;
     std::cout << " (" << get_antioch_version() << ")" << std::endl << std::endl;
     std::cout << ANTIOCH_LIB_RELEASE << std::endl << std::endl;
     std::cout << "Build Date   = " << ANTIOCH_BUILD_DATE     << std::endl;
     std::cout << "Build Host   = " << ANTIOCH_BUILD_HOST     << std::endl;
     std::cout << "Build User   = " << ANTIOCH_BUILD_USER     << std::endl;
     std::cout << "Build Arch   = " << ANTIOCH_BUILD_ARCH     << std::endl;
     std::cout << "Build Rev    = " << ANTIOCH_BUILD_VERSION  << std::endl << std::endl;
     std::cout << "C++ Config   = " << ANTIOCH_CXX << " " << ANTIOCH_CXXFLAGS << std::endl;
     std::cout << "--------------------------------------------------------" << std::endl;
     return;
   }
template<typename CoeffType > KineticsType< CoeffType > * Antioch::build_rate (const std::vector< CoeffType > & data, const KineticsModel::KineticsModel & kin) inline
cross-road to kinetics model
We take here the parameters as:
Definition at line 56 of file kinetics_parsing.h.
References antioch_assert_equal_to, antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, std::pow(), and Antioch::KineticsModel::VANTHOFF.
   {
     using std::pow;
     KineticsType<CoeffType>* rate = NULL;
     switch(kin)
       {
       case(KineticsModel::HERCOURT_ESSEN):
         {
           antioch_assert_equal_to(3,data.size());
           rate = new HercourtEssenRate<CoeffType>(data[0],data[1],data[2]);//Cf,eta,Tref
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           antioch_assert_equal_to(2,data.size());
           rate = new BerthelotRate<CoeffType>(data[0],data[1]);// Cf, D
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           antioch_assert_equal_to(3,data.size());
           rate = new ArrheniusRate<CoeffType>(data[0],data[1],data[2]);//Cf,Ea,scale
         }
         break;
       case(KineticsModel::BHE):
         {
           antioch_assert_equal_to(4,data.size());
           rate = new BerthelotHercourtEssenRate<CoeffType>(data[0],data[1],data[2],data[3]);//Cf,eta,D,Tref
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           antioch_assert_equal_to(5,data.size());
           rate = new KooijRate<CoeffType>(data[0],data[1],data[2],data[3],data[4]);//Cf,eta,Ea,Tref,scale
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           antioch_assert_equal_to(6,data.size());
           rate = new VantHoffRate<CoeffType>(data[0],data[1],data[2],data[3],data[4],data[5]);//Cf,eta,Ea,D,Tref,scale
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(kin)
     return rate;
   }
template<typename CoeffType > Reaction< CoeffType > * Antioch::build_reaction (const unsigned int n_species, const std::string & equation, const ReactionType::ReactionType & type, const KineticsModel::KineticsModel & kin) inline
Definition at line 51 of file reaction_parsing.h.
References antioch_error, Antioch::ReactionType::DUPLICATE, Antioch::ReactionType::ELEMENTARY, Antioch::ReactionType::LINDEMANN_FALLOFF, Antioch::ReactionType::THREE_BODY, and Antioch::ReactionType::TROE_FALLOFF.
   {
     Reaction<CoeffType>* reaction = NULL;
     switch(type)
       {
       case(ReactionType::ELEMENTARY):
         {
           reaction = new ElementaryReaction<CoeffType>(n_species,equation,kin);
         }
         break;
       case(ReactionType::DUPLICATE):
         {
           reaction = new DuplicateReaction<CoeffType>(n_species,equation,kin);
         }
         break;
       case(ReactionType::THREE_BODY):
         {
           reaction = new ThreeBodyReaction<CoeffType>(n_species,equation,kin);
         }
         break;
       case(ReactionType::LINDEMANN_FALLOFF):
         {
           reaction = new FalloffReaction<CoeffType,LindemannFalloff<CoeffType> >(n_species,equation,type,kin);
         }
       case(ReactionType::TROE_FALLOFF):
         {
           reaction = new FalloffReaction<CoeffType,TroeFalloff<CoeffType> >(n_species,equation,type,kin);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(type)
     // Dummy
     return reaction;
   }
template<typename T , typename Scalar > std::vector<T> Antioch::constant_clone (const std::vector< T > & example, const Scalar & value) inline
template<typename T , typename Scalar > T Antioch::constant_clone (const T & example, const Scalar & value) inline
Definition at line 130 of file metaprogramming.h.
 { return value; }
template<typename T , typename Scalar > vex::vector< T > Antioch::constant_clone (const vex::vector< T > & example, const Scalar & value) inline
Definition at line 171 of file vexcl_utils.h.
 {
   vex::vector<T> returnval(example.queue_list(), example.size());
   returnval = value;
   return returnval;
 }
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols, typename Scalar > _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > Antioch::constant_clone (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & ex, const Scalar & value) inline
Definition at line 183 of file eigen_utils.h.
Referenced by Antioch::CEAEvaluator< CoeffType >::cp(), Antioch::CEAThermodynamics< NumericType >::cp(), Antioch::LindemannFalloff< CoeffType >::F_and_derivatives(), Antioch::TroeFalloff< CoeffType >::F_and_derivatives(), Antioch::CEACurveFit< CoeffType >::interval(), Antioch::LindemannFalloff< CoeffType >::operator()(), Antioch::TroeFalloff< CoeffType >::operator()(), and Antioch::LindemannFalloff< CoeffType >::value().
 {
   // We can't just use setZero here with arbitrary _Scalar types
   if (ex.size())
     return
       _Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>
         (ex.rows(), ex.cols()).setConstant(value);
   return
     _Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>
       (ex.rows(), ex.cols());
 }
template<typename T , typename Scalar > std::valarray< T > Antioch::constant_clone (const std::valarray< T > & example, const Scalar & value) inline
Definition at line 189 of file valarray_utils.h.
 {
   if (example.size())
     return std::valarray<T>(value,example.size());
   else
     return std::valarray<T>();
 }
int Antioch::get_antioch_version ()
Definition at line 58 of file antioch_version.C.
References ANTIOCH_MAJOR_VERSION, ANTIOCH_MICRO_VERSION, and ANTIOCH_MINOR_VERSION.
Referenced by antioch_version_stdout().
   {
     /* Note: return format follows the versioning convention xx.yy.zz where
        xx = major version number
        yy = minor version number
        zz = micro version number
        For example:
        v.   0.23  -> 002300 = 2300
        v   0.23.1 -> 002301 = 2301
        v. 10.23.2 -> 102302         */
     int major_version = 0;
     int minor_version = 0;
     int micro_version = 0;
 #ifdef ANTIOCH_MAJOR_VERSION
     major_version = ANTIOCH_MAJOR_VERSION;
 #endif
 #ifdef ANTIOCH_MINOR_VERSION
     minor_version = ANTIOCH_MINOR_VERSION;
 #endif
 #ifdef ANTIOCH_MICRO_VERSION
     micro_version = ANTIOCH_MICRO_VERSION;
 #endif
     return major_version*10000 + minor_version*100 + micro_version;
   }
template<typename Tbool , typename Ttrue , typename Tfalse > Antioch::enable_if_c< is_metaphysicl< Tbool >::value &&is_metaphysicl< Ttrue >::value &&is_metaphysicl< Tfalse >::value, typename state_type< Ttrue >::type >::type Antioch::if_else (const Tbool & condition, const Ttrue & if_true, const Tfalse & if_false) inline
Definition at line 135 of file metaphysicl_utils.h.
References antioch_assert_equal_to.
 {
   typename state_type<Ttrue>::type returnval;
   antioch_assert_equal_to(condition.size(), if_true.size());
   antioch_assert_equal_to(condition.size(), if_false.size());
   for (std::size_t i=0; i != condition.size(); ++i)
     returnval[i] = condition[i] ? if_true[i] : if_false[i];
   return returnval;
 }
template<typename T > T Antioch::if_else (bool condition, T if_true, T if_false) inline
template<typename BoolInput , typename IfValue , typename ElseValue > boost::proto::result_of::make_expr< boost::proto::tag::if_else_, boost::proto::deduce_domain, const vex::vector_expression< BoolInput > &, const IfValue &, const ElseValue & >::type const Antioch::if_else (const vex::vector_expression< BoolInput > & condition, const IfValue & if_true, const ElseValue & if_false) inline
Definition at line 197 of file vexcl_utils.h.
References boost::proto::if_else().
 {
   return boost::proto::if_else(condition, if_true, if_false);
 }
template<typename T > std::valarray< T > Antioch::if_else (const std::valarray< bool > & condition, const std::valarray< T > & if_true, const std::valarray< T > & if_false) inline
Definition at line 214 of file valarray_utils.h.
References antioch_assert_equal_to.
 {
   antioch_assert_equal_to(condition.size(), if_true.size());
   antioch_assert_equal_to(condition.size(), if_false.size());
   const std::size_t size = condition.size();
   std::valarray<T> returnval(size);
   for (std::size_t i=0; i != size; ++i)
     returnval[i] = condition[i] ? if_true[i] : if_false[i];
   return returnval;
 }
template<typename Condition , typename T1 , typename T2 > enable_if_c< is_eigen< T1 >::value &&is_eigen< T2 >::value, typename state_type< T1 >::type >::type Antioch::if_else (const Condition & condition, const T1 & if_true, const T2 & if_false) inline
Definition at line 220 of file eigen_utils.h.
Referenced by Antioch::CEAEvaluator< CoeffType >::cp(), Antioch::CEAThermodynamics< NumericType >::cp(), Antioch::CEAEvaluator< CoeffType >::cp_over_R(), Antioch::CEAThermodynamics< NumericType >::cp_over_R(), Antioch::CEAEvaluator< CoeffType >::dh_RT_minus_s_R_dT(), Antioch::CEAThermodynamics< NumericType >::dh_RT_minus_s_R_dT(), Antioch::CEAEvaluator< CoeffType >::h_RT_minus_s_R(), Antioch::CEAThermodynamics< NumericType >::h_RT_minus_s_R(), and Antioch::CEACurveFit< CoeffType >::interval().
 {
   return condition.select(if_true, if_false);
 }
template<typename T > void Antioch::init_clone (T & output, const T & example) inline
Definition at line 117 of file metaprogramming.h.
Referenced by init_clone(), and init_constant().
 { output = example; }
template<typename T > void Antioch::init_clone (vex::vector< T > & output, const vex::vector< T > & example) inline
Definition at line 181 of file vexcl_utils.h.
 {
   output.resize(example.queue_list(), example.size());
   output = example;
 }
template<typename T > void Antioch::init_clone (std::valarray< T > & output, const std::valarray< T > & example) inline
Definition at line 202 of file valarray_utils.h.
References init_clone().
 {
   const std::size_t sz = example.size();
   output.resize(sz);
   for (std::size_t i=0; i != sz; ++i)
     init_clone(output[i], example[i]);
 }
template<typename Vector , typename Scalar > void Antioch::init_constant (Vector & output, const Scalar & example) inline
Definition at line 121 of file metaprogramming.h.
References init_clone().
Referenced by vectester().
 {
   for (typename Antioch::size_type<Vector>::type i=0;
        i != output.size(); ++i)
     init_clone(output[i], example);
 }
template<typename T > Antioch::enable_if_c< is_metaphysicl< T >::value, typename value_type< T >::type >::type Antioch::max (const T & in) inline
Definition at line 69 of file metaphysicl_utils.h.
References std::max(), and max().
 {
   using std::max;
   typename value_type<T>::type maxval = in[0];
   const std::size_t size = in.size();
   for (std::size_t i = 1; i < size; ++i)
     maxval = max(maxval, in[i]);
   return maxval;
 }
template<typename T > Antioch::enable_if_c< is_eigen< T >::value, typename value_type< T >::type >::type Antioch::max (const T & in) inline
Definition at line 90 of file eigen_utils.h.
Referenced by Antioch::CEAEvaluator< CoeffType >::cp_over_R(), Antioch::CEAThermodynamics< NumericType >::cp_over_R(), Antioch::StatMechThermodynamics< CoeffType >::cv_rot(), Antioch::CEAEvaluator< CoeffType >::dh_RT_minus_s_R_dT(), Antioch::CEAThermodynamics< NumericType >::dh_RT_minus_s_R_dT(), Antioch::CEAEvaluator< CoeffType >::h_RT_minus_s_R(), Antioch::CEAThermodynamics< NumericType >::h_RT_minus_s_R(), max(), Antioch::StatMechThermodynamics< CoeffType >::T_from_e_tot(), test_cp(), test_val(), test_viscosity(), vec_compare(), and vectester().
 {
   return in.maxCoeff();
 }
template<typename T > T Antioch::max (const vex::vector< T > & in) inline
Definition at line 104 of file vexcl_utils.h.
 {
   vex::Reductor<T, vex::MAX> vex_max(in.queue_list());
   return vex_max(in);
 }
template<typename T > T Antioch::max (const std::valarray< T > & in) inline
Definition at line 121 of file valarray_utils.h.
 {
   return in.max();
 }
template<typename T > Antioch::enable_if_c< is_metaphysicl< T >::value, typename value_type< T >::type >::type Antioch::min (const T & in) inline
Definition at line 86 of file metaphysicl_utils.h.
References std::min(), and min().
 {
   using std::min;
   typename value_type<T>::type minval = in[0];
   const std::size_t size = in.size();
   for (std::size_t i = 1; i < size; ++i)
     minval = min(minval, in[i]);
   return minval;
 }
template<typename T > Antioch::enable_if_c< is_eigen< T >::value, typename value_type< T >::type >::type Antioch::min (const T & in) inline
Definition at line 100 of file eigen_utils.h.
Referenced by Antioch::CEAEvaluator< CoeffType >::cp_over_R(), Antioch::CEAThermodynamics< NumericType >::cp_over_R(), Antioch::CEAEvaluator< CoeffType >::dh_RT_minus_s_R_dT(), Antioch::CEAThermodynamics< NumericType >::dh_RT_minus_s_R_dT(), Antioch::CEAEvaluator< CoeffType >::h_RT_minus_s_R(), Antioch::CEAThermodynamics< NumericType >::h_RT_minus_s_R(), min(), and Antioch::StatMechThermodynamics< CoeffType >::T_from_e_tot().
 {
   return in.minCoeff();
 }
template<typename T > T Antioch::min (const vex::vector< T > & in) inline
Definition at line 113 of file vexcl_utils.h.
 {
   vex::Reductor<T, vex::MIN> vex_min(in.queue_list());
   return vex_min(in);
 }
template<typename T > T Antioch::min (const std::valarray< T > & in) inline
Definition at line 129 of file valarray_utils.h.
 {
   return in.min();
 }
template<class NumericType > void Antioch::read_blottner_data_ascii (MixtureViscosity< BlottnerViscosity< NumericType >, NumericType > & mu, std::istream & in) inline
Definition at line 52 of file blottner_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), and skip_comment_lines().
Referenced by read_blottner_data_ascii_default().
   {
     // skip the header
     skip_comment_lines(in, '#');
     std::string name;
     NumericType a, b, c;
     while (in.good())
       {
         in >> name; // Species Name
         in >> a;    //
         in >> b;    //
         in >> c;    //
         // If we are still good, we have a valid set of transport
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             const ChemicalMixture<NumericType>& chem_mixture = mu.chemical_mixture();
             // Check if this is a species we want.
             if( chem_mixture.active_species_name_map().find(name) !=
                 chem_mixture.active_species_name_map().end() )
               {
                 // Pack up coefficients
                 std::vector<NumericType> coeffs(3);
                 coeffs[0] = a;
                 coeffs[1] = b;
                 coeffs[2] = c;
                 mu.add(name, coeffs);
               }
           }
       }
     return;
   }
template void Antioch::read_blottner_data_ascii< double > (MixtureViscosity< BlottnerViscosity< double >, double > & , std::istream & in)
template<class NumericType > void Antioch::read_blottner_data_ascii_default (MixtureViscosity< BlottnerViscosity< NumericType >, NumericType > & mu) inline
Definition at line 96 of file blottner_parsing.h.
References read_blottner_data_ascii().
Referenced by tester().
   {
     static const std::string
       default_blottner_transport_data
       ("#-----------------------------------------------------------------------------\n"
        "# Coefficients for Blottner viscosity model\n"
        "# Form of the fit:\n"
        "# \n"
        "# mu = 0.1*exp[A*log(T)*log(T) + B*log(T) + C]\n"
        "# \n"
        "# References:\n"
        "# \n"
        "# Air  -- Identical to N2 fit\n"
        "# N    -- Sandia Report SC-RR-70-754\n"
        "# N2   -- Sandia Report SC-RR-70-754\n"
        "# CPN2 -- Identical to N2 fit\n"
        "# NO   -- Sandia Report SC-RR-70-754\n"
        "# O    -- Sandia Report SC-RR-70-754\n"
        "# O2   -- Sandia Report SC-RR-70-754\n"
        "# C    -- AIAA-1997-2474\n"
        "# C2   -- AIAA-1997-2474\n"
        "# C3   -- AIAA-1997-2474\n"
        "# C2H  -- wild-ass guess: identical to HCN fit\n"
        "# CN   -- AIAA-1997-2474\n"
        "# CO   -- AIAA-1997-2474\n"
        "# CO2  -- AIAA-1997-2474\n"
        "# HCN  -- AIAA-1997-2474\n"
        "# H    -- AIAA-1997-2474\n"
        "# H2   -- AIAA-1997-2474\n"
        "# e    -- Sandia Report SC-RR-70-754\n"
        "\n"
        "Air     2.68142000000e-02  3.17783800000e-01 -1.13155513000e+01\n"
        "CPAir   2.68142000000e-02  3.17783800000e-01 -1.13155513000e+01\n"
        "N       1.15572000000e-02  6.03167900000e-01 -1.24327495000e+01\n"
        "N2      2.68142000000e-02  3.17783800000e-01 -1.13155513000e+01\n"
        "CPN2    2.68142000000e-02  3.17783800000e-01 -1.13155513000e+01\n"
        "NO      4.36378000000e-02 -3.35511000000e-02 -9.57674300000e+00\n"
        "O       2.03144000000e-02  4.29440400000e-01 -1.16031403000e+01\n"
        "O2      4.49290000000e-02 -8.26158000000e-02 -9.20194750000e+00\n"
        "C       -8.3285e-3         0.7703240         -12.7378000\n"
        "C2      -8.4311e-3         0.7876060         -13.0268000\n"
        "C3      -8.4312e-3         0.7876090         -12.8240000\n"
        "C2H     -2.4241e-2         1.0946550         -14.5835500\n"
        "CN      -8.3811e-3         0.7860330         -12.9406000\n"
        "CO      -0.019527394       1.013295          -13.97873\n"
        "CO2     -0.019527387       1.047818          -14.32212\n"
        "HCN     -2.4241e-2         1.0946550         -14.5835500\n"
        "H       -8.3912e-3         0.7743270         -13.6653000\n"
        "H2      -8.3346e-3         0.7815380         -13.5351000\n"
        "e       0.00000000000e+00  0.00000000000e+00 -1.16031403000e+01\n");
     std::istringstream buf(default_blottner_transport_data);
     read_blottner_data_ascii( mu, buf );
     return;
   }
template void Antioch::read_blottner_data_ascii_default< double > (MixtureViscosity< BlottnerViscosity< double >, double > & mu)
template<class NumericType > void Antioch::read_cea_mixture_data_ascii (CEAThermoMixture< NumericType > & thermo, std::istream & in) inline
Definition at line 59 of file cea_mixture_ascii_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), Antioch::CEAThermoMixture< NumericType >::add_curve_fit(), antioch_error, Antioch::CEAThermoMixture< NumericType >::check(), Antioch::CEAThermoMixture< NumericType >::chemical_mixture(), and skip_comment_lines().
Referenced by read_cea_mixture_data_ascii_default().
   {
     skip_comment_lines(in, '#');
     std::string name;
     unsigned int n_int;
     std::vector<NumericType> coeffs;
     NumericType h_form, val;
     const ChemicalMixture<NumericType>& chem_mixture = thermo.chemical_mixture();
     while (in.good())
       {
         in >> name;   // Species Name
         in >> n_int;  // Number of T intervals: [200-1000], [1000-6000], ([6000-20000])
         in >> h_form; // Formation Enthalpy @ 298.15 K
         coeffs.clear();
         for (unsigned int interval=0; interval<n_int; interval++)
           {
             for (unsigned int n=0; n<10; n++)
               {
                 in >> val, coeffs.push_back(val);
               }
           }
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             // Check if this is a species we want.
             if( chem_mixture.active_species_name_map().find(name) !=
                 chem_mixture.active_species_name_map().end() )
               {
                 thermo.add_curve_fit(name, coeffs);
               }
           }
       } // end while
     // Make sure we actually populated everything
     if( !thermo.check() )
       {
         std::cerr << "Error: CEA table not fully populated" << std::endl;
         antioch_error();
       }
     return;
   }
template<class NumericType > void Antioch::read_cea_mixture_data_ascii_default (CEAThermoMixture< NumericType > & thermo) inline
Definition at line 112 of file cea_mixture_ascii_parsing.h.
References read_cea_mixture_data_ascii().
Referenced by tester(), and vectester().
   {
     static const std::string
       default_thermo_data
       ("#-----------------------------------------------------------------------------\n"
       "# Cp, H, and S curve fit parameters from CEA program (1994)\n"
       "# \n"
       "# File Format:\n"
       "# \n"
       "# First line:\n"
       "# \n"
       "#        Species Name\n"
       "#        Number of T intervals: [200-1000], [1000-6000], ([6000-20000])\n"
       "#        Formation Enthalpy @ 298.15K\n"
       "# \n"
       "# Lines 2-4 (2-8):\n"
       "# \n"
       "#        a0-a4; a5-a9 for each interval.\n"
       "# \n"
       "# \n"
       "# Cp/R =  a0*T^-2   + a1*T^-1     + a2     + a3*T   + a4*T^2   + a5*T^3   + a6*T^4\n"
       "# H/RT = -a0*T^-2   + a1*T^-1*lnT + a2     + a3*T/2 + a4*T^2/3 + a5*T^3/4 + a6*T^4/5 + a8/T\n"
       "# S/R  = -a0*T^-2/2 - a1*T^-1     + a2*lnT + a3*T   + a4*T^2/2 + a5*T^3/3 + a6*T^4/4 + a9\n"
       "# \n"
       "# Note that a7 is always zero and is not used in the calculation of Cp,H, or S.\n"
       "# The constant is included simply for compatibility with cea.\n"
       "# \n"
       "# \n"
       "# Sources:\n"
       "# \n"
       "# All values come directly from cea400 program (05/98)\n"
       "# Note that for monotomics in which the only non-zero parameter is a2, cea \n"
       "# stores this value in the 1st position. This must be changed for FIN-S to \n"
       "# work correctly.\n"
       "# [PB]: HO2/H2O2 values taken from  http://www.grc.nasa.gov/WWW/CEAWeb/ceaThermoBuild.htm \n"
       "#-------------------------------------------------------------------------------\n"
       "\n"
       "Ar  3            0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  4.37967491e+00\n"
       "  2.01053848e+01 -5.99266107e-02  2.50006940e+00 -3.99214116e-08  1.20527214e-11\n"
       " -1.81901558e-15  1.07857664e-19  0.00000000e+00 -7.44993961e+02  4.37918011e+00\n"
       " -9.95126508e+08  6.45888726e+05 -1.67589470e+02  2.31993336e-02 -1.72108091e-06\n"
       "  6.53193846e-11 -9.74014773e-16  0.00000000e+00 -5.07830034e+06  1.46529848e+03\n"
       "                                                                          \n"
       "Ar+  3           1526778.407                                                      \n"
       " -5.73120917e+04  7.93079147e+02 -1.71712122e+00  1.04418402e-02 -1.18020750e-05\n"
       "  6.52813478e-09 -1.44755813e-12  0.00000000e+00  1.79057223e+05  2.94915095e+01\n"
       " -3.83596540e+05  8.16201970e+02  2.30134263e+00 -4.95298377e-06  1.20510848e-08\n"
       " -2.18505029e-12  1.26549390e-16  0.00000000e+00  1.77181146e+05  7.94750748e+00\n"
       "  1.01737284e+07 -6.68510410e+03  4.46095379e+00 -3.03416529e-04  2.62347956e-08\n"
       " -1.20511583e-12  2.30380688e-17  0.00000000e+00  2.35435354e+05 -1.04451930e+01\n"
       "                                                                          \n"
       "Air  2           -125.530                                                         \n"
       "  1.00995016e+04 -1.96827561e+02  5.00915511e+00 -5.76101373e-03  1.06685993e-05\n"
       " -7.94029797e-09  2.18523191e-12  0.00000000e+00 -1.76796731e+02 -3.92150098e+00\n"
       "  2.41521443e+05 -1.25787460e+03  5.14455867e+00 -2.13854179e-04  7.06522784e-08\n"
       " -1.07148349e-11  6.57780015e-16  0.00000000e+00  6.46226319e+03 -8.14740866e+00\n"
       "                                                                          \n"
       "CPAir  3         -125.530                                                 \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "                                                                          \n"
       "C  3             716680.000                                                       \n"
       "  6.49503147e+02 -9.64901086e-01  2.50467548e+00 -1.28144803e-05  1.98013365e-08\n"
       " -1.60614403e-11  5.31448341e-15  0.00000000e+00  8.54576311e+04  4.74799922e+00\n"
       " -1.28913647e+05  1.71952857e+02  2.64604439e+00 -3.35306895e-04  1.74209274e-07\n"
       " -2.90281783e-11  1.64218239e-15  0.00000000e+00  8.41059785e+04  4.13012235e+00\n"
       "  4.43252801e+08 -2.88601841e+05  7.73710832e+01 -9.71528189e-03  6.64959533e-07\n"
       " -2.23007878e-11  2.89938870e-16  0.00000000e+00  2.35527344e+06 -6.40512241e+02\n"
       "                                                                          \n"
       "C+  3            1809444.482                                                      \n"
       "  2.25853318e+03 -1.57454401e+00  2.50363759e+00 -5.20253954e-06  4.51647956e-09\n"
       " -2.18115104e-12  4.49430845e-16  0.00000000e+00  2.16895191e+05  4.34577527e+00\n"
       "  1.25511271e+04 -3.41187502e+01  2.54338322e+00 -2.80512097e-05  9.75164222e-09\n"
       " -1.73685542e-12  1.24619194e-16  0.00000000e+00  2.17100179e+05  4.06398843e+00\n"
       "  5.61815495e+05 -6.04705988e+03  5.88454166e+00 -7.21189472e-04  6.82348422e-08\n"
       " -2.59987863e-12  3.63386841e-17  0.00000000e+00  2.58137054e+05 -2.28001243e+01\n"
       "                                                                          \n"
       "C2  3            830457.000                                                       \n"
       "  5.55956757e+05 -9.98000622e+03  6.68153991e+01 -1.74341173e-01  2.44849356e-04\n"
       " -1.70344706e-07  4.68447130e-11  0.00000000e+00  1.44586386e+05 -3.44818817e+02\n"
       " -9.68890957e+05  3.56099020e+03 -5.06351169e-01  2.94509281e-03 -7.13928908e-07\n"
       "  8.67047006e-11 -4.07681670e-15  0.00000000e+00  7.68186000e+04  3.33990355e+01\n"
       "  6.31616742e+06  1.36534413e+04 -3.99672321e+00  1.93752303e-03 -1.58441823e-07\n"
       "  5.52076555e-12 -7.25360969e-17  0.00000000e+00  9.39290526e+03  6.61413426e+01\n"
       "                                                                          \n"
       "C2H  3           566205.472                                                       \n"
       "  7.65369105e+03 -4.18740132e+02  7.25427188e+00 -5.03701933e-03  8.23519623e-06\n"
       " -4.61676824e-09  9.50926320e-13  0.00000000e+00  6.85068967e+04 -1.58602839e+01\n"
       "  3.99586409e+06 -1.19690929e+04  1.71383304e+01 -3.33695957e-03  6.00328130e-07\n"
       " -5.49724012e-11  2.02273188e-15  0.00000000e+00  1.43142317e+05 -9.28591870e+01\n"
       "  0.              0.              7.59195493e+00  0.              0.            \n"
       "  0.              0.              0.              6.41223400e+04 -2.03895009e+01\n"
       "                                                                          \n"
       "C2H2  2  228200.000                                                       \n"
       "  1.59813325e+05 -2.21667505e+03  1.26572561e+01 -7.98017014e-03  8.05580151e-06\n"
       " -2.43394461e-09 -7.50945461e-14  0.00000000e+00  3.71263379e+04 -5.24443365e+01\n"
       "  1.71379212e+06 -5.92897095e+03  1.23611564e+01  1.31470625e-04 -1.36286904e-07\n"
       "  2.71274606e-11 -1.30208685e-15  0.00000000e+00  6.26648973e+04 -5.81886602e+01\n"
       "                                                                          \n"
       "C3  3            839948.500                                                       \n"
       " -4.35456285e+04  6.66010414e+02  1.45101513e+00  7.43442531e-03 -3.81010954e-06\n"
       " -2.33675605e-11  4.40699631e-13  0.00000000e+00  9.63517401e+04  2.02514928e+01\n"
       "  4.50804398e+06 -1.46101600e+04  2.28194701e+01 -8.54423692e-03  2.14604329e-06\n"
       " -2.10384214e-10  6.35151106e-15  0.00000000e+00  1.91196492e+05 -1.27185429e+02\n"
       "  5.62195627e+08 -4.80014820e+05  1.48773604e+02 -1.86380758e-02  1.25369345e-06\n"
       " -4.23152054e-11  5.69651073e-16  0.00000000e+00  3.77769020e+06 -1.22634937e+03\n"
       "                                                                          \n"
       "CF  2            242300.000                                                       \n"
       " -4.85659087e+04  8.37066845e+02 -1.58605380e+00  1.37329926e-02 -1.54543720e-05\n"
       "  8.89879494e-09 -2.08319768e-12  0.00000000e+00  2.41920950e+04  3.37110765e+01\n"
       " -7.30301173e+04 -3.10432552e+02  4.68755965e+00 -1.75388618e-05  1.17998295e-08\n"
       " -1.88283316e-12  1.89811962e-16  0.00000000e+00  2.93490294e+04 -2.32175022e+00\n"
       "                                                                          \n"
       "CF2  2            -186600.00                                                      \n"
       " -4.28469549e+04  9.42241347e+02 -3.83847378e+00  2.84787584e-02 -3.61855678e-05\n"
       "  2.30750321e-08 -5.91498489e-12  0.00000000e+00 -2.77993759e+04  4.66760006e+01\n"
       " -1.98592186e+06  4.47486108e+03  2.05367791e+00  2.54212017e-03 -6.46636536e-07\n"
       "  7.98822582e-11 -3.82452258e-15  0.00000000e+00 -5.43485110e+04  2.28899734e+01\n"
       "                                                                          \n"
       "CF3  2           -467400.000                                                      \n"
       " -2.89509314e+04  7.08259104e+02 -3.49874496e+00  3.60052779e-02 -4.51845638e-05\n"
       "  2.83046097e-08 -7.12428016e-12  0.00000000e+00 -6.05579954e+04  4.50043769e+01\n"
       " -3.00992537e+05 -1.04577415e+03  1.07783067e+01 -3.11222805e-04  6.88233084e-08\n"
       " -7.90018181e-12  3.66510631e-16  0.00000000e+00 -5.42636700e+04 -3.41619073e+01\n"
       "                                                                          \n"
       "CF4  2           -933500.000                                                      \n"
       "  9.81534964e+03  1.16366074e+02 -1.28852758e+00  3.95962388e-02 -4.99633605e-05\n"
       "  3.12541430e-08 -7.84194211e-12  0.00000000e+00 -1.13896083e+05  2.93876064e+01\n"
       " -4.16418379e+05 -1.41489926e+03  1.40513863e+01 -4.19996407e-04  9.28167764e-08\n"
       " -1.06499640e-11  4.93955439e-16  0.00000000e+00 -1.09514188e+05 -5.48720115e+01\n"
       "                                                                          \n"
       "CH  3            597338.000                                                       \n"
       "  2.22056413e+04 -3.40537175e+02  5.53138641e+00 -5.79489639e-03  7.96946173e-06\n"
       " -4.46585989e-09  9.59622884e-13  0.00000000e+00  7.24039052e+04 -9.10756700e+00\n"
       "  2.06073377e+06 -5.39612964e+03  7.85618794e+00 -7.96575798e-04  1.76427377e-07\n"
       " -1.97634586e-11  5.03028668e-16  0.00000000e+00  1.06219245e+05 -3.15471110e+01\n"
       " -8.06826755e+08  4.57539322e+05 -9.84385128e+01  1.23522859e-02 -8.48550223e-07\n"
       "  3.04037261e-11 -4.40026028e-16  0.00000000e+00 -3.59580957e+06  8.95336505e+02\n"
       "                                                                          \n"
       "CH2  2           388800.000                                                       \n"
       "  3.52591418e+04 -3.36765436e+02  4.50893691e+00  2.52106603e-03 -5.31151087e-06\n"
       "  6.65421308e-09 -2.61007296e-12  0.00000000e+00  4.73772550e+04 -3.80734012e+00\n"
       "  2.51041594e+06 -7.95393239e+03  1.23882957e+01 -1.77590968e-03  3.21740029e-07\n"
       " -3.06886344e-11  1.20490060e-15  0.00000000e+00  9.60102856e+04 -6.15597799e+01\n"
       "                                                                          \n"
       "CH3  2           146900.000                                                       \n"
       " -2.87728611e+04  5.09505607e+02  1.99073056e-01  1.36396516e-02 -1.43455892e-05\n"
       "  1.01396738e-08 -3.02843889e-12  0.00000000e+00  1.41109873e+04  2.02339462e+01\n"
       "  2.76090427e+06 -9.33655279e+03  1.48769863e+01 -1.43922769e-03  2.44392393e-07\n"
       " -2.22384579e-11  8.39158849e-16  0.00000000e+00  7.48476479e+04 -7.91948334e+01\n"
       "                                                                          \n"
       "CH4  2           -74600.000                                                       \n"
       " -1.76654573e+05  2.78547782e+03 -1.20193547e+01  3.91462588e-02 -3.61165608e-05\n"
       "  2.01838794e-08 -4.95577215e-12  0.00000000e+00 -2.33101156e+04  8.90108100e+01\n"
       "  3.74626570e+06 -1.38885134e+04  2.05402982e+01 -1.94419693e-03  4.32387145e-07\n"
       " -4.06101278e-11  1.64315927e-15  0.00000000e+00  7.56598868e+04 -1.22297711e+02\n"
       "                                                                          \n"
       "Cl  3             121301.000                                                      \n"
       "  2.27621585e+04 -2.16841329e+02  2.74518512e+00  2.45110169e-03 -5.45801199e-06\n"
       "  4.41798688e-09 -1.28813400e-12  0.00000000e+00  1.50135707e+04  3.10295076e+00\n"
       " -1.69793293e+05  6.08172646e+02  2.12866409e+00  1.30736703e-04 -2.64488360e-08\n"
       "  2.84250478e-12 -1.25291173e-16  0.00000000e+00  9.93438740e+03  8.84475941e+00\n"
       " -7.13968707e+07  4.49993633e+04 -9.26431535e+00  1.65743796e-03 -1.32621940e-07\n"
       "  5.53399887e-12 -8.39030188e-17  0.00000000e+00 -3.40533303e+05  1.06911130e+02\n"
       "                                                                          \n"
       "Cl2  2            0.000                                                           \n"
       "  3.46281724e+04 -5.54712949e+02  6.20759103e+00 -2.98963673e-03  3.17303416e-06\n"
       " -1.79363467e-09  4.26005863e-13  0.00000000e+00  1.53407075e+03 -9.43835303e+00\n"
       "  6.09256675e+06 -1.94962688e+04  2.85453491e+01 -1.44996828e-02  4.46388943e-06\n"
       " -6.35852403e-10  3.32735931e-14  0.00000000e+00  1.21211722e+05 -1.69077832e+02\n"
       "                                                                          \n"
       "CN  3            438683.448                                                       \n"
       "  3.94910175e+03 -1.39157387e+02  4.93077604e+00 -6.30459473e-03  1.25682136e-05\n"
       " -9.87818175e-09  2.84310304e-12  0.00000000e+00  5.22845470e+04 -2.76308000e+00\n"
       " -2.22797608e+06  5.04066445e+03 -2.12179448e-01  1.35488122e-03  1.32592277e-07\n"
       " -6.93693400e-11  5.49489162e-15  0.00000000e+00  1.78454233e+04  3.28251898e+01\n"
       " -1.79477307e+08  1.05433143e+05 -1.72959888e+01  2.19486383e-03 -8.50880168e-08\n"
       "  9.31846830e-13  6.35821408e-18  0.00000000e+00 -7.96247645e+05  1.91311273e+02\n"
       "                                                                          \n"
       "CN+  3           1800490.876                                                      \n"
       " -8.30280101e+05  8.77557203e+03 -2.97740322e+01  4.97682660e-02 -1.30219681e-05\n"
       " -2.05830943e-08  1.12683268e-11  0.00000000e+00  1.70579088e+05  2.03989171e+02\n"
       " -7.15337451e+06  1.85722746e+04 -1.08452053e+01  6.10660526e-03 -1.19119357e-06\n"
       "  1.18483369e-10 -4.79977687e-15  0.00000000e+00  9.26204124e+04  1.13532651e+02\n"
       " -1.81294631e+08  1.12880452e+05 -2.28730839e+01  3.48458573e-03 -2.20976256e-07\n"
       "  6.57976539e-12 -7.55649586e-17  0.00000000e+00 -6.78420857e+05  2.36263389e+02\n"
       "                                                                          \n"
       "CO  3            -110530.000                                                      \n"
       "  1.48902756e+04 -2.92225095e+02  5.72445841e+00 -8.17613694e-03  1.45688598e-05\n"
       " -1.08773325e-08  3.02790549e-12  0.00000000e+00 -1.30306970e+04 -7.85914715e+00\n"
       "  4.61915856e+05 -1.94468575e+03  5.91664709e+00 -5.66423407e-04  1.39880257e-07\n"
       " -1.78766498e-11  9.62085040e-16  0.00000000e+00 -2.46573844e+03 -1.38739939e+01\n"
       "  8.86855241e+08 -7.50028541e+05  2.49544449e+02 -3.95630299e-02  3.29773210e-06\n"
       " -1.31839398e-10  1.99891378e-15  0.00000000e+00  5.70135124e+06 -2.06067958e+03\n"
       "                                                                          \n"
       "CO+  3           1247790.876                                                      \n"
       " -2.17873999e+04  1.28881819e+02  3.76902289e+00 -3.43171391e-03  8.19387911e-06\n"
       " -6.46375790e-09  1.80371143e-12  0.00000000e+00  1.48234825e+05  3.99043782e+00\n"
       "  2.31681660e+05 -1.05763263e+03  4.55420231e+00  4.49546934e-04 -2.48947782e-07\n"
       "  5.26750391e-11 -3.28947110e-15  0.00000000e+00  1.55505203e+05 -3.87341085e+00\n"
       " -3.03555723e+08  2.39308392e+05 -7.03490196e+01  1.13953628e-02 -8.31506401e-07\n"
       "  2.86366814e-11 -3.80321984e-16  0.00000000e+00 -1.68859083e+06  6.29189365e+02\n"
       "                                                                          \n"
       "CO2  3           -393510.000                                                      \n"
       "  4.94378364e+04 -6.26429208e+02  5.30181336e+00  2.50360057e-03 -2.12470010e-07\n"
       " -7.69148680e-10  2.84997991e-13  0.00000000e+00 -4.52818986e+04 -7.04876965e+00\n"
       "  1.17696943e+05 -1.78880147e+03  8.29154353e+00 -9.22477831e-05  4.86963541e-09\n"
       " -1.89206384e-12  6.33067509e-16  0.00000000e+00 -3.90834501e+04 -2.65268192e+01\n"
       " -1.54440623e+09  1.01683614e+06 -2.56137710e+02  3.36936393e-02 -2.18115791e-06\n"
       "  6.99132485e-11 -8.84221214e-16  0.00000000e+00 -8.04312850e+06  2.25415326e+03\n"
       "                                                                          \n"
       "F  3             79380.000                                                        \n"
       "  1.13740909e+03 -1.45339280e+02  4.07740361e+00 -4.30336014e-03  5.72889774e-06\n"
       " -3.81931290e-09  1.01832251e-12  0.00000000e+00  9.31111012e+03 -3.55898265e+00\n"
       "  1.47350623e+04  8.14992736e+01  2.44437182e+00  2.12021003e-05 -4.54691862e-09\n"
       "  5.10952873e-13 -2.33389465e-17  0.00000000e+00  8.38837465e+03  5.47871064e+00\n"
       " -2.92672476e+07  1.77567492e+04 -1.81446326e+00  5.35120028e-04 -3.51362080e-08\n"
       "  1.10151969e-12 -1.06129384e-17  0.00000000e+00 -1.31964272e+05  4.24881456e+01\n"
       "                                                                          \n"
       "F2  2            0.000                                                            \n"
       "  1.01817754e+04  2.27422347e+01  1.97135403e+00  8.15160123e-03 -1.14895968e-05\n"
       "  7.95864947e-09 -2.16707863e-12  0.00000000e+00 -9.58693453e+02  1.13059974e+01\n"
       " -2.94116687e+06  9.45659515e+03 -7.73861346e+00  7.64471159e-03 -2.24100723e-06\n"
       "  2.91584473e-10 -1.42503371e-14  0.00000000e+00 -6.07100397e+04  8.42383313e+01\n"
       "                                                                          \n"
       "H  3             217998.828                                                       \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.54737080e+04 -4.46682853e-01\n"
       "  6.07877425e+01 -1.81935442e-01  2.50021182e+00 -1.22651286e-07  3.73287633e-11\n"
       " -5.68774456e-15  3.41021020e-19  0.00000000e+00  2.54748640e+04 -4.48191777e-01\n"
       "  2.17375769e+08 -1.31203540e+05  3.39917420e+01 -3.81399968e-03  2.43285484e-07\n"
       " -7.69427554e-12  9.64410563e-17  0.00000000e+00  1.06763809e+06 -2.74230105e+02\n"
       "                                                                          \n"
       "H+  3            1536245.928                                                      \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.84021488e+05 -1.14064664e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.84021488e+05 -1.14064664e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.84021488e+05 -1.14064664e+00\n"
       "                                                                          \n"
       "H2  3            0.000                                                            \n"
       "  4.07832281e+04 -8.00918545e+02  8.21470167e+00 -1.26971436e-02  1.75360493e-05\n"
       " -1.20286016e-08  3.36809316e-12  0.00000000e+00  2.68248438e+03 -3.04378866e+01\n"
       "  5.60812338e+05 -8.37149134e+02  2.97536304e+00  1.25224993e-03 -3.74071842e-07\n"
       "  5.93662825e-11 -3.60699573e-15  0.00000000e+00  5.33981585e+03 -2.20276405e+00\n"
       "  4.96671613e+08 -3.14744812e+05  7.98388750e+01 -8.41450419e-03  4.75306044e-07\n"
       " -1.37180973e-11  1.60537460e-16  0.00000000e+00  2.48835466e+06 -6.69552419e+02\n"
       "                                                                          \n"
       "H2+  3           1494672.430                                                      \n"
       " -3.12089221e+04  2.30462995e+02  3.33556119e+00 -2.41904915e-03  7.00601261e-06\n"
       " -5.61000425e-09  1.56416804e-12  0.00000000e+00  1.77410460e+05 -8.27833845e-01\n"
       "  1.67222618e+06 -6.59518544e+03  1.27932197e+01 -5.50934546e-03  2.03066946e-06\n"
       " -3.35102754e-10  1.94608913e-14  0.00000000e+00  2.18999958e+05 -6.79271109e+01\n"
       " -1.82206202e+08  1.01819129e+05 -1.24582075e+01  1.07663464e-03 -3.93220966e-08\n"
       "  6.28514344e-13 -2.09437896e-18  0.00000000e+00 -6.51306155e+05  1.47140561e+02\n"
       "                                                                          \n"
       "H2O  2           -241826.000                                                      \n"
       " -3.94795999e+04  5.75572977e+02  9.31783351e-01  7.22271091e-03 -7.34255448e-06\n"
       "  4.95504134e-09 -1.33693261e-12  0.00000000e+00 -3.30397425e+04  1.72420539e+01\n"
       "  1.03497224e+06 -2.41269895e+03  4.64611114e+00  2.29199814e-03 -6.83683007e-07\n"
       "  9.42646842e-11 -4.82238028e-15  0.00000000e+00 -1.38428625e+04 -7.97815119e+00\n"
       "                                                                          \n"
       "H2O2 2           -135880.000                                                     \n"
       " -9.279533580E+04  1.564748385E+03 -5.976460140E+00  3.270744520E-02 -3.932193260E-05 \n"
       "  2.509255235E-08 -6.465045290E-12  0.000000000E+00 -2.494004728E+04  5.877174180E+01 \n"
       "  1.489428027E+06 -5.170821780E+03  1.128204970E+01 -8.042397790E-05 -1.818383769E-08 \n"
       "  6.947265590E-12 -4.827831900E-16  0.000000000E+00  1.418251038E+04 -4.650855660E+01 \n"
       "                                                                          \n"
       "HCl  2           -92310.000                                                       \n"
       "  2.06258829e+04 -3.09336886e+02  5.27541885e+00 -4.82887422e-03  6.19579460e-06\n"
       " -3.04002378e-09  4.91679003e-13  0.00000000e+00 -1.06778230e+04 -7.30931775e+00\n"
       "  9.15774951e+05 -2.77055021e+03  5.97353979e+00 -3.62981006e-04  4.73552919e-08\n"
       "  2.81026205e-12 -6.65610422e-16  0.00000000e+00  5.67495805e+03 -1.64282706e+01\n"
       "                                                                          \n"
       "HCN  2           135000.000                                                       \n"
       "  9.09829783e+04 -1.23865966e+03  8.72132229e+00 -6.52828128e-03  8.87274723e-06\n"
       " -4.80890877e-09  9.31791773e-13  0.00000000e+00  2.12197899e+04 -2.74668335e+01\n"
       "  1.23689825e+06 -4.44676184e+03  9.73891163e+00 -5.85539810e-04  1.07285501e-07\n"
       " -1.01340360e-11  3.34873666e-16  0.00000000e+00  4.24459481e+04 -4.00579742e+01\n"
       "                                                                          \n"
       "He  3            0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  9.28723974e-01\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  9.28723974e-01\n"
       "  3.39684542e+06 -2.19403765e+03  3.08023188e+00 -8.06895755e-05  6.25278491e-09\n"
       " -2.57499007e-13  4.42996022e-18  0.00000000e+00  1.65051896e+04 -4.04881439e+00\n"
       "                                                                          \n"
       "He+  3           2378521.473                                                      \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.85323374e+05  1.62166556e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.85323374e+05  1.62166556e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.85323374e+05  1.62166556e+00\n"
       "                                                                          \n"
       "HO2   2           12020.000                                                        \n"
       " -7.598882540E+04  1.329383918E+03 -4.677388240E+00  2.508308202E-02 -3.006551588E-05 \n"
       "  1.895600056E-08 -4.828567390E-12  0.000000000E+00 -5.873350960E+03  5.193602140E+01 \n"
       " -1.810669724E+06  4.963192030E+03 -1.039498992E+00  4.560148530E-03 -1.061859447E-06 \n"
       "  1.144567878E-10 -4.763064160E-15  0.000000000E+00 -3.200817190E+04  4.066850920E+01 \n"
       "                                                                          \n"
       "N  3             472680.000                                                       \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  5.61046378e+04  4.19390932e+00\n"
       "  8.87650138e+04 -1.07123150e+02  2.36218829e+00  2.91672008e-04 -1.72951510e-07\n"
       "  4.01265788e-11 -2.67722757e-15  0.00000000e+00  5.69735133e+04  4.86523579e+00\n"
       "  5.47518105e+08 -3.10757498e+05  6.91678274e+01 -6.84798813e-03  3.82757240e-07\n"
       " -1.09836771e-11  1.27798602e-16  0.00000000e+00  2.55058562e+06 -5.84876971e+02\n"
       "                                                                          \n"
       "N+  3            1882127.624                                                      \n"
       "  5.23707921e+03  2.29995832e+00  2.48748882e+00  2.73749075e-05 -3.13444758e-08\n"
       "  1.85011133e-11 -4.44735098e-15  0.00000000e+00  2.25628474e+05  5.07683507e+00\n"
       "  2.90497037e+05 -8.55790861e+02  3.47738929e+00 -5.28826719e-04  1.35235031e-07\n"
       " -1.38983412e-11  5.04616628e-16  0.00000000e+00  2.31080998e+05 -1.99414226e+00\n"
       "  1.64609215e+07 -1.11316522e+04  4.97698664e+00 -2.00539358e-04  1.02248136e-08\n"
       " -2.69143086e-13  3.53993159e-18  0.00000000e+00  3.13628470e+05 -1.70664595e+01\n"
       "                                                                          \n"
       "N2  3            0.000                                                            \n"
       "  2.21037122e+04 -3.81846145e+02  6.08273815e+00 -8.53091381e-03  1.38464610e-05\n"
       " -9.62579293e-09  2.51970560e-12  0.00000000e+00  7.10845911e+02 -1.07600320e+01\n"
       "  5.87709908e+05 -2.23924255e+03  6.06694267e+00 -6.13965296e-04  1.49179819e-07\n"
       " -1.92309442e-11  1.06194871e-15  0.00000000e+00  1.28320618e+04 -1.58663484e+01\n"
       "  8.30971200e+08 -6.42048187e+05  2.02020507e+02 -3.06501961e-02  2.48685558e-06\n"
       " -9.70579208e-11  1.43751673e-15  0.00000000e+00  4.93850663e+06 -1.67204791e+03\n"
       "                                                                          \n"
       "CPN2  3  0.000                                                            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "                                                                          \n"
       "N2+  3           1509508.424                                                      \n"
       " -3.47404104e+04  2.69621543e+02  3.16491970e+00 -2.13224760e-03  6.73048636e-06\n"
       " -5.63731151e-09  1.62175773e-12  0.00000000e+00  1.79000446e+05  6.83295935e+00\n"
       " -2.84559747e+06  7.05888915e+03 -2.88488265e+00  3.06867527e-03 -4.36164780e-07\n"
       "  2.10250882e-11  5.41202519e-16  0.00000000e+00  1.34038874e+05  5.09089472e+01\n"
       " -3.71283095e+08  3.13928800e+05 -9.60351986e+01  1.57119350e-02 -1.17506567e-06\n"
       "  4.14444172e-11 -5.62189377e-16  0.00000000e+00 -2.21736248e+06  8.43627257e+02\n"
       "                                                                          \n"
       "NCO  2           131843.928                                                       \n"
       "  9.50796917e+03 -1.95732986e+02  4.23512791e+00  3.90371915e-03  3.85514012e-07\n"
       " -2.85351957e-09  1.23451381e-12  0.00000000e+00  1.55696257e+04  2.04252484e+00\n"
       "  7.39292978e+04 -1.61725838e+03  8.57491953e+00 -3.76455498e-04  7.03829586e-08\n"
       " -6.68653218e-12  2.98893417e-16  0.00000000e+00  2.28940706e+04 -2.55276588e+01\n"
       "                                                                          \n"
       "NH  3            357032.001                                                       \n"
       "  1.35965062e+04 -1.90029565e+02  4.51849625e+00 -2.43277540e-03  2.37758524e-06\n"
       " -2.59278055e-10 -2.65968566e-13  0.00000000e+00  4.28097215e+04 -3.88655464e+00\n"
       "  1.95814005e+06 -5.78285659e+03  9.33573752e+00 -2.29290818e-03  6.07608715e-07\n"
       " -6.64793603e-11  2.38423143e-15  0.00000000e+00  7.89890925e+04 -4.11696671e+01\n"
       "  9.52452031e+07 -8.58576221e+04  2.98043076e+01 -2.97954712e-03  1.65632380e-07\n"
       " -4.74475838e-12  5.57010457e-17  0.00000000e+00  6.96138236e+05 -2.22901475e+02\n"
       "                                                                          \n"
       "NH+  3           1665795.114                                                      \n"
       "  4.25377807e+03 -2.45823599e+02  6.70892578e+00 -1.03849090e-02  1.50901050e-05\n"
       " -9.58052447e-09  2.33321001e-12  0.00000000e+00  2.00108653e+05 -1.39506084e+01\n"
       "  1.40570994e+06 -4.13621679e+03  7.63201549e+00 -1.22832624e-03  2.72118887e-07\n"
       " -2.01009966e-11  3.71725697e-17  0.00000000e+00  2.25898469e+05 -2.78678557e+01\n"
       "  2.39294879e+08 -1.74166248e+05  5.10791647e+01 -5.56763349e-03  3.27339769e-07\n"
       " -9.79799764e-12  1.18654583e-16  0.00000000e+00  1.55470927e+06 -4.06597642e+02\n"
       "                                                                          \n"
       "NH2  2           189134.662                                                       \n"
       " -3.11601645e+04  4.75073546e+02  1.37457969e+00  6.29944545e-03 -5.97605729e-06\n"
       "  4.48239827e-09 -1.41043554e-12  0.00000000e+00  1.92910370e+04  1.53894335e+01\n"
       "  1.66900789e+06 -5.61038294e+03  9.97188164e+00 -1.17828134e-03  4.23396549e-07\n"
       " -6.53976978e-11  3.61987805e-15  0.00000000e+00  5.68905973e+04 -4.37935788e+01\n"
       "                                                                          \n"
       "NH3  2           -45940.000                                                       \n"
       " -7.68122642e+04  1.27095161e+03 -3.89322933e+00  2.14598848e-02 -2.18376679e-05\n"
       "  1.31738577e-08 -3.33232227e-12  0.00000000e+00 -1.26488643e+04  4.36601505e+01\n"
       "  2.45238816e+06 -8.04089084e+03  1.27134588e+01 -3.98017165e-04  3.55246584e-08\n"
       "  2.53096956e-12 -3.32272323e-16  0.00000000e+00  4.38618973e+04 -6.46232791e+01\n"
       "                                                                          \n"
       "NO  3            91269.110                                                        \n"
       " -1.14391658e+04  1.53646774e+02  3.43146865e+00 -2.66859213e-03  8.48139877e-06\n"
       " -7.68511079e-09  2.38679758e-12  0.00000000e+00  9.09794974e+03  6.72872795e+00\n"
       "  2.23903708e+05 -1.28965624e+03  5.43394039e+00 -3.65605546e-04  9.88101763e-08\n"
       " -1.41608327e-11  9.38021642e-16  0.00000000e+00  1.75029422e+04 -8.50169908e+00\n"
       " -9.57530764e+08  5.91243671e+05 -1.38456733e+02  1.69433998e-02 -1.00735146e-06\n"
       "  2.91258526e-11 -3.29511091e-16  0.00000000e+00 -4.67750329e+06  1.24208166e+03\n"
       "                                                                          \n"
       "NO+  3           990807.104                                                       \n"
       "  1.39852659e+03 -1.59049494e+02  5.12291732e+00 -6.39444005e-03  1.12392489e-05\n"
       " -7.98862419e-09  2.10739504e-12  0.00000000e+00  1.18749224e+05 -4.39855768e+00\n"
       "  6.06984843e+05 -2.27838831e+03  6.08031794e+00 -6.06681584e-04  1.43199471e-07\n"
       " -1.74798063e-11  8.93496500e-16  0.00000000e+00  1.32270602e+05 -1.51987490e+01\n"
       "  2.67640091e+09 -1.83294905e+06  5.09925021e+02 -7.11382025e-02  5.31766050e-06\n"
       " -1.96320842e-10  2.80526850e-15  0.00000000e+00  1.44330920e+07 -4.32404518e+03\n"
       "                                                                          \n"
       "NO2  2           34193.022                                                        \n"
       " -5.64204584e+04  9.63309734e+02 -2.43451851e+00  1.92776414e-02 -1.87456362e-05\n"
       "  9.14553637e-09 -1.77766146e-12  0.00000000e+00 -1.54793043e+03  4.06785541e+01\n"
       "  7.21271176e+05 -3.83253763e+03  1.11395534e+01 -2.23801440e-03  6.54762164e-07\n"
       " -7.61120803e-11  3.32829926e-15  0.00000000e+00  2.50244718e+04 -4.30507224e+01\n"
       "                                                                          \n"
       "Ne  3            0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  3.35532272e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  3.35532272e+00\n"
       " -1.23825275e+07  6.95857958e+03  1.01670929e+00  1.42466456e-04 -4.80393393e-09\n"
       " -1.17021318e-13  8.41515365e-18  0.00000000e+00 -5.66393363e+04  1.64843870e+01\n"
       "                                                                          \n"
       "O  3             249175.003                                                       \n"
       " -7.95361130e+03  1.60717779e+02  1.96622644e+00  1.01367031e-03 -1.11041542e-06\n"
       "  6.51750750e-10 -1.58477925e-13  0.00000000e+00  2.84036244e+04  8.40424182e+00\n"
       "  2.61902026e+05 -7.29872203e+02  3.31717727e+00 -4.28133436e-04  1.03610459e-07\n"
       " -9.43830433e-12  2.72503830e-16  0.00000000e+00  3.39242806e+04 -6.67958535e-01\n"
       "  1.77900426e+08 -1.08232826e+05  2.81077837e+01 -2.97523226e-03  1.85499753e-07\n"
       " -5.79623154e-12  7.19172016e-17  0.00000000e+00  8.89094263e+05 -2.18172815e+02\n"
       "                                                                          \n"
       "O+  3            1568787.228                                                      \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.87935284e+05  4.39337676e+00\n"
       " -2.16651321e+05  6.66545615e+02  1.70206436e+00  4.71499281e-04 -1.42713182e-07\n"
       "  2.01659590e-11 -9.10715776e-16  0.00000000e+00  1.83719197e+05  1.00569038e+01\n"
       " -2.14383538e+08  1.46951852e+05 -3.68086454e+01  5.03616454e-03 -3.08787385e-07\n"
       "  9.18683487e-12 -1.07416327e-16  0.00000000e+00 -9.61420896e+05  3.42619308e+02\n"
       "                                                                          \n"
       "O2  3            0.000                                                            \n"
       " -3.42556269e+04  4.84699986e+02  1.11901159e+00  4.29388743e-03 -6.83627313e-07\n"
       " -2.02337478e-09  1.03904064e-12  0.00000000e+00 -3.39145434e+03  1.84969912e+01\n"
       " -1.03793994e+06  2.34483275e+03  1.81972949e+00  1.26784887e-03 -2.18807142e-07\n"
       "  2.05372411e-11 -8.19349062e-16  0.00000000e+00 -1.68901253e+04  1.73871835e+01\n"
       "  4.97515261e+08 -2.86602339e+05  6.69015464e+01 -6.16971869e-03  3.01623757e-07\n"
       " -7.42087888e-12  7.27744063e-17  0.00000000e+00  2.29348755e+06 -5.53044968e+02\n"
       "                                                                          \n"
       "O2+  3           1171828.436                                                      \n"
       " -8.17746071e+04  1.00476232e+03 -3.36540054e-01  6.10537849e-03 -2.70414396e-06\n"
       " -3.01196202e-10  4.16272255e-13  0.00000000e+00  1.34792023e+05  2.78321591e+01\n"
       "  7.36613050e+04 -8.45858362e+02  4.98541998e+00 -1.61328191e-04  6.43445548e-08\n"
       " -1.50600823e-11  1.57904421e-15  0.00000000e+00  1.44631062e+05 -5.81278407e+00\n"
       " -1.56225883e+09  1.16148087e+06 -3.30267037e+02  4.71112832e-02 -3.35458085e-06\n"
       "  1.16800722e-10 -1.58980527e-15  0.00000000e+00 -8.85846055e+06  2.85218069e+03\n"
       "                                                                          \n"
       "OH  3            39347.106                                                        \n"
       " -1.99886366e+03  9.30014295e+01  3.05085385e+00  1.52953035e-03 -3.15789256e-06\n"
       "  3.31544734e-09 -1.13876303e-12  0.00000000e+00  3.24004397e+03  4.67411290e+00\n"
       "  1.01739349e+06 -2.50995748e+03  5.11654809e+00  1.30529875e-04 -8.28431902e-08\n"
       "  2.00647550e-11 -1.55699342e-15  0.00000000e+00  2.04452334e+04 -1.10128250e+01\n"
       "  2.84724229e+08 -1.85953704e+05  5.00825057e+01 -5.14238586e-03  2.87554326e-07\n"
       " -8.22883906e-12  9.56725603e-17  0.00000000e+00  1.46864630e+06 -4.02356407e+02\n"
       "                                                                          \n"
       "Si  3            450000.000                                                       \n"
       "  9.83614081e+01  1.54654452e+02  1.87643667e+00  1.32063800e-03 -1.52972006e-06\n"
       "  8.95056277e-10 -1.95287349e-13  0.00000000e+00  5.26351031e+04  9.69828888e+00\n"
       " -6.16929885e+05  2.24068393e+03 -4.44861932e-01  1.71005632e-03 -4.10771416e-07\n"
       "  4.55888478e-11 -1.88951535e-15  0.00000000e+00  3.95355876e+04  2.67966806e+01\n"
       " -9.28654894e+08  5.44398989e+05 -1.20673974e+02  1.35966270e-02 -7.60649866e-07\n"
       "  2.14974607e-11 -2.47411677e-16  0.00000000e+00 -4.29379212e+06  1.08638284e+03\n"
       "                                                                          \n"
       "SiO  2           -98842.860                                                       \n"
       " -4.60579335e+04  7.88008654e+02 -1.52373799e+00  1.41931317e-02 -1.66800664e-05\n"
       "  9.99331149e-09 -2.42820390e-12  0.00000000e+00 -1.65800032e+04  3.29397543e+01\n"
       " -2.29083217e+05  6.00671324e+01  4.47768446e+00 -8.55465297e-05  1.02072020e-07\n"
       " -3.23332906e-11  3.52510129e-15  0.00000000e+00 -1.41706507e+04 -7.14499047e-01\n"
       "                                                                          \n"
       "e  3             0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02 -1.17208127e+01\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02 -1.17208127e+01\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02 -1.17208127e+01\n"
       );
     std::istringstream buf(default_thermo_data);
     read_cea_mixture_data_ascii(thermo,buf);
     return;
   }
template<class NumericType > void Antioch::read_cea_thermo_data_ascii (CEAThermodynamics< NumericType > & thermo, std::istream & in) inline
Definition at line 58 of file cea_thermo_ascii_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), Antioch::CEAThermodynamics< NumericType >::add_curve_fit(), antioch_error, Antioch::CEAThermodynamics< NumericType >::check(), Antioch::CEAThermodynamics< NumericType >::chemical_mixture(), and skip_comment_lines().
Referenced by read_cea_thermo_data_ascii_default().
   {
     skip_comment_lines(in, '#');
     std::string name;
     unsigned int n_int;
     std::vector<NumericType> coeffs;
     NumericType h_form, val;
     const ChemicalMixture<NumericType>& chem_mixture = thermo.chemical_mixture();
     while (in.good())
       {
         in >> name;   // Species Name
         in >> n_int;  // Number of T intervals: [200-1000], [1000-6000], ([6000-20000])
         in >> h_form; // Formation Enthalpy @ 298.15 K
         coeffs.clear();
         for (unsigned int interval=0; interval<n_int; interval++)
           {
             for (unsigned int n=0; n<10; n++)
               {
                 in >> val, coeffs.push_back(val);
               }
           }
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             // Check if this is a species we want.
             if( chem_mixture.active_species_name_map().find(name) !=
                 chem_mixture.active_species_name_map().end() )
               {
                 thermo.add_curve_fit(name, coeffs);
               }
           }
       } // end while
     // Make sure we actually populated everything
     if( !thermo.check() )
       {
         std::cerr << "Error: CEA table not fully populated" << std::endl;
         antioch_error();
       }
     return;
   }
template<class NumericType > void Antioch::read_cea_thermo_data_ascii_default (CEAThermodynamics< NumericType > & thermo) inline
Definition at line 111 of file cea_thermo_ascii_parsing.h.
References read_cea_thermo_data_ascii().
Referenced by Antioch::CEAThermodynamics< NumericType >::CEAThermodynamics().
   {
     static const std::string
       default_thermo_data
       ("#-----------------------------------------------------------------------------\n"
       "# Cp, H, and S curve fit parameters from CEA program (1994)\n"
       "# \n"
       "# File Format:\n"
       "# \n"
       "# First line:\n"
       "# \n"
       "#        Species Name\n"
       "#        Number of T intervals: [200-1000], [1000-6000], ([6000-20000])\n"
       "#        Formation Enthalpy @ 298.15K\n"
       "# \n"
       "# Lines 2-4 (2-8):\n"
       "# \n"
       "#        a0-a4; a5-a9 for each interval.\n"
       "# \n"
       "# \n"
       "# Cp/R =  a0*T^-2   + a1*T^-1     + a2     + a3*T   + a4*T^2   + a5*T^3   + a6*T^4\n"
       "# H/RT = -a0*T^-2   + a1*T^-1*lnT + a2     + a3*T/2 + a4*T^2/3 + a5*T^3/4 + a6*T^4/5 + a8/T\n"
       "# S/R  = -a0*T^-2/2 - a1*T^-1     + a2*lnT + a3*T   + a4*T^2/2 + a5*T^3/3 + a6*T^4/4 + a9\n"
       "# \n"
       "# Note that a7 is always zero and is not used in the calculation of Cp,H, or S.\n"
       "# The constant is included simply for compatibility with cea.\n"
       "# \n"
       "# \n"
       "# Sources:\n"
       "# \n"
       "# All values come directly from cea400 program (05/98)\n"
       "# Note that for monotomics in which the only non-zero parameter is a2, cea \n"
       "# stores this value in the 1st position. This must be changed for FIN-S to \n"
       "# work correctly.\n"
       "# [PB]: HO2/H2O2 values taken from  http://www.grc.nasa.gov/WWW/CEAWeb/ceaThermoBuild.htm \n"
       "#-------------------------------------------------------------------------------\n"
       "\n"
       "Ar  3            0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  4.37967491e+00\n"
       "  2.01053848e+01 -5.99266107e-02  2.50006940e+00 -3.99214116e-08  1.20527214e-11\n"
       " -1.81901558e-15  1.07857664e-19  0.00000000e+00 -7.44993961e+02  4.37918011e+00\n"
       " -9.95126508e+08  6.45888726e+05 -1.67589470e+02  2.31993336e-02 -1.72108091e-06\n"
       "  6.53193846e-11 -9.74014773e-16  0.00000000e+00 -5.07830034e+06  1.46529848e+03\n"
       "                                                                          \n"
       "Ar+  3           1526778.407                                                      \n"
       " -5.73120917e+04  7.93079147e+02 -1.71712122e+00  1.04418402e-02 -1.18020750e-05\n"
       "  6.52813478e-09 -1.44755813e-12  0.00000000e+00  1.79057223e+05  2.94915095e+01\n"
       " -3.83596540e+05  8.16201970e+02  2.30134263e+00 -4.95298377e-06  1.20510848e-08\n"
       " -2.18505029e-12  1.26549390e-16  0.00000000e+00  1.77181146e+05  7.94750748e+00\n"
       "  1.01737284e+07 -6.68510410e+03  4.46095379e+00 -3.03416529e-04  2.62347956e-08\n"
       " -1.20511583e-12  2.30380688e-17  0.00000000e+00  2.35435354e+05 -1.04451930e+01\n"
       "                                                                          \n"
       "Air  2           -125.530                                                         \n"
       "  1.00995016e+04 -1.96827561e+02  5.00915511e+00 -5.76101373e-03  1.06685993e-05\n"
       " -7.94029797e-09  2.18523191e-12  0.00000000e+00 -1.76796731e+02 -3.92150098e+00\n"
       "  2.41521443e+05 -1.25787460e+03  5.14455867e+00 -2.13854179e-04  7.06522784e-08\n"
       " -1.07148349e-11  6.57780015e-16  0.00000000e+00  6.46226319e+03 -8.14740866e+00\n"
       "                                                                          \n"
       "CPAir  3         -125.530                                                 \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "                                                                          \n"
       "C  3             716680.000                                                       \n"
       "  6.49503147e+02 -9.64901086e-01  2.50467548e+00 -1.28144803e-05  1.98013365e-08\n"
       " -1.60614403e-11  5.31448341e-15  0.00000000e+00  8.54576311e+04  4.74799922e+00\n"
       " -1.28913647e+05  1.71952857e+02  2.64604439e+00 -3.35306895e-04  1.74209274e-07\n"
       " -2.90281783e-11  1.64218239e-15  0.00000000e+00  8.41059785e+04  4.13012235e+00\n"
       "  4.43252801e+08 -2.88601841e+05  7.73710832e+01 -9.71528189e-03  6.64959533e-07\n"
       " -2.23007878e-11  2.89938870e-16  0.00000000e+00  2.35527344e+06 -6.40512241e+02\n"
       "                                                                          \n"
       "C+  3            1809444.482                                                      \n"
       "  2.25853318e+03 -1.57454401e+00  2.50363759e+00 -5.20253954e-06  4.51647956e-09\n"
       " -2.18115104e-12  4.49430845e-16  0.00000000e+00  2.16895191e+05  4.34577527e+00\n"
       "  1.25511271e+04 -3.41187502e+01  2.54338322e+00 -2.80512097e-05  9.75164222e-09\n"
       " -1.73685542e-12  1.24619194e-16  0.00000000e+00  2.17100179e+05  4.06398843e+00\n"
       "  5.61815495e+05 -6.04705988e+03  5.88454166e+00 -7.21189472e-04  6.82348422e-08\n"
       " -2.59987863e-12  3.63386841e-17  0.00000000e+00  2.58137054e+05 -2.28001243e+01\n"
       "                                                                          \n"
       "C2  3            830457.000                                                       \n"
       "  5.55956757e+05 -9.98000622e+03  6.68153991e+01 -1.74341173e-01  2.44849356e-04\n"
       " -1.70344706e-07  4.68447130e-11  0.00000000e+00  1.44586386e+05 -3.44818817e+02\n"
       " -9.68890957e+05  3.56099020e+03 -5.06351169e-01  2.94509281e-03 -7.13928908e-07\n"
       "  8.67047006e-11 -4.07681670e-15  0.00000000e+00  7.68186000e+04  3.33990355e+01\n"
       "  6.31616742e+06  1.36534413e+04 -3.99672321e+00  1.93752303e-03 -1.58441823e-07\n"
       "  5.52076555e-12 -7.25360969e-17  0.00000000e+00  9.39290526e+03  6.61413426e+01\n"
       "                                                                          \n"
       "C2H  3           566205.472                                                       \n"
       "  7.65369105e+03 -4.18740132e+02  7.25427188e+00 -5.03701933e-03  8.23519623e-06\n"
       " -4.61676824e-09  9.50926320e-13  0.00000000e+00  6.85068967e+04 -1.58602839e+01\n"
       "  3.99586409e+06 -1.19690929e+04  1.71383304e+01 -3.33695957e-03  6.00328130e-07\n"
       " -5.49724012e-11  2.02273188e-15  0.00000000e+00  1.43142317e+05 -9.28591870e+01\n"
       "  0.              0.              7.59195493e+00  0.              0.            \n"
       "  0.              0.              0.              6.41223400e+04 -2.03895009e+01\n"
       "                                                                          \n"
       "C2H2  2  228200.000                                                       \n"
       "  1.59813325e+05 -2.21667505e+03  1.26572561e+01 -7.98017014e-03  8.05580151e-06\n"
       " -2.43394461e-09 -7.50945461e-14  0.00000000e+00  3.71263379e+04 -5.24443365e+01\n"
       "  1.71379212e+06 -5.92897095e+03  1.23611564e+01  1.31470625e-04 -1.36286904e-07\n"
       "  2.71274606e-11 -1.30208685e-15  0.00000000e+00  6.26648973e+04 -5.81886602e+01\n"
       "                                                                          \n"
       "C3  3            839948.500                                                       \n"
       " -4.35456285e+04  6.66010414e+02  1.45101513e+00  7.43442531e-03 -3.81010954e-06\n"
       " -2.33675605e-11  4.40699631e-13  0.00000000e+00  9.63517401e+04  2.02514928e+01\n"
       "  4.50804398e+06 -1.46101600e+04  2.28194701e+01 -8.54423692e-03  2.14604329e-06\n"
       " -2.10384214e-10  6.35151106e-15  0.00000000e+00  1.91196492e+05 -1.27185429e+02\n"
       "  5.62195627e+08 -4.80014820e+05  1.48773604e+02 -1.86380758e-02  1.25369345e-06\n"
       " -4.23152054e-11  5.69651073e-16  0.00000000e+00  3.77769020e+06 -1.22634937e+03\n"
       "                                                                          \n"
       "CF  2            242300.000                                                       \n"
       " -4.85659087e+04  8.37066845e+02 -1.58605380e+00  1.37329926e-02 -1.54543720e-05\n"
       "  8.89879494e-09 -2.08319768e-12  0.00000000e+00  2.41920950e+04  3.37110765e+01\n"
       " -7.30301173e+04 -3.10432552e+02  4.68755965e+00 -1.75388618e-05  1.17998295e-08\n"
       " -1.88283316e-12  1.89811962e-16  0.00000000e+00  2.93490294e+04 -2.32175022e+00\n"
       "                                                                          \n"
       "CF2  2            -186600.00                                                      \n"
       " -4.28469549e+04  9.42241347e+02 -3.83847378e+00  2.84787584e-02 -3.61855678e-05\n"
       "  2.30750321e-08 -5.91498489e-12  0.00000000e+00 -2.77993759e+04  4.66760006e+01\n"
       " -1.98592186e+06  4.47486108e+03  2.05367791e+00  2.54212017e-03 -6.46636536e-07\n"
       "  7.98822582e-11 -3.82452258e-15  0.00000000e+00 -5.43485110e+04  2.28899734e+01\n"
       "                                                                          \n"
       "CF3  2           -467400.000                                                      \n"
       " -2.89509314e+04  7.08259104e+02 -3.49874496e+00  3.60052779e-02 -4.51845638e-05\n"
       "  2.83046097e-08 -7.12428016e-12  0.00000000e+00 -6.05579954e+04  4.50043769e+01\n"
       " -3.00992537e+05 -1.04577415e+03  1.07783067e+01 -3.11222805e-04  6.88233084e-08\n"
       " -7.90018181e-12  3.66510631e-16  0.00000000e+00 -5.42636700e+04 -3.41619073e+01\n"
       "                                                                          \n"
       "CF4  2           -933500.000                                                      \n"
       "  9.81534964e+03  1.16366074e+02 -1.28852758e+00  3.95962388e-02 -4.99633605e-05\n"
       "  3.12541430e-08 -7.84194211e-12  0.00000000e+00 -1.13896083e+05  2.93876064e+01\n"
       " -4.16418379e+05 -1.41489926e+03  1.40513863e+01 -4.19996407e-04  9.28167764e-08\n"
       " -1.06499640e-11  4.93955439e-16  0.00000000e+00 -1.09514188e+05 -5.48720115e+01\n"
       "                                                                          \n"
       "CH  3            597338.000                                                       \n"
       "  2.22056413e+04 -3.40537175e+02  5.53138641e+00 -5.79489639e-03  7.96946173e-06\n"
       " -4.46585989e-09  9.59622884e-13  0.00000000e+00  7.24039052e+04 -9.10756700e+00\n"
       "  2.06073377e+06 -5.39612964e+03  7.85618794e+00 -7.96575798e-04  1.76427377e-07\n"
       " -1.97634586e-11  5.03028668e-16  0.00000000e+00  1.06219245e+05 -3.15471110e+01\n"
       " -8.06826755e+08  4.57539322e+05 -9.84385128e+01  1.23522859e-02 -8.48550223e-07\n"
       "  3.04037261e-11 -4.40026028e-16  0.00000000e+00 -3.59580957e+06  8.95336505e+02\n"
       "                                                                          \n"
       "CH2  2           388800.000                                                       \n"
       "  3.52591418e+04 -3.36765436e+02  4.50893691e+00  2.52106603e-03 -5.31151087e-06\n"
       "  6.65421308e-09 -2.61007296e-12  0.00000000e+00  4.73772550e+04 -3.80734012e+00\n"
       "  2.51041594e+06 -7.95393239e+03  1.23882957e+01 -1.77590968e-03  3.21740029e-07\n"
       " -3.06886344e-11  1.20490060e-15  0.00000000e+00  9.60102856e+04 -6.15597799e+01\n"
       "                                                                          \n"
       "CH3  2           146900.000                                                       \n"
       " -2.87728611e+04  5.09505607e+02  1.99073056e-01  1.36396516e-02 -1.43455892e-05\n"
       "  1.01396738e-08 -3.02843889e-12  0.00000000e+00  1.41109873e+04  2.02339462e+01\n"
       "  2.76090427e+06 -9.33655279e+03  1.48769863e+01 -1.43922769e-03  2.44392393e-07\n"
       " -2.22384579e-11  8.39158849e-16  0.00000000e+00  7.48476479e+04 -7.91948334e+01\n"
       "                                                                          \n"
       "CH4  2           -74600.000                                                       \n"
       " -1.76654573e+05  2.78547782e+03 -1.20193547e+01  3.91462588e-02 -3.61165608e-05\n"
       "  2.01838794e-08 -4.95577215e-12  0.00000000e+00 -2.33101156e+04  8.90108100e+01\n"
       "  3.74626570e+06 -1.38885134e+04  2.05402982e+01 -1.94419693e-03  4.32387145e-07\n"
       " -4.06101278e-11  1.64315927e-15  0.00000000e+00  7.56598868e+04 -1.22297711e+02\n"
       "                                                                          \n"
       "Cl  3             121301.000                                                      \n"
       "  2.27621585e+04 -2.16841329e+02  2.74518512e+00  2.45110169e-03 -5.45801199e-06\n"
       "  4.41798688e-09 -1.28813400e-12  0.00000000e+00  1.50135707e+04  3.10295076e+00\n"
       " -1.69793293e+05  6.08172646e+02  2.12866409e+00  1.30736703e-04 -2.64488360e-08\n"
       "  2.84250478e-12 -1.25291173e-16  0.00000000e+00  9.93438740e+03  8.84475941e+00\n"
       " -7.13968707e+07  4.49993633e+04 -9.26431535e+00  1.65743796e-03 -1.32621940e-07\n"
       "  5.53399887e-12 -8.39030188e-17  0.00000000e+00 -3.40533303e+05  1.06911130e+02\n"
       "                                                                          \n"
       "Cl2  2            0.000                                                           \n"
       "  3.46281724e+04 -5.54712949e+02  6.20759103e+00 -2.98963673e-03  3.17303416e-06\n"
       " -1.79363467e-09  4.26005863e-13  0.00000000e+00  1.53407075e+03 -9.43835303e+00\n"
       "  6.09256675e+06 -1.94962688e+04  2.85453491e+01 -1.44996828e-02  4.46388943e-06\n"
       " -6.35852403e-10  3.32735931e-14  0.00000000e+00  1.21211722e+05 -1.69077832e+02\n"
       "                                                                          \n"
       "CN  3            438683.448                                                       \n"
       "  3.94910175e+03 -1.39157387e+02  4.93077604e+00 -6.30459473e-03  1.25682136e-05\n"
       " -9.87818175e-09  2.84310304e-12  0.00000000e+00  5.22845470e+04 -2.76308000e+00\n"
       " -2.22797608e+06  5.04066445e+03 -2.12179448e-01  1.35488122e-03  1.32592277e-07\n"
       " -6.93693400e-11  5.49489162e-15  0.00000000e+00  1.78454233e+04  3.28251898e+01\n"
       " -1.79477307e+08  1.05433143e+05 -1.72959888e+01  2.19486383e-03 -8.50880168e-08\n"
       "  9.31846830e-13  6.35821408e-18  0.00000000e+00 -7.96247645e+05  1.91311273e+02\n"
       "                                                                          \n"
       "CN+  3           1800490.876                                                      \n"
       " -8.30280101e+05  8.77557203e+03 -2.97740322e+01  4.97682660e-02 -1.30219681e-05\n"
       " -2.05830943e-08  1.12683268e-11  0.00000000e+00  1.70579088e+05  2.03989171e+02\n"
       " -7.15337451e+06  1.85722746e+04 -1.08452053e+01  6.10660526e-03 -1.19119357e-06\n"
       "  1.18483369e-10 -4.79977687e-15  0.00000000e+00  9.26204124e+04  1.13532651e+02\n"
       " -1.81294631e+08  1.12880452e+05 -2.28730839e+01  3.48458573e-03 -2.20976256e-07\n"
       "  6.57976539e-12 -7.55649586e-17  0.00000000e+00 -6.78420857e+05  2.36263389e+02\n"
       "                                                                          \n"
       "CO  3            -110530.000                                                      \n"
       "  1.48902756e+04 -2.92225095e+02  5.72445841e+00 -8.17613694e-03  1.45688598e-05\n"
       " -1.08773325e-08  3.02790549e-12  0.00000000e+00 -1.30306970e+04 -7.85914715e+00\n"
       "  4.61915856e+05 -1.94468575e+03  5.91664709e+00 -5.66423407e-04  1.39880257e-07\n"
       " -1.78766498e-11  9.62085040e-16  0.00000000e+00 -2.46573844e+03 -1.38739939e+01\n"
       "  8.86855241e+08 -7.50028541e+05  2.49544449e+02 -3.95630299e-02  3.29773210e-06\n"
       " -1.31839398e-10  1.99891378e-15  0.00000000e+00  5.70135124e+06 -2.06067958e+03\n"
       "                                                                          \n"
       "CO+  3           1247790.876                                                      \n"
       " -2.17873999e+04  1.28881819e+02  3.76902289e+00 -3.43171391e-03  8.19387911e-06\n"
       " -6.46375790e-09  1.80371143e-12  0.00000000e+00  1.48234825e+05  3.99043782e+00\n"
       "  2.31681660e+05 -1.05763263e+03  4.55420231e+00  4.49546934e-04 -2.48947782e-07\n"
       "  5.26750391e-11 -3.28947110e-15  0.00000000e+00  1.55505203e+05 -3.87341085e+00\n"
       " -3.03555723e+08  2.39308392e+05 -7.03490196e+01  1.13953628e-02 -8.31506401e-07\n"
       "  2.86366814e-11 -3.80321984e-16  0.00000000e+00 -1.68859083e+06  6.29189365e+02\n"
       "                                                                          \n"
       "CO2  3           -393510.000                                                      \n"
       "  4.94378364e+04 -6.26429208e+02  5.30181336e+00  2.50360057e-03 -2.12470010e-07\n"
       " -7.69148680e-10  2.84997991e-13  0.00000000e+00 -4.52818986e+04 -7.04876965e+00\n"
       "  1.17696943e+05 -1.78880147e+03  8.29154353e+00 -9.22477831e-05  4.86963541e-09\n"
       " -1.89206384e-12  6.33067509e-16  0.00000000e+00 -3.90834501e+04 -2.65268192e+01\n"
       " -1.54440623e+09  1.01683614e+06 -2.56137710e+02  3.36936393e-02 -2.18115791e-06\n"
       "  6.99132485e-11 -8.84221214e-16  0.00000000e+00 -8.04312850e+06  2.25415326e+03\n"
       "                                                                          \n"
       "F  3             79380.000                                                        \n"
       "  1.13740909e+03 -1.45339280e+02  4.07740361e+00 -4.30336014e-03  5.72889774e-06\n"
       " -3.81931290e-09  1.01832251e-12  0.00000000e+00  9.31111012e+03 -3.55898265e+00\n"
       "  1.47350623e+04  8.14992736e+01  2.44437182e+00  2.12021003e-05 -4.54691862e-09\n"
       "  5.10952873e-13 -2.33389465e-17  0.00000000e+00  8.38837465e+03  5.47871064e+00\n"
       " -2.92672476e+07  1.77567492e+04 -1.81446326e+00  5.35120028e-04 -3.51362080e-08\n"
       "  1.10151969e-12 -1.06129384e-17  0.00000000e+00 -1.31964272e+05  4.24881456e+01\n"
       "                                                                          \n"
       "F2  2            0.000                                                            \n"
       "  1.01817754e+04  2.27422347e+01  1.97135403e+00  8.15160123e-03 -1.14895968e-05\n"
       "  7.95864947e-09 -2.16707863e-12  0.00000000e+00 -9.58693453e+02  1.13059974e+01\n"
       " -2.94116687e+06  9.45659515e+03 -7.73861346e+00  7.64471159e-03 -2.24100723e-06\n"
       "  2.91584473e-10 -1.42503371e-14  0.00000000e+00 -6.07100397e+04  8.42383313e+01\n"
       "                                                                          \n"
       "H  3             217998.828                                                       \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.54737080e+04 -4.46682853e-01\n"
       "  6.07877425e+01 -1.81935442e-01  2.50021182e+00 -1.22651286e-07  3.73287633e-11\n"
       " -5.68774456e-15  3.41021020e-19  0.00000000e+00  2.54748640e+04 -4.48191777e-01\n"
       "  2.17375769e+08 -1.31203540e+05  3.39917420e+01 -3.81399968e-03  2.43285484e-07\n"
       " -7.69427554e-12  9.64410563e-17  0.00000000e+00  1.06763809e+06 -2.74230105e+02\n"
       "                                                                          \n"
       "H+  3            1536245.928                                                      \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.84021488e+05 -1.14064664e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.84021488e+05 -1.14064664e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.84021488e+05 -1.14064664e+00\n"
       "                                                                          \n"
       "H2  3            0.000                                                            \n"
       "  4.07832281e+04 -8.00918545e+02  8.21470167e+00 -1.26971436e-02  1.75360493e-05\n"
       " -1.20286016e-08  3.36809316e-12  0.00000000e+00  2.68248438e+03 -3.04378866e+01\n"
       "  5.60812338e+05 -8.37149134e+02  2.97536304e+00  1.25224993e-03 -3.74071842e-07\n"
       "  5.93662825e-11 -3.60699573e-15  0.00000000e+00  5.33981585e+03 -2.20276405e+00\n"
       "  4.96671613e+08 -3.14744812e+05  7.98388750e+01 -8.41450419e-03  4.75306044e-07\n"
       " -1.37180973e-11  1.60537460e-16  0.00000000e+00  2.48835466e+06 -6.69552419e+02\n"
       "                                                                          \n"
       "H2+  3           1494672.430                                                      \n"
       " -3.12089221e+04  2.30462995e+02  3.33556119e+00 -2.41904915e-03  7.00601261e-06\n"
       " -5.61000425e-09  1.56416804e-12  0.00000000e+00  1.77410460e+05 -8.27833845e-01\n"
       "  1.67222618e+06 -6.59518544e+03  1.27932197e+01 -5.50934546e-03  2.03066946e-06\n"
       " -3.35102754e-10  1.94608913e-14  0.00000000e+00  2.18999958e+05 -6.79271109e+01\n"
       " -1.82206202e+08  1.01819129e+05 -1.24582075e+01  1.07663464e-03 -3.93220966e-08\n"
       "  6.28514344e-13 -2.09437896e-18  0.00000000e+00 -6.51306155e+05  1.47140561e+02\n"
       "                                                                          \n"
       "H2O  2           -241826.000                                                      \n"
       " -3.94795999e+04  5.75572977e+02  9.31783351e-01  7.22271091e-03 -7.34255448e-06\n"
       "  4.95504134e-09 -1.33693261e-12  0.00000000e+00 -3.30397425e+04  1.72420539e+01\n"
       "  1.03497224e+06 -2.41269895e+03  4.64611114e+00  2.29199814e-03 -6.83683007e-07\n"
       "  9.42646842e-11 -4.82238028e-15  0.00000000e+00 -1.38428625e+04 -7.97815119e+00\n"
       "                                                                          \n"
       "H2O2 2           -135880.000                                                     \n"
       " -9.279533580E+04  1.564748385E+03 -5.976460140E+00  3.270744520E-02 -3.932193260E-05 \n"
       "  2.509255235E-08 -6.465045290E-12  0.000000000E+00 -2.494004728E+04  5.877174180E+01 \n"
       "  1.489428027E+06 -5.170821780E+03  1.128204970E+01 -8.042397790E-05 -1.818383769E-08 \n"
       "  6.947265590E-12 -4.827831900E-16  0.000000000E+00  1.418251038E+04 -4.650855660E+01 \n"
       "                                                                          \n"
       "HCl  2           -92310.000                                                       \n"
       "  2.06258829e+04 -3.09336886e+02  5.27541885e+00 -4.82887422e-03  6.19579460e-06\n"
       " -3.04002378e-09  4.91679003e-13  0.00000000e+00 -1.06778230e+04 -7.30931775e+00\n"
       "  9.15774951e+05 -2.77055021e+03  5.97353979e+00 -3.62981006e-04  4.73552919e-08\n"
       "  2.81026205e-12 -6.65610422e-16  0.00000000e+00  5.67495805e+03 -1.64282706e+01\n"
       "                                                                          \n"
       "HCN  2           135000.000                                                       \n"
       "  9.09829783e+04 -1.23865966e+03  8.72132229e+00 -6.52828128e-03  8.87274723e-06\n"
       " -4.80890877e-09  9.31791773e-13  0.00000000e+00  2.12197899e+04 -2.74668335e+01\n"
       "  1.23689825e+06 -4.44676184e+03  9.73891163e+00 -5.85539810e-04  1.07285501e-07\n"
       " -1.01340360e-11  3.34873666e-16  0.00000000e+00  4.24459481e+04 -4.00579742e+01\n"
       "                                                                          \n"
       "He  3            0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  9.28723974e-01\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  9.28723974e-01\n"
       "  3.39684542e+06 -2.19403765e+03  3.08023188e+00 -8.06895755e-05  6.25278491e-09\n"
       " -2.57499007e-13  4.42996022e-18  0.00000000e+00  1.65051896e+04 -4.04881439e+00\n"
       "                                                                          \n"
       "He+  3           2378521.473                                                      \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.85323374e+05  1.62166556e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.85323374e+05  1.62166556e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  2.85323374e+05  1.62166556e+00\n"
       "                                                                          \n"
       "HO2   2           12020.000                                                        \n"
       " -7.598882540E+04  1.329383918E+03 -4.677388240E+00  2.508308202E-02 -3.006551588E-05 \n"
       "  1.895600056E-08 -4.828567390E-12  0.000000000E+00 -5.873350960E+03  5.193602140E+01 \n"
       " -1.810669724E+06  4.963192030E+03 -1.039498992E+00  4.560148530E-03 -1.061859447E-06 \n"
       "  1.144567878E-10 -4.763064160E-15  0.000000000E+00 -3.200817190E+04  4.066850920E+01 \n"
       "                                                                          \n"
       "N  3             472680.000                                                       \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  5.61046378e+04  4.19390932e+00\n"
       "  8.87650138e+04 -1.07123150e+02  2.36218829e+00  2.91672008e-04 -1.72951510e-07\n"
       "  4.01265788e-11 -2.67722757e-15  0.00000000e+00  5.69735133e+04  4.86523579e+00\n"
       "  5.47518105e+08 -3.10757498e+05  6.91678274e+01 -6.84798813e-03  3.82757240e-07\n"
       " -1.09836771e-11  1.27798602e-16  0.00000000e+00  2.55058562e+06 -5.84876971e+02\n"
       "                                                                          \n"
       "N+  3            1882127.624                                                      \n"
       "  5.23707921e+03  2.29995832e+00  2.48748882e+00  2.73749075e-05 -3.13444758e-08\n"
       "  1.85011133e-11 -4.44735098e-15  0.00000000e+00  2.25628474e+05  5.07683507e+00\n"
       "  2.90497037e+05 -8.55790861e+02  3.47738929e+00 -5.28826719e-04  1.35235031e-07\n"
       " -1.38983412e-11  5.04616628e-16  0.00000000e+00  2.31080998e+05 -1.99414226e+00\n"
       "  1.64609215e+07 -1.11316522e+04  4.97698664e+00 -2.00539358e-04  1.02248136e-08\n"
       " -2.69143086e-13  3.53993159e-18  0.00000000e+00  3.13628470e+05 -1.70664595e+01\n"
       "                                                                          \n"
       "N2  3            0.000                                                            \n"
       "  2.21037122e+04 -3.81846145e+02  6.08273815e+00 -8.53091381e-03  1.38464610e-05\n"
       " -9.62579293e-09  2.51970560e-12  0.00000000e+00  7.10845911e+02 -1.07600320e+01\n"
       "  5.87709908e+05 -2.23924255e+03  6.06694267e+00 -6.13965296e-04  1.49179819e-07\n"
       " -1.92309442e-11  1.06194871e-15  0.00000000e+00  1.28320618e+04 -1.58663484e+01\n"
       "  8.30971200e+08 -6.42048187e+05  2.02020507e+02 -3.06501961e-02  2.48685558e-06\n"
       " -9.70579208e-11  1.43751673e-15  0.00000000e+00  4.93850663e+06 -1.67204791e+03\n"
       "                                                                          \n"
       "CPN2  3  0.000                                                            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "  0.              0.              3.5             0.              0.            \n"
       "  0.              0.              0.              0.              0.            \n"
       "                                                                          \n"
       "N2+  3           1509508.424                                                      \n"
       " -3.47404104e+04  2.69621543e+02  3.16491970e+00 -2.13224760e-03  6.73048636e-06\n"
       " -5.63731151e-09  1.62175773e-12  0.00000000e+00  1.79000446e+05  6.83295935e+00\n"
       " -2.84559747e+06  7.05888915e+03 -2.88488265e+00  3.06867527e-03 -4.36164780e-07\n"
       "  2.10250882e-11  5.41202519e-16  0.00000000e+00  1.34038874e+05  5.09089472e+01\n"
       " -3.71283095e+08  3.13928800e+05 -9.60351986e+01  1.57119350e-02 -1.17506567e-06\n"
       "  4.14444172e-11 -5.62189377e-16  0.00000000e+00 -2.21736248e+06  8.43627257e+02\n"
       "                                                                          \n"
       "NCO  2           131843.928                                                       \n"
       "  9.50796917e+03 -1.95732986e+02  4.23512791e+00  3.90371915e-03  3.85514012e-07\n"
       " -2.85351957e-09  1.23451381e-12  0.00000000e+00  1.55696257e+04  2.04252484e+00\n"
       "  7.39292978e+04 -1.61725838e+03  8.57491953e+00 -3.76455498e-04  7.03829586e-08\n"
       " -6.68653218e-12  2.98893417e-16  0.00000000e+00  2.28940706e+04 -2.55276588e+01\n"
       "                                                                          \n"
       "NH  3            357032.001                                                       \n"
       "  1.35965062e+04 -1.90029565e+02  4.51849625e+00 -2.43277540e-03  2.37758524e-06\n"
       " -2.59278055e-10 -2.65968566e-13  0.00000000e+00  4.28097215e+04 -3.88655464e+00\n"
       "  1.95814005e+06 -5.78285659e+03  9.33573752e+00 -2.29290818e-03  6.07608715e-07\n"
       " -6.64793603e-11  2.38423143e-15  0.00000000e+00  7.89890925e+04 -4.11696671e+01\n"
       "  9.52452031e+07 -8.58576221e+04  2.98043076e+01 -2.97954712e-03  1.65632380e-07\n"
       " -4.74475838e-12  5.57010457e-17  0.00000000e+00  6.96138236e+05 -2.22901475e+02\n"
       "                                                                          \n"
       "NH+  3           1665795.114                                                      \n"
       "  4.25377807e+03 -2.45823599e+02  6.70892578e+00 -1.03849090e-02  1.50901050e-05\n"
       " -9.58052447e-09  2.33321001e-12  0.00000000e+00  2.00108653e+05 -1.39506084e+01\n"
       "  1.40570994e+06 -4.13621679e+03  7.63201549e+00 -1.22832624e-03  2.72118887e-07\n"
       " -2.01009966e-11  3.71725697e-17  0.00000000e+00  2.25898469e+05 -2.78678557e+01\n"
       "  2.39294879e+08 -1.74166248e+05  5.10791647e+01 -5.56763349e-03  3.27339769e-07\n"
       " -9.79799764e-12  1.18654583e-16  0.00000000e+00  1.55470927e+06 -4.06597642e+02\n"
       "                                                                          \n"
       "NH2  2           189134.662                                                       \n"
       " -3.11601645e+04  4.75073546e+02  1.37457969e+00  6.29944545e-03 -5.97605729e-06\n"
       "  4.48239827e-09 -1.41043554e-12  0.00000000e+00  1.92910370e+04  1.53894335e+01\n"
       "  1.66900789e+06 -5.61038294e+03  9.97188164e+00 -1.17828134e-03  4.23396549e-07\n"
       " -6.53976978e-11  3.61987805e-15  0.00000000e+00  5.68905973e+04 -4.37935788e+01\n"
       "                                                                          \n"
       "NH3  2           -45940.000                                                       \n"
       " -7.68122642e+04  1.27095161e+03 -3.89322933e+00  2.14598848e-02 -2.18376679e-05\n"
       "  1.31738577e-08 -3.33232227e-12  0.00000000e+00 -1.26488643e+04  4.36601505e+01\n"
       "  2.45238816e+06 -8.04089084e+03  1.27134588e+01 -3.98017165e-04  3.55246584e-08\n"
       "  2.53096956e-12 -3.32272323e-16  0.00000000e+00  4.38618973e+04 -6.46232791e+01\n"
       "                                                                          \n"
       "NO  3            91269.110                                                        \n"
       " -1.14391658e+04  1.53646774e+02  3.43146865e+00 -2.66859213e-03  8.48139877e-06\n"
       " -7.68511079e-09  2.38679758e-12  0.00000000e+00  9.09794974e+03  6.72872795e+00\n"
       "  2.23903708e+05 -1.28965624e+03  5.43394039e+00 -3.65605546e-04  9.88101763e-08\n"
       " -1.41608327e-11  9.38021642e-16  0.00000000e+00  1.75029422e+04 -8.50169908e+00\n"
       " -9.57530764e+08  5.91243671e+05 -1.38456733e+02  1.69433998e-02 -1.00735146e-06\n"
       "  2.91258526e-11 -3.29511091e-16  0.00000000e+00 -4.67750329e+06  1.24208166e+03\n"
       "                                                                          \n"
       "NO+  3           990807.104                                                       \n"
       "  1.39852659e+03 -1.59049494e+02  5.12291732e+00 -6.39444005e-03  1.12392489e-05\n"
       " -7.98862419e-09  2.10739504e-12  0.00000000e+00  1.18749224e+05 -4.39855768e+00\n"
       "  6.06984843e+05 -2.27838831e+03  6.08031794e+00 -6.06681584e-04  1.43199471e-07\n"
       " -1.74798063e-11  8.93496500e-16  0.00000000e+00  1.32270602e+05 -1.51987490e+01\n"
       "  2.67640091e+09 -1.83294905e+06  5.09925021e+02 -7.11382025e-02  5.31766050e-06\n"
       " -1.96320842e-10  2.80526850e-15  0.00000000e+00  1.44330920e+07 -4.32404518e+03\n"
       "                                                                          \n"
       "NO2  2           34193.022                                                        \n"
       " -5.64204584e+04  9.63309734e+02 -2.43451851e+00  1.92776414e-02 -1.87456362e-05\n"
       "  9.14553637e-09 -1.77766146e-12  0.00000000e+00 -1.54793043e+03  4.06785541e+01\n"
       "  7.21271176e+05 -3.83253763e+03  1.11395534e+01 -2.23801440e-03  6.54762164e-07\n"
       " -7.61120803e-11  3.32829926e-15  0.00000000e+00  2.50244718e+04 -4.30507224e+01\n"
       "                                                                          \n"
       "Ne  3            0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  3.35532272e+00\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02  3.35532272e+00\n"
       " -1.23825275e+07  6.95857958e+03  1.01670929e+00  1.42466456e-04 -4.80393393e-09\n"
       " -1.17021318e-13  8.41515365e-18  0.00000000e+00 -5.66393363e+04  1.64843870e+01\n"
       "                                                                          \n"
       "O  3             249175.003                                                       \n"
       " -7.95361130e+03  1.60717779e+02  1.96622644e+00  1.01367031e-03 -1.11041542e-06\n"
       "  6.51750750e-10 -1.58477925e-13  0.00000000e+00  2.84036244e+04  8.40424182e+00\n"
       "  2.61902026e+05 -7.29872203e+02  3.31717727e+00 -4.28133436e-04  1.03610459e-07\n"
       " -9.43830433e-12  2.72503830e-16  0.00000000e+00  3.39242806e+04 -6.67958535e-01\n"
       "  1.77900426e+08 -1.08232826e+05  2.81077837e+01 -2.97523226e-03  1.85499753e-07\n"
       " -5.79623154e-12  7.19172016e-17  0.00000000e+00  8.89094263e+05 -2.18172815e+02\n"
       "                                                                          \n"
       "O+  3            1568787.228                                                      \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.87935284e+05  4.39337676e+00\n"
       " -2.16651321e+05  6.66545615e+02  1.70206436e+00  4.71499281e-04 -1.42713182e-07\n"
       "  2.01659590e-11 -9.10715776e-16  0.00000000e+00  1.83719197e+05  1.00569038e+01\n"
       " -2.14383538e+08  1.46951852e+05 -3.68086454e+01  5.03616454e-03 -3.08787385e-07\n"
       "  9.18683487e-12 -1.07416327e-16  0.00000000e+00 -9.61420896e+05  3.42619308e+02\n"
       "                                                                          \n"
       "O2  3            0.000                                                            \n"
       " -3.42556269e+04  4.84699986e+02  1.11901159e+00  4.29388743e-03 -6.83627313e-07\n"
       " -2.02337478e-09  1.03904064e-12  0.00000000e+00 -3.39145434e+03  1.84969912e+01\n"
       " -1.03793994e+06  2.34483275e+03  1.81972949e+00  1.26784887e-03 -2.18807142e-07\n"
       "  2.05372411e-11 -8.19349062e-16  0.00000000e+00 -1.68901253e+04  1.73871835e+01\n"
       "  4.97515261e+08 -2.86602339e+05  6.69015464e+01 -6.16971869e-03  3.01623757e-07\n"
       " -7.42087888e-12  7.27744063e-17  0.00000000e+00  2.29348755e+06 -5.53044968e+02\n"
       "                                                                          \n"
       "O2+  3           1171828.436                                                      \n"
       " -8.17746071e+04  1.00476232e+03 -3.36540054e-01  6.10537849e-03 -2.70414396e-06\n"
       " -3.01196202e-10  4.16272255e-13  0.00000000e+00  1.34792023e+05  2.78321591e+01\n"
       "  7.36613050e+04 -8.45858362e+02  4.98541998e+00 -1.61328191e-04  6.43445548e-08\n"
       " -1.50600823e-11  1.57904421e-15  0.00000000e+00  1.44631062e+05 -5.81278407e+00\n"
       " -1.56225883e+09  1.16148087e+06 -3.30267037e+02  4.71112832e-02 -3.35458085e-06\n"
       "  1.16800722e-10 -1.58980527e-15  0.00000000e+00 -8.85846055e+06  2.85218069e+03\n"
       "                                                                          \n"
       "OH  3            39347.106                                                        \n"
       " -1.99886366e+03  9.30014295e+01  3.05085385e+00  1.52953035e-03 -3.15789256e-06\n"
       "  3.31544734e-09 -1.13876303e-12  0.00000000e+00  3.24004397e+03  4.67411290e+00\n"
       "  1.01739349e+06 -2.50995748e+03  5.11654809e+00  1.30529875e-04 -8.28431902e-08\n"
       "  2.00647550e-11 -1.55699342e-15  0.00000000e+00  2.04452334e+04 -1.10128250e+01\n"
       "  2.84724229e+08 -1.85953704e+05  5.00825057e+01 -5.14238586e-03  2.87554326e-07\n"
       " -8.22883906e-12  9.56725603e-17  0.00000000e+00  1.46864630e+06 -4.02356407e+02\n"
       "                                                                          \n"
       "Si  3            450000.000                                                       \n"
       "  9.83614081e+01  1.54654452e+02  1.87643667e+00  1.32063800e-03 -1.52972006e-06\n"
       "  8.95056277e-10 -1.95287349e-13  0.00000000e+00  5.26351031e+04  9.69828888e+00\n"
       " -6.16929885e+05  2.24068393e+03 -4.44861932e-01  1.71005632e-03 -4.10771416e-07\n"
       "  4.55888478e-11 -1.88951535e-15  0.00000000e+00  3.95355876e+04  2.67966806e+01\n"
       " -9.28654894e+08  5.44398989e+05 -1.20673974e+02  1.35966270e-02 -7.60649866e-07\n"
       "  2.14974607e-11 -2.47411677e-16  0.00000000e+00 -4.29379212e+06  1.08638284e+03\n"
       "                                                                          \n"
       "SiO  2           -98842.860                                                       \n"
       " -4.60579335e+04  7.88008654e+02 -1.52373799e+00  1.41931317e-02 -1.66800664e-05\n"
       "  9.99331149e-09 -2.42820390e-12  0.00000000e+00 -1.65800032e+04  3.29397543e+01\n"
       " -2.29083217e+05  6.00671324e+01  4.47768446e+00 -8.55465297e-05  1.02072020e-07\n"
       " -3.23332906e-11  3.52510129e-15  0.00000000e+00 -1.41706507e+04 -7.14499047e-01\n"
       "                                                                          \n"
       "e  3             0.000                                                            \n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02 -1.17208127e+01\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02 -1.17208127e+01\n"
       "  0.00000000e+00  0.00000000e+00  2.50000000e+00  0.00000000e+00  0.00000000e+00\n"
       "  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.45375000e+02 -1.17208127e+01\n"
       );
     std::istringstream buf(default_thermo_data);
     read_cea_thermo_data_ascii(thermo,buf);
     return;
   }
template<class NumericType > void Antioch::read_reaction_set_data_xml (const std::string & filename, const bool verbose, ReactionSet< NumericType > & reaction_set) inline
Definition at line 59 of file read_reaction_set_data_xml.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), Antioch::Reaction< CoeffType >::add_forward_rate(), Antioch::Reaction< CoeffType >::add_product(), Antioch::Reaction< CoeffType >::add_reactant(), Antioch::ReactionSet< CoeffType >::add_reaction(), antioch_assert_equal_to, antioch_deprecated, antioch_error, antioch_not_implemented, Antioch::KineticsModel::ARRHENIUS, tinyxml2::XMLElement::Attribute(), Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::ReactionSet< CoeffType >::chemical_mixture(), Antioch::ReactionType::DUPLICATE, Antioch::ReactionType::ELEMENTARY, tinyxml2::XMLDocument::ErrorID(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLDocument::GetErrorStr1(), tinyxml2::XMLDocument::GetErrorStr2(), tinyxml2::XMLElement::GetText(), Antioch::KineticsModel::HERCOURT_ESSEN, tinyxml2::XMLElement::IntAttribute(), Antioch::KineticsModel::KOOIJ, Antioch::ReactionType::LINDEMANN_FALLOFF, tinyxml2::XMLDocument::LoadFile(), Antioch::Reaction< CoeffType >::n_rate_constants(), Antioch::ChemicalMixture< CoeffType >::n_species(), tinyxml2::XMLNode::NextSiblingElement(), Antioch::Reaction< CoeffType >::set_efficiency(), split_string_double_on_colon(), split_string_int_on_colon(), SplitString(), Antioch::Reaction< CoeffType >::swap_forward_rates(), Antioch::ReactionType::THREE_BODY, Antioch::ReactionType::TROE_FALLOFF, Antioch::Reaction< CoeffType >::type(), and Antioch::KineticsModel::VANTHOFF.
   {
     tinyxml2::XMLDocument doc;
     if(doc.LoadFile(filename.c_str()))
       {
         std::cerr << "ERROR: unable to load xml file " << filename << std::endl;
         std::cerr << "Error of tinyxml2 library:\n"
                   << "\tID = " << doc.ErrorID() << "\n"
                   << "\tError String1 = " << doc.GetErrorStr1() << "\n"
                   << "\tError String2 = " << doc.GetErrorStr2() << std::endl;
         antioch_error();
       }
     tinyxml2::XMLElement* element = doc.FirstChildElement("ctml");
     if (!element)
       {
         std::cerr << "ERROR:  no <ctml> tag found in file " << filename
                   << std::endl;
         antioch_error();
       }
     const ChemicalMixture<NumericType>& chem_mixture = reaction_set.chemical_mixture();
     unsigned int n_species = chem_mixture.n_species();
     // Sanity Check on species
     /*
       tinyxml2::XMLElement* species = element->FirstChildElement("phase");
       species = species->FirstChildElement("speciesArray");
       std::vector<std::string> species_names;
       std::cout << species->GetText() << std::endl;
       SplitString(std::string(species->GetText()),
       " ",
       species_names,
       false);
       if( n_species != species_names.size() )
       {
       std::cerr << "Error: Mismatch in n_species and the number of species specified in" << std::endl
       << "       the kinetics XML file " << filename << std::endl
       << "       Found species: " << species->GetText() << std::endl;
       antioch_error();
       }
     */
     // Now read in reaction data
     element = element->FirstChildElement("reactionData");
     if (!element) return;
     tinyxml2::XMLElement* reaction = element->FirstChildElement("reaction");
     std::map<std::string,KineticsModel::KineticsModel> kin_keyword;
     kin_keyword["HercourtEssen"]          = KineticsModel::HERCOURT_ESSEN;
     kin_keyword["Berthelot"]              = KineticsModel::BERTHELOT;
     kin_keyword["Arrhenius"]              = KineticsModel::ARRHENIUS;
     kin_keyword["BerthelotHercourtEssen"] = KineticsModel::BHE;
     kin_keyword["Kooij"]                  = KineticsModel::KOOIJ;
     kin_keyword["ModifiedArrhenius"]      = KineticsModel::KOOIJ;  //for Arrhenius fans
     kin_keyword["VantHoff"]               = KineticsModel::VANTHOFF;
     std::vector<std::string> models;
     models.push_back("HercourtEssen");
     models.push_back("Berthelot");
     models.push_back("Arrhenius");
     models.push_back("BerthelotHercourtEssen");
     models.push_back("Kooij");
     models.push_back("ModifiedArrhenius");
     models.push_back("VantHoff");
     std::map<std::string,ReactionType::ReactionType> proc_keyword;
     proc_keyword["Elementary"]        = ReactionType::ELEMENTARY;
     proc_keyword["Duplicate"]         = ReactionType::DUPLICATE;
     proc_keyword["ThreeBody"]         = ReactionType::THREE_BODY;
     proc_keyword["LindemannFalloff"]  = ReactionType::LINDEMANN_FALLOFF;
     proc_keyword["TroeFalloff"]       = ReactionType::TROE_FALLOFF;
     while (reaction)
       {
         if (verbose) std::cout << "Reaction #" << reaction->IntAttribute("id") << ":\n"
                                << " eqn: " << reaction->FirstChildElement("equation")->GetText()
                                << std::endl;
         ReactionType::ReactionType typeReaction(ReactionType::ELEMENTARY);
         KineticsModel::KineticsModel kineticsModel(KineticsModel::HERCOURT_ESSEN); // = 0
         if (reaction->Attribute("type"))
           {
             if (verbose) std::cout << " type: " << reaction->Attribute("type") << std::endl;
             if(!proc_keyword.count(reaction->Attribute("type")))
             {
                 std::cerr << "Implemented chemical processes are:\n"
                           << "  Elementary (default)\n"
                           << "  Duplicate\n"
                           << "  ThreeBody\n"
                           << "  LindemannFalloff\n"
                           << "  TroeFalloff\n"
                           << "See Antioch documentation for more details."
                           << std::endl;
                 antioch_not_implemented();
             }
             typeReaction = proc_keyword[reaction->Attribute("type")];
           }
         // construct a Reaction object
         Reaction<NumericType>* my_rxn = build_reaction<NumericType>(n_species, reaction->FirstChildElement("equation")->GetText(),typeReaction,kineticsModel);
         unsigned int imod(0);
         tinyxml2::XMLElement* rate_constant = reaction->FirstChildElement("rateCoeff")->FirstChildElement(models[imod].c_str());
         while(!rate_constant)
         {
           if(imod == models.size() - 1)
           {
                 std::cerr << "Could not find a suitable kinetics model.\n"
                           << "Implemented kinetics models are:\n"
                           << "  HercourtEssen\n"
                           << "  Berthelot\n"
                           << "  Arrhenius\n"
                           << "  BerthelotHercourtEssen\n"
                           << "  Kooij (default)\n"
                           << "  ModifiedArrhenius (= Kooij)\n"
                           << "  VantHoff\n"
                           << "See Antioch documentation for more details."
                           << std::endl;
                 antioch_not_implemented();
           }
           imod++;
           rate_constant = reaction->FirstChildElement("rateCoeff")->FirstChildElement(models[imod].c_str());
         }
         kineticsModel = kin_keyword[models[imod]];
         while(rate_constant) //for duplicate and falloff models, several kinetics rate to load, no mixing allowed
         {
           // usually Kooij is called Arrhenius, check here
           if(kineticsModel == KineticsModel::ARRHENIUS && rate_constant->FirstChildElement("b") != NULL)
           {
             if(std::atof(rate_constant->FirstChildElement("b")->GetText()) != 0.)
             {
                kineticsModel = KineticsModel::KOOIJ;
                antioch_deprecated();
                std::cerr << "An equation of the form \"A * (T/Tref)^beta * exp(-Ea/(R*T))\" is a Kooij equation,\n"
                          << "I guess a modified Arrhenius could be a name too.  Whatever, the correct label is\n"
                          << "\"Kooij\", or, <<  la limite >> \"ModifiedArrhenius\".  Please use those terms instead,\n"
                          << "thanks and a good day to you, user." << std::endl;
             }
           }
           if(verbose)
             {
               std::cout << " rate: " << models[imod] << " model\n"
                         << "   A: " << rate_constant->FirstChildElement("A")->GetText() << "\n"; //always
               if(rate_constant->FirstChildElement("b") != NULL)
               {
                   std::cout << "   b: " << rate_constant->FirstChildElement("b")->GetText() << "\n";
               }
               if(rate_constant->FirstChildElement("E") != NULL)
               {
                   std::cout << "   E: " << rate_constant->FirstChildElement("E")->GetText() << "\n";
               }
               if(rate_constant->FirstChildElement("D") != NULL)
               {
                   std::cout << "   D: " << rate_constant->FirstChildElement("D")->GetText() << "\n";
               }
             }
           // typically Cantera files list activation energy in cal/mol, but we want it in K.
           std::vector<NumericType> data;
           data.push_back(std::atof(rate_constant->FirstChildElement("A")->GetText()));
           if(rate_constant->FirstChildElement("b") != NULL)
           {
              data.push_back(std::atof(rate_constant->FirstChildElement("b")->GetText()));
           }
           if(data.back() == 0.)//if ARRHENIUS parameterized as KOOIJ
           {
              data.pop_back();
           }
           if(rate_constant->FirstChildElement("E") != NULL)
           {
              data.push_back(std::atof(rate_constant->FirstChildElement("E")->GetText()));
           }
           if(rate_constant->FirstChildElement("D") != NULL)
           {
              data.push_back(std::atof(rate_constant->FirstChildElement("D")->GetText()));
           }
           //Tref
           if(kineticsModel == KineticsModel::HERCOURT_ESSEN ||
              kineticsModel == KineticsModel::BHE            ||
              kineticsModel == KineticsModel::KOOIJ          ||
              kineticsModel == KineticsModel::VANTHOFF)
           {
             data.push_back(1.);
             if(rate_constant->FirstChildElement("Tref"))
             {
                 data.back() = std::atof(rate_constant->FirstChildElement("Tref")->GetText());
             }
           }
           //scale E -> E/R
           if(kineticsModel == KineticsModel::ARRHENIUS ||
              kineticsModel == KineticsModel::KOOIJ     ||
              kineticsModel == KineticsModel::VANTHOFF)
           {
             data.push_back(Constants::R_universal<NumericType>()/1000.L);
             if( rate_constant->FirstChildElement("E")->Attribute("units"))//if there's the attribute
               {
               if( std::string(rate_constant->FirstChildElement("E")->Attribute("units")) == "cal/mol" )
                 {
                   data.back() = 1.9858775L;
                 }
               }
           }
           KineticsType<NumericType>* rate = build_rate<NumericType>(data,kineticsModel);
           my_rxn->add_forward_rate(rate);
           rate_constant = rate_constant->NextSiblingElement(models[imod].c_str());
         } //end of duplicate/falloff kinetics description loop
         // for falloff, we need a way to know which rate constant is the low pressure limit
         // and which is the high pressure limit
         // usually by calling the low pressure limite "k0". If nothing given, by default
         // the first rate constant encountered is the low limit,
         // so we need to change something only if the second rate constant has a "name" attribute
         // of value "k0"
         if(typeReaction == ReactionType::LINDEMANN_FALLOFF ||
            typeReaction == ReactionType::TROE_FALLOFF)
         {
            antioch_assert_equal_to(my_rxn->n_rate_constants(),2);
            rate_constant = reaction->FirstChildElement("rateCoeff")->FirstChildElement(models[imod].c_str())->NextSiblingElement(models[imod].c_str());
            if(rate_constant->Attribute("name")) //if attribute exists
            {
              if(std::string(rate_constant->Attribute("name")) == "k0") //and is indeed k0
              {
                my_rxn->swap_forward_rates(0,1);
              }
            }
         }
         tinyxml2::XMLElement *efficiencies =
           reaction->FirstChildElement("rateCoeff")->FirstChildElement("efficiencies");
         //efficiencies are only for three body reactions
         if(efficiencies)
           {
             if(efficiencies->GetText())
               {
                 antioch_assert_equal_to (ReactionType::THREE_BODY, my_rxn->type());
                 if(verbose) std::cout << "   efficiencies: " << efficiencies->GetText();
                 std::vector<std::string> efficiency_pairs;
                 SplitString( std::string(efficiencies->GetText()),
                              " ",
                              efficiency_pairs,
                              /* include_empties = */ false );
                 for(unsigned int p = 0; p < efficiency_pairs.size(); p++)
                   {
                     std::pair<std::string, double> pair(split_string_double_on_colon (efficiency_pairs[p]));
                     if(verbose)
                       {
                         std::cout  << "\n    " << efficiency_pairs[p]
                                    << " " << pair.first << " " << pair.second;
                       }
                     if(pair.first == "e-") pair.first = "e";
                     // it is possible that the efficiency is specified for a species we are not
                     // modeling - so only add the efficiency if it is included in our list
                     if( chem_mixture.active_species_name_map().count( pair.first ) )
                       {
                         my_rxn->set_efficiency( pair.first,
                                                chem_mixture.active_species_name_map().find( pair.first )->second,
                                                pair.second );
                       }
                   }
               }
           }
         //F parameters only for Troe falloff
         tinyxml2::XMLElement *troe =
           reaction->FirstChildElement("rateCoeff")->FirstChildElement("Troe");
         if(troe)
         {
 std::cout << "0" << std::endl;
            antioch_assert_equal_to (ReactionType::TROE_FALLOFF, my_rxn->type());
            FalloffReaction<NumericType,TroeFalloff<NumericType> > *my_fall_rxn =
                 static_cast<FalloffReaction<NumericType,TroeFalloff<NumericType> > *> (my_rxn);
            if(!troe->FirstChildElement("alpha"))
            {
                 std::cerr << "alpha parameter of Troe falloff missing!" << std::endl;
                 antioch_error();
            }
            my_fall_rxn->F().set_alpha(std::atof(troe->FirstChildElement("alpha")->GetText()));
            if(!troe->FirstChildElement("T3"))
            {
                 std::cerr << "T*** parameter of Troe falloff missing!" << std::endl;
                 antioch_error();
            }
            my_fall_rxn->F().set_T3(std::atof(troe->FirstChildElement("T3")->GetText()));
            if(!troe->FirstChildElement("T1"))
            {
                 std::cerr << "T* parameter of Troe falloff missing!" << std::endl;
                 antioch_error();
            }
            my_fall_rxn->F().set_T1(std::atof(troe->FirstChildElement("T1")->GetText()));
            if(troe->FirstChildElement("T2"))//T2 is optional
            {
              my_fall_rxn->F().set_T2(std::atof(troe->FirstChildElement("T2")->GetText()));
            }
         }
         tinyxml2::XMLElement* reactants = reaction->FirstChildElement("reactants");
         tinyxml2::XMLElement* products  = reaction->FirstChildElement("products");
         // We will add the reaction, unless we do not have a
         // reactant or product
         bool relevant_reaction = true;
         if(reactants->GetText())
           {
             if (verbose) std::cout << "\n   reactants: " << reactants->GetText();
             std::vector<std::string> reactant_pairs;
             // Split the reactant string on whitespace. If no entries were found,
             // there is no whitespace - and assume then only one reactant is listed.
             if( !SplitString(std::string(reactants->GetText()),
                              " ",
                              reactant_pairs,
                              /* include_empties = */ false)     )
               {
                 reactant_pairs.push_back(reactants->GetText());
               }
             for( unsigned int p=0; p < reactant_pairs.size(); p++ )
               {
                 std::pair<std::string,int> pair( split_string_int_on_colon(reactant_pairs[p]) );
                 if(pair.first == "e-") pair.first = "e";
                 if(verbose) std::cout  << "\n    " << reactant_pairs[p] << " " << pair.first << " " << pair.second;
                 if( !chem_mixture.active_species_name_map().count( pair.first ) )
                   {
                     relevant_reaction = false;
                     if (verbose) std::cout << "\n     -> skipping this reaction (no reactant " << pair.first << ")";
                   }
                 else
                   {
                     my_rxn->add_reactant( pair.first,
                                          chem_mixture.active_species_name_map().find( pair.first )->second,
                                          pair.second );
                   }
               }
           }
         if(products->GetText())
           {
             if(verbose) std::cout << "\n   products: " << products->GetText();
             std::vector<std::string> product_pairs;
             // Split the product string on whitespace. If no entries were found,
             // there is no whitespace - and assume then only one product is listed.
             if( !SplitString( std::string(products->GetText()),
                               " ",
                               product_pairs,
                               /* include_empties = */ false )     )
               {
                 product_pairs.push_back(products->GetText());
               }
             for (unsigned int p=0; p<product_pairs.size(); p++)
               {
                 std::pair<std::string, int> pair(split_string_int_on_colon (product_pairs[p]));
                 if(pair.first == "e-") pair.first = "e";
                 if(verbose) std::cout  << "\n    " << product_pairs[p] << " " << pair.first << " " << pair.second;
                 if( !chem_mixture.active_species_name_map().count( pair.first ) )
                   {
                     relevant_reaction = false;
                     if (verbose) std::cout << "\n     -> skipping this reaction (no product " << pair.first << ")";
                   }
                 else
                   {
                     my_rxn->add_product( pair.first,
                                         chem_mixture.active_species_name_map().find( pair.first )->second,
                                         pair.second );
                   }
               }
           }
         if(verbose) std::cout << "\n\n";
         if(relevant_reaction)
           reaction_set.add_reaction(my_rxn);
         // Go to the next reaction
         reaction = reaction->NextSiblingElement("reaction");
       }
     return;
   }
template<class NumericType > void Antioch::read_species_data_ascii (ChemicalMixture< NumericType > & chem_mixture, std::istream & in) inline
Definition at line 59 of file species_ascii_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::add_species(), antioch_error, skip_comment_lines(), Antioch::ChemicalMixture< CoeffType >::species_list(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
Referenced by read_species_data_ascii_default().
   {
     skip_comment_lines(in, '#');
     std::string name;
     NumericType mol_wght, h_form, n_tr_dofs;
     int charge;
     while (in.good())
       {
         in >> name;      // Species Name
         in >> mol_wght;  // molecular weight (kg/kmol)
         in >> h_form;    // heat of formation at Ok (J/kg)
         in >> n_tr_dofs; // number of translational/rotational DOFs
         in >> charge;    // charge number
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             // If we do not have an enum for this species, that is going to cause
             // problems down the line.
             if (!chem_mixture.species_name_map().count(name))
               {
                 std::cerr << "ERROR: Unexpected species " << name
                           << " encountered while parsing thermodynamic table!"
                           << std::endl;
                 antioch_error();
               }
             /* Only add a ChemicalSpecies if the user supplied it to
                the ChemicalMixture. */
             Species species = chem_mixture.species_name_map().find(name)->second;
             // using default comparison:
             std::vector<Species>::const_iterator it = std::search_n( chem_mixture.species_list().begin(),
                                                                      chem_mixture.species_list().end(),
                                                                      1, species);
             if( it != chem_mixture.species_list().end() )
               {
                 unsigned int index = static_cast<unsigned int>(it - chem_mixture.species_list().begin());
                 chem_mixture.add_species( index, name, mol_wght, h_form, n_tr_dofs, charge );
               }
           }
       }
     return;
   }
template<class NumericType > void Antioch::read_species_data_ascii_default (ChemicalMixture< NumericType > & chem_mixture) inline
Default species data. Includes molecular weights, heats of formation (J/kg), nominal translational/rotational degrees of freedom (cv=c_tr*R*T where c_tr=5/2 for diatomics and c_tr=3/2 for atoms, and charge number.) Originally taken from FIN-S.
Default species data. Includes molecular weights, heats of formation (J/kg), nominal translational/rotational degrees of freedom (cv=c_tr*R*T where c_tr=5/2 for diatomics and c_tr=3/2 for atoms, and charge number.) Originally taken from FIN-S.
Definition at line 113 of file species_ascii_parsing.h.
References read_species_data_ascii().
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
   {
     static const std::string
       default_species_chem_data
       ("#===========================================================================\n"
        "# LEGEND\n"
        "#===========================================================================\n"
        "#\n"
        "#    Species    -- Species name\n"
        "#    Mol. Wt.   -- Molecular weight (kg/kmol)\n"
        "#    Hform      -- Formation enthalpy (J/kg @ 0K)\n"
        "#    cfs        -- Nominal T-R Degrees of freedom (cv = cfs*k*T)\n"
        "#    zns        -- Charge number\n"
        "#\n"
        "#[PB]: I'm unsure about the cfs for HO2 and H2O2."
        "#    Spec.     Mol. Wt.     Hform (0K),  cfs,   zns\n"
        "\n"
        "Air     28.96000          0.000000000000        2.5      0\n"
        "CPAir   28.96000          0.000000000000        2.5      0\n"
        "Ar      39.94400          0.000000000000        1.5      0\n"
        "Ar+     39.94345          3.8068120000e7        1.5      1\n"
        "C       12.01100          5.9211889000e7        1.5      0\n"
        "C+      12.01045          1.4967366000e8        1.5      1\n"
        "C2      24.02200          3.4234785000e7        2.5      0\n"
        "C2H     25.03000          2.2572910000e7        2.5      0\n"
        "C2H2    26.03800          8.7548580000e6        2.5      0\n"
        "C3      36.03300          2.3062193000e7        2.5      0\n"
        "CF      31.00940          9.9617550000e6        2.5      0\n"
        "CF2     50.00780         -2.5187600000e6        3.0      0\n"
        "CF3     69.00620         -7.1992350000e6        3.0      0\n"
        "CF4     88.00460         -1.0258770000e7        3.0      0\n"
        "CH      13.01900          4.5627850000e7        2.5      0\n"
        "CH2     14.02700          2.7803520000e7        3.0      0\n"
        "CH3     15.03500          9.9559030000e6        3.0      0\n"
        "CH4     16.04300         -4.1532130000e6        3.0      0\n"
        "Cl      35.45300          3.3740400000e6        1.5      0\n"
        "Cl2     70.90600          0.000000000000        2.5      0\n"
        "CN      26.01900          1.6795420000e7        2.5      0\n"
        "CN+     26.01845          6.8835800000e7        2.5      1\n"
        "CO      28.01100         -4.0630824000e6        2.5      0\n"
        "CO+     28.01045          4.4200904000e7        2.5      1\n"
        "CO2     44.01100         -8.9328800000e6        2.5      0\n"
        "F       18.99840          4.0423050000e6        1.5      0\n"
        "F2      37.99680          0.000000000000        2.5      0\n"
        "H        1.00800          2.1432040000e8        1.5      0\n"
        "H+       1.00745          1.5167840000e9        1.5      1\n"
        "H2       2.01600          0.000000000000        2.5      0\n"
        "H2+      2.01545          7.3847530000e8        2.5      1\n"
        "H2O     18.01600         -1.3261710000e7        3.0      0\n"
        "H2O2    34.01475         -3.8186669018e6        3.0      0\n"
        "HCl     36.46100         -2.5266800000e6        2.5      0\n"
        "HCN     27.02700          4.8982130000e6        2.5      0\n"
        "He       4.00300          0.000000000000        1.5      0\n"
        "He+      4.00245          5.9271800000e8        1.5      1\n"
        "HO2     33.00681          4.5239149133e5        3.0      0\n"
        "N       14.00800          3.3621610000e7        1.5      0\n"
        "Ne      20.17900          0.000000000000        1.5      0\n"
        "N+      14.00745          1.3400000000e8        1.5      1\n"
        "N2      28.01600          0.000000000000        2.5      0\n"
        "CPN2    28.01600          0.000000000000        2.5      0\n"
        "N2+     28.01545          5.3700000000e7        2.5      1\n"
        "NCO     42.01900          4.2124000000e6        2.5      0\n"
        "NH      15.01600          2.3867900000e7        2.5      0\n"
        "NH+     15.01545          1.1050000000e8        2.5      1\n"
        "NH2     16.02400          1.2036000000e7        3.0      0\n"
        "NH3     17.03200         -2.2866370000e6        3.0      0\n"
        "NO      30.00800          2.9961230000e6        2.5      0\n"
        "NO+     30.00745          3.2834800000e7        2.5      1\n"
        "NO2     46.00800          8.0420800000e5        3.0      0\n"
        "O       16.00000          1.5420000000e7        1.5      0\n"
        "O+      15.99945          9.7560000000e7        1.5      1\n"
        "O2      32.00000          0.000000000000        2.5      0\n"
        "O2+     31.99945          3.6370000000e7        2.5      1\n"
        "OH      17.00800          2.2995060000e6        2.5      0\n"
        "Si      28.08550          1.5868220000e7        1.5      0\n"
        "SiO     44.08550         -2.2683200000e6        2.5      0\n"
        "e        0.00055          0.000000000000        1.5     -1\n");
     std::istringstream buf(default_species_chem_data);
     read_species_data_ascii(chem_mixture,buf);
     return;
   }
template<class NumericType > void Antioch::read_species_electronic_data_ascii (ChemicalMixture< NumericType > & chem_mixture, std::istream & in) inline
Definition at line 390 of file species_ascii_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), Antioch::ChemicalMixture< CoeffType >::add_species_electronic_data(), antioch_assert_equal_to, antioch_error, Antioch::ChemicalMixture< CoeffType >::chemical_species(), skip_comment_lines(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
Referenced by read_species_electronic_data_ascii_default().
   {
     // skip the header
     skip_comment_lines(in, '#');
     std::string name;
     NumericType theta_e;
     unsigned int n_degeneracies;
     while (in.good())
       {
         in >> name;           // Species Name
         in >> theta_e;        // characteristic electronic temperature (K)
         in >> n_degeneracies; // number of degeneracies for this level
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             // If we do not have an enum for this species, that is going to cause
             // problems down the line.
             if (!chem_mixture.species_name_map().count(name))
               {
                 std::cerr << "ERROR: Unexpected species " << name
                           << " encountered while parsing thermodynamic table!"
                           << std::endl;
                 antioch_error();
               }
             // If this species is not part of the existing mixture, we
             // don't care about it, so just continue silently.
             if (!chem_mixture.active_species_name_map().count(name))
               {
                 continue;
               }
             // ... otherwise we add the data
             const unsigned int s =
               chem_mixture.active_species_name_map().find(name)->second;
             antioch_assert_equal_to((chem_mixture.chemical_species()[s])->species(), name);
             chem_mixture.add_species_electronic_data(s, theta_e, n_degeneracies);
           }
       }
   }
template<class NumericType > void Antioch::read_species_electronic_data_ascii_default (ChemicalMixture< NumericType > & chem_mixture) inline
Definition at line 443 of file species_ascii_parsing.h.
References read_species_electronic_data_ascii().
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
   {
     static const std::string
       default_species_elec_data
       ("#===========================================================================\n"
        "# LEGEND\n"
        "#===========================================================================\n"
        "# Thetae        -- Characteristic electronic temperature (K)\n"
        "# edg           -- Degeneracy of the electronic mode\n"
        "# #elevels      -- Total number of electronic levels\n"
        "#\n"
        "# Species     ThetaE     edg  #elevels\n"
        "\n"
        "Ar        0.00000e+00   1\n"
        "Ar        1.61114e+05   9\n"
        "Ar        1.62583e+05  21\n"
        "Ar        1.63613e+05   7\n"
        "Ar        1.64233e+05   3\n"
        "Ar        1.64943e+05   5\n"
        "Ar        1.65352e+05  15\n"
        "\n"
        "Ar+       0.00000e+00   4\n"
        "Ar+       2.05980e+03   2\n"
        "\n"
        "C        0.00000e+00   1\n"
        "C        2.35959e+01   3\n"
        "C        6.24428e+01   5\n"
        "C        1.46649e+04   5\n"
        "C        3.11466e+04   1\n"
        "C        4.85374e+04   5\n"
        "C        9.22094e+04  15\n"
        "C        1.08275e+05   9\n"
        "C        1.40824e+05   5\n"
        "C        1.52221e+05   3\n"
        "C        1.72477e+05   3\n"
        "\n"
        "C+       0.00000e+00   2\n"
        "C+       9.12471e+01   4\n"
        "C+       6.19188e+04  12\n"
        "C+       1.07809e+05  10\n"
        "C+       1.38833e+05   2\n"
        "C+       1.59203e+05   6\n"
        "\n"
        "C2       0.00000e+00   1\n"
        "C2       1.03045e+03   6\n"
        "C2       9.25747e+03   1\n"
        "C2       1.20732e+04   2\n"
        "C2       1.32762e+04   3\n"
        "C2       2.18406e+04   2\n"
        "C2       2.69626e+04   1\n"
        "C2       2.88079e+04   6\n"
        "C2       3.23724e+04  10\n"
        "C2       4.38467e+04   5\n"
        "C2       4.92952e+04   2\n"
        "C2       5.01773e+04   6\n"
        "C2       5.06089e+04   1\n"
        "C2       5.51051e+04   6\n"
        "C2       5.66374e+04   2\n"
        "C2       5.86972e+04   6\n"
        "C2       5.89898e+04   6\n"
        "C2       6.12918e+04   6\n"
        "C2       6.20112e+04   2\n"
        "C2       6.22123e+04   1\n"
        "C2       6.25148e+04   1\n"
        "C2       6.43852e+04   3\n"
        "C2       7.46005e+04   6\n"
        "C2       7.60393e+04   1\n"
        "C2       7.91828e+04   1\n"
        "C2       7.97081e+04   2\n"
        "C2       9.07867e+04   2\n"
        "\n"
        "CH        0.00000e+00   4\n"
        "CH        7.62590e+03   4\n"
        "CH        3.48250e+04   6\n"
        "\n"
        "Cl       0.00000e+00   4\n"
        "Cl       1.26952e+03   2\n"
        "Cl2      0.00000e+00   1\n"
        "Cl2      2.56574e+04   6\n"
        "\n"
        "CN       0.00000e+00   2\n"
        "CN       1.32943e+04   4\n"
        "CN       3.70513e+04   2\n"
        "CN       4.66163e+04   4\n"
        "CN       6.18673e+04   8\n"
        "CN       6.86296e+04   8\n"
        "CN       7.74061e+04   4\n"
        "CN       7.83931e+04   4\n"
        "CN       8.51053e+04   2\n"
        "CN       8.64639e+04   4\n"
        "CN       8.79882e+04   4\n"
        "CN       8.97796e+04   4\n"
        "CN       9.16500e+04   4\n"
        "CN       9.24039e+04   4\n"
        "CN       9.26571e+04   2\n"
        "CN       9.99949e+04   8\n"
        "CN       1.01002e+05   2\n"
        "CN       1.01721e+05   4\n"
        "\n"
        "CN+       0.00000e+00   1\n"
        "CN+       2.87770e+03   6\n"
        "CN+       1.19620e+04   2\n"
        "CN+       1.72660e+04   6\n"
        "\n"
        "CO       0.00000e+00   1\n"
        "CO       7.00493e+04   6\n"
        "CO       8.03206e+04   3\n"
        "CO       8.79436e+04   6\n"
        "CO       9.24129e+04   3\n"
        "CO       9.36438e+04   2\n"
        "CO       9.36418e+04   1\n"
        "CO       9.48556e+04   2\n"
        "\n"
        "CO+      0.00000e+00   2\n"
        "CO+      2.98303e+04   4\n"
        "CO+      6.60063e+04   2\n"
        "\n"
        "F         0.00000e+00   4\n"
        "F         5.81430e+02   2\n"
        "\n"
        "N         0.00000e+00   4\n"
        "N         2.76647e+04  10\n"
        "N         4.14931e+04   6\n"
        "\n"
        "N+        0.00000e+00   1\n"
        "N+        7.00684e+01   3\n"
        "N+        1.88192e+02   5\n"
        "N+        2.20366e+04   5\n"
        "N+        4.70318e+04   1\n"
        "N+        6.73125e+04   5\n"
        "N+        1.32719e+05  15\n"
        "\n"
        "N2       0.00000e+00   1\n"
        "N2       7.22316e+04   3\n"
        "N2       8.57786e+04   6\n"
        "N2       8.60503e+04   6\n"
        "N2       9.53512e+04   3\n"
        "N2       9.80564e+04   1\n"
        "N2       9.96827e+04   2\n"
        "N2       1.04898e+05   2\n"
        "N2       1.11649e+05   5\n"
        "N2       1.22584e+05   1\n"
        "N2       1.24886e+05   6\n"
        "N2       1.28248e+05   6\n"
        "N2       1.33806e+05  10\n"
        "N2       1.40430e+05   6\n"
        "N2       1.50496e+05   6\n"
        "\n"
        "N2+      0.00000e+00   2\n"
        "N2+      1.31900e+04   4\n"
        "N2+      3.66332e+04   2\n"
        "N2+      3.66888e+04   4\n"
        "N2+      5.98530e+04   8\n"
        "N2+      6.61837e+04   8\n"
        "N2+      7.59899e+04   4\n"
        "N2+      7.62551e+04   4\n"
        "N2+      8.20102e+04   4\n"
        "N2+      8.41683e+04   4\n"
        "N2+      8.63265e+04   8\n"
        "N2+      8.92041e+04   8\n"
        "N2+      9.20816e+04   4\n"
        "N2+      9.22255e+04   4\n"
        "N2+      9.29377e+04   2\n"
        "N2+      9.63979e+04   2\n"
        "N2+      1.03592e+05   4\n"
        "\n"
        "NH        0.00000e+00   3\n"
        "NH        1.80950e+04   2\n"
        "NH        3.04990e+04   1\n"
        "NH        4.28870e+04   6\n"
        "\n"
        "NH+       0.00000e+00   4\n"
        "NH+       8.02880e+02   4\n"
        "NH+       3.30360e+04   6\n"
        "\n"
        "NO       0.00000e+00   4\n"
        "NO       5.46735e+04   8\n"
        "NO       6.31714e+04   2\n"
        "NO       6.59945e+04   4\n"
        "NO       6.90612e+04   4\n"
        "NO       7.05000e+04   4\n"
        "NO       7.49106e+04   4\n"
        "NO       7.62888e+04   2\n"
        "NO       8.67619e+04   4\n"
        "NO       8.71443e+04   2\n"
        "NO       8.88608e+04   4\n"
        "NO       8.98176e+04   4\n"
        "NO       8.98845e+04   2\n"
        "NO       9.04270e+04   2\n"
        "NO       9.06428e+04   2\n"
        "NO       9.11176e+04   4\n"
        "\n"
        "NO+      0.00000e+00   1\n"
        "NO+      7.50897e+04   3\n"
        "NO+      8.52546e+04   6\n"
        "NO+      8.90357e+04   6\n"
        "NO+      9.74698e+04   3\n"
        "NO+      1.00055e+05   1\n"
        "NO+      1.02803e+05   2\n"
        "NO+      1.05714e+05   2\n"
        "\n"
        "O         0.00000e+00   5\n"
        "O         2.27708e+02   3\n"
        "O         3.26569e+02   1\n"
        "O         2.28303e+04   5\n"
        "O         4.86199e+04   1\n"
        "\n"
        "O+        0.00000e+00   4\n"
        "O+        3.85833e+04  10\n"
        "O+        5.82235e+04   6\n"
        "\n"
        "O2        0.00000e+00   3\n"
        "O2        1.13916e+04   2\n"
        "O2        1.89847e+04   1\n"
        "O2        4.75597e+04   1\n"
        "O2        4.99124e+04   6\n"
        "O2        5.09227e+04   3\n"
        "O2        7.18986e+04   3\n"
        "\n"
        "O2+       0.00000e+00   4\n"
        "O2+       4.73544e+04   8\n"
        "O2+       5.83740e+04   4\n"
        "O2+       5.84143e+04   6\n"
        "O2+       6.22990e+04   4\n"
        "O2+       6.73347e+04   2\n"
        "O2+       7.12194e+04   4\n"
        "O2+       7.65428e+04   4\n"
        "O2+       8.81969e+04   4\n"
        "O2+       8.89163e+04   4\n"
        "O2+       9.42398e+04   8\n"
        "O2+       9.49592e+04   4\n"
        "O2+       9.59203e+04   2\n"
        "O2+       9.98510e+04   2\n"
        "O2+       1.03592e+05   4\n"
        "\n"
        "OH        0.00000e+00   4\n"
        "OH        4.70280e+04   2\n"
        "\n"
        "Si        0.00000e+00   1\n"
        "Si        1.10940e+02   3\n"
        "Si        3.21090e+02   5\n"
        "Si        9.06300e+03   5\n"
        "Si        2.21500e+04   1\n");
     std::istringstream buf(default_species_elec_data);
     read_species_electronic_data_ascii(chem_mixture,buf);
   }
template<class NumericType > void Antioch::read_species_vibrational_data_ascii (ChemicalMixture< NumericType > & chem_mixture, std::istream & in) inline
Definition at line 206 of file species_ascii_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), Antioch::ChemicalMixture< CoeffType >::add_species_vibrational_data(), antioch_assert_equal_to, antioch_error, Antioch::ChemicalMixture< CoeffType >::chemical_species(), skip_comment_lines(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
Referenced by read_species_vibrational_data_ascii_default().
   {
     // skip the header
     skip_comment_lines(in, '#');
     std::string name;
     NumericType theta_v;
     unsigned int n_degeneracies;
     while (in.good())
       {
         in >> name;           // Species Name
         in >> theta_v;        // characteristic vibrational temperature (K)
         in >> n_degeneracies; // degeneracy of the mode
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             // If we do not have an enum for this species, that is going to cause
             // problems down the line.
             if (!chem_mixture.species_name_map().count(name))
               {
                 std::cerr << "ERROR: Unexpected species " << name
                           << " encountered while parsing thermodynamic table!"
                           << std::endl;
                 antioch_error();
               }
             // If this species is not part of the existing mixture, we
             // don't care about it, so just continue silently
             if( !chem_mixture.active_species_name_map().count(name) )
               {
                 continue;
               }
             // ... otherwise we add the data
             const unsigned int s =
               chem_mixture.active_species_name_map().find(name)->second;
             antioch_assert_equal_to((chem_mixture.chemical_species()[s])->species(), name);
             chem_mixture.add_species_vibrational_data(s, theta_v, n_degeneracies);
           }
       }
   }
template<class NumericType > void Antioch::read_species_vibrational_data_ascii_default (ChemicalMixture< NumericType > & chem_mixture) inline
Definition at line 259 of file species_ascii_parsing.h.
References read_species_vibrational_data_ascii().
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
   {
     static const std::string
       default_species_vib_data
       ("#===========================================================================\n"
        "# LEGEND\n"
        "#===========================================================================\n"
        "#\n"
        "# Species       -- Species name\n"
        "# Theta_v       -- Characteristic vibrational temperature (K)\n"
        "# degeneracy   -- degeneracy of the mode\n"
        "#\n"
        "# Characteristic Temperatures for Simple Harmonic Oscillator Model\n"
        "#\n"
        "# Species     Theta_v  degeneracy\n"
        "C2      2.66870e+03   1\n"
        "\n"
        "C2H     5.20100e+03   1\n"
        "C2H     7.20000e+02   2\n"
        "C2H     2.66100e+03   1\n"
        "\n"
        "C2H2    4.85290e+03   1\n"
        "C2H2    2.84000e+03   1\n"
        "C2H2    4.72490e+03   1\n"
        "C2H2    8.81830e+02   2\n"
        "C2H2    1.05080e+03   2\n"
        "\n"
        "C3      1.84500e+03   1\n"
        "C3      7.78700e+02   2\n"
        "C3      3.11760e+03   1\n"
        "\n"
        "CF      1.88214e+03   1\n"
        "\n"
        "CF2     1.76120e+03   1\n"
        "CF2     9.56820e+02   1\n"
        "CF2     1.60000e+03   1\n"
        "\n"
        "CF3     1.56800e+03   1\n"
        "CF3     1.00900e+03   1\n"
        "CF3     1.81150e+03   2\n"
        "CF3     7.36680e+02   2\n"
        "\n"
        "CF4     1.30720e+03   1\n"
        "CF4     6.25892e+02   2\n"
        "CF4     1.84540e+03   3\n"
        "CF4     9.08950e+02   3\n"
        "\n"
        "CH      4.11290e+03   1\n"
        "\n"
        "CH2     4.31650e+03   1\n"
        "CH2     1.95972e+03   1\n"
        "CH2     4.60432e+03   1\n"
        "\n"
        "CH3     4.31650e+03   1\n"
        "CH3     8.73370e+02   1\n"
        "CH3     4.54960e+03   2\n"
        "CH3     2.01150e+03   2\n"
        "\n"
        "CH4     4.19660e+03   1\n"
        "CH4     2.20620e+03   2\n"
        "CH4     4.34450e+03   3\n"
        "CH4     1.88600e+03   3\n"
        "\n"
        "Cl2     8.05355e+02   1\n"
        "\n"
        "CN      2.97610e+03   1\n"
        "\n"
        "CN+     2.92520e+03   1\n"
        "\n"
        "CO      3.12200e+03   1\n"
        "\n"
        "CO+     3.18800e+03   1\n"
        "\n"
        "CO2     1.91870e+03   1\n"
        "CO2     9.59660e+02   2\n"
        "CO2     3.38210e+03   1\n"
        "\n"
        "F2      1.32020e+03   1\n"
        "\n"
        "H2      6.33140e+03   1\n"
        "\n"
        "H2+     3.34280e+03   1\n"
        "\n"
        "H2O     5.26130e+03   1\n"
        "H2O     2.29460e+03   1\n"
        "H2O     5.40395e+03   1\n"
        "\n"
        "HCl     4.30330e+03   1\n"
        "\n"
        "HCN     3.01620e+03   1\n"
        "HCN     1.02660e+03   2\n"
        "HCN     4.76450e+03   1\n"
        "\n"
        "N2      3.39500e+03   1\n"
        "\n"
        "N2+     3.17580e+03   1\n"
        "\n"
        "NCO     1.83600e+03   1\n"
        "NCO     7.67100e+02   2\n"
        "NCO     2.76800e+03   1\n"
        "\n"
        "NH      4.72240e+03   1\n"
        "\n"
        "NH3     4.78100e+03   1\n"
        "NH3     1.47040e+03   1\n"
        "NH3     4.95440e+03   2\n"
        "NH3     2.34070e+03   2\n"
        "\n"
        "NO      2.81700e+03   1\n"
        "\n"
        "NO+     3.42100e+03   1\n"
        "\n"
        "NO2     1.07900e+03   1\n"
        "NO2     1.90000e+03   1\n"
        "NO2     2.32700e+03   1\n"
        "\n"
        "O2      2.23900e+03   1\n"
        "\n"
        "O2+     2.74120e+03   1\n"
        "\n"
        "OH      5.37820e+03   1\n"
        "\n"
        "SiO     1.78640e+03   1\n");
     std::istringstream buf(default_species_vib_data);
     read_species_vibrational_data_ascii(chem_mixture,buf);
   }
template<class NumericType > void Antioch::read_sutherland_data_ascii (MixtureViscosity< SutherlandViscosity< NumericType >, NumericType > & mu, std::istream & in) inline
Definition at line 52 of file sutherland_parsing.h.
References Antioch::ChemicalMixture< CoeffType >::active_species_name_map(), and skip_comment_lines().
Referenced by read_sutherland_data_ascii_default().
   {
     // skip the header
     skip_comment_lines(in, '#');
     std::string name;
     NumericType a, b;
      while (in.good())
       {
         in >> name; // Species Name
         in >> a;    //
         in >> b;    //
         // If we are still good, we have a valid set of transport
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (in.good())
           {
             const ChemicalMixture<NumericType>& chem_mixture = mu.chemical_mixture();
             // Check if this is a species we want.
             if( chem_mixture.active_species_name_map().find(name) !=
                 chem_mixture.active_species_name_map().end() )
               {
                 // Pack up coefficients
                 std::vector<NumericType> coeffs(2);
                 coeffs[0] = a;
                 coeffs[1] = b;
                 mu.add(name, coeffs);
               }
           }
       }
     return;
   }
template<class NumericType > void Antioch::read_sutherland_data_ascii_default (MixtureViscosity< SutherlandViscosity< NumericType >, NumericType > & mu) inline
Definition at line 92 of file sutherland_parsing.h.
References read_sutherland_data_ascii().
   {
     static const std::string
       default_sutherland_transport_data
       ("#-----------------------------------------------------------------------------\n"
        "# Coefficients for Sutherland viscosity model\n"
        "# \n"
        "# Form of the fit:\n"
        "# \n"
        "# mu = A*T^1.5/(T + B)\n"
        "# \n"
        "# where T is in Kelvin and the viscosity is then given in Pa-s.\n"
        "# \n"
        "# Sources:\n"
        "# \n"
        "# Air   -- \n"
        "# N2    -- \n"
        "# CPAir & CPN2 -- compatibility with benkirk's dissertation cases\n"
        "# \n"
        "# Sutherland coefficients are in general not as accurate as Blottner fits,\n"
        "# and are provided mainly for completeness.\n"
        "\n"
        "Air     1.458000e-06  1.103000e+02\n"
        "CPAir   1.458000e-06  1.104000e+02\n"
        "N2      1.399306e-06  1.066667e+02\n"
        "CPN2    1.399306e-06  1.066667e+02\n");
     std::istringstream buf(default_sutherland_transport_data);
     read_sutherland_data_ascii( mu, buf );
     return;
   }
template<typename T > void Antioch::set_zero (T & output) inline
Definition at line 105 of file metaprogramming.h.
 { output = 0; }
template<typename T > void Antioch::set_zero (std::vector< T > & a) inline
Definition at line 143 of file vector_utils.h.
References zero_clone().
 {
   if (a.size())
     std::fill(a.begin(), a.end(), zero_clone(a[0]));
 }
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> void Antioch::set_zero (_Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & a) inline
Definition at line 205 of file eigen_utils.h.
References zero_clone().
Referenced by Antioch::DuplicateReaction< CoeffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::ElementaryReaction< CoeffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources(), Antioch::KineticsEvaluator< CoeffType, StateType >::compute_mole_sources_and_derivs(), Antioch::Reaction< CoeffType >::compute_rate_of_progress_and_derivatives(), Antioch::LindemannFalloff< CoeffType >::F_and_derivatives(), and tester().
 {
   // We can't just use setZero here with arbitrary value_types
   if (a.size())
     a.setConstant (zero_clone(a[0]));
 }
void Antioch::skip_comment_lines (std::istream & in, const char comment_start)
Skip comment lines in the header of an ASCII text file prefixed with the comment character 'comment_start'.
This is put in Antioch namespace so we can reuse in a few classes where we are reading in text tables. Originally taken from FIN-S.
Definition at line 33 of file input_utils.C.
Referenced by read_blottner_data_ascii(), read_cea_mixture_data_ascii(), read_cea_thermo_data_ascii(), read_species_data_ascii(), read_species_electronic_data_ascii(), read_species_vibrational_data_ascii(), and read_sutherland_data_ascii().
   {
     char c, line[256];
     while (in.get(c), c==comment_start)
       in.getline (line, 255);
     // put back first character of
     // first non-comment line
     in.putback (c);
   }
std::pair<std::string, double> Antioch::split_string_double_on_colon (const std::string & token) inline
Split on colon, and return name, double value pair.
Taken from FIN-S for XML parsing.
Definition at line 63 of file string_utils.h.
References antioch_assert.
Referenced by read_reaction_set_data_xml().
   {
     std::pair<std::string, double> ret = std::make_pair(std::string(), 0.0);
     std::string::size_type colon_position = token.find(":");
     antioch_assert (colon_position != std::string::npos);
     ret.first  = token.substr(0, colon_position);
     ret.second = std::atof(token.substr(colon_position + 1).c_str());
     return ret;
   }
std::pair<std::string, int> Antioch::split_string_int_on_colon (const std::string & token) inline
Split on colon, and return name, int value pair.
Taken from FIN-S for XML parsing.
Definition at line 47 of file string_utils.h.
References antioch_assert.
Referenced by read_reaction_set_data_xml().
   {
     std::pair<std::string, int> ret = std::make_pair(std::string(), 0);
     std::string::size_type colon_position = token.find(":");
     antioch_assert (colon_position != std::string::npos);
     ret.first  = token.substr(0, colon_position);
     ret.second = std::atoi(token.substr(colon_position + 1).c_str());
     return ret;
   }
int Antioch::SplitString (const std::string & input, const std::string & delimiter, std::vector< std::string > & results, bool includeEmpties = true) inline
Taken from FIN-S for XML parsing.
Definition at line 78 of file string_utils.h.
References std::int.
Referenced by read_reaction_set_data_xml().
   {
     using std::vector;
     using std::string;
     int iPos = 0;
     int newPos = -1;
     int sizeS2 = (int)delimiter.size();
     int isize = (int)input.size();
     if(
        ( isize == 0 )
        ||
        ( sizeS2 == 0 )
         )
       {
         return 0;
       }
     vector<int> positions;
     newPos = input.find (delimiter, 0);
     if( newPos < 0 )
       {
         return 0;
       }
     int numFound = 0;
     while( newPos >= iPos )
       {
         numFound++;
         positions.push_back(newPos);
         iPos = newPos;
         newPos = input.find (delimiter, iPos+sizeS2);
       }
     if( numFound == 0 )
       {
         return 0;
       }
     for( int i=0; i <= static_cast<int>(positions.size()); ++i )
       {
         string s("");
         if( i == 0 )
           {
             s = input.substr( i, positions[i] );
           }
         else
           {
             int offset = positions[i-1] + sizeS2;
             if( offset < isize )
               {
                 if( i == static_cast<int>(positions.size()) )
                   {
                     s = input.substr(offset);
                   }
                 else if( i > 0 )
                   {
                     s = input.substr( positions[i-1] + sizeS2,
                                       positions[i] - positions[i-1] - sizeS2 );
                   }
               }
           }
         if( includeEmpties || ( s.size() > 0 ) )
           {
             results.push_back(s);
           }
       }
     return numFound;
   }
template<typename T > T Antioch::zero_clone (const T &) inline
Definition at line 109 of file metaprogramming.h.
 { return 0; }
template<typename T > std::vector< T > Antioch::zero_clone (const std::vector< T > & example) inline
Definition at line 110 of file vector_utils.h.
References zero_clone().
 {
   if (example.size())
     return std::vector<T>(example.size(),zero_clone(example[0]));
   return std::vector<T>();
 }
template<typename T , typename T2 > void Antioch::zero_clone (T & output, const T2 &) inline
Definition at line 113 of file metaprogramming.h.
 { output = 0; }
template<typename T1 , typename T2 > void Antioch::zero_clone (std::vector< T1 > & output, const std::vector< T2 > & example) inline
Definition at line 121 of file vector_utils.h.
References zero_clone().
 {
   const std::size_t sz = example.size();
   output.resize(sz);
   for (std::size_t i=0; i != sz; ++i)
     Antioch::zero_clone(output[i], example[i]);
 }
template<typename T , typename Scalar > std::vector<T> Antioch::zero_clone (const std::vector< T > & example, const Scalar & value) inline
Definition at line 132 of file vector_utils.h.
 {
   if (example.size())
     return std::vector<T>(example.size(),value);
   return std::vector<T>();
 }
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > Antioch::zero_clone (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & ex) inline
Definition at line 147 of file eigen_utils.h.
Referenced by Antioch::FalloffReaction< CoeffType, FalloffType >::compute_forward_rate_coefficient(), Antioch::Reaction< CoeffType >::compute_forward_rate_coefficient(), Antioch::DuplicateReaction< CoeffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::FalloffReaction< CoeffType, FalloffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::Reaction< CoeffType >::compute_rate_of_progress_and_derivatives(), Antioch::CEAEvaluator< CoeffType >::cp_over_R(), Antioch::CEAThermodynamics< NumericType >::cp_over_R(), Antioch::StatMechThermodynamics< CoeffType >::cv_el(), Antioch::StatMechThermodynamics< CoeffType >::cv_vib(), Antioch::KineticsType< CoeffType >::derivative(), Antioch::CEAEvaluator< CoeffType >::dh_RT_minus_s_R_dT(), Antioch::CEAThermodynamics< NumericType >::dh_RT_minus_s_R_dT(), Antioch::StatMechThermodynamics< CoeffType >::e_el(), Antioch::TroeFalloff< CoeffType >::F_and_derivatives(), Antioch::CEAEvaluator< CoeffType >::h_RT_minus_s_R(), Antioch::CEAThermodynamics< NumericType >::h_RT_minus_s_R(), Antioch::CEACurveFit< CoeffType >::interval(), Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::k(), Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::mu(), Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::mu_and_k(), Antioch::KineticsType< CoeffType >::operator()(), Antioch::TroeFalloff< CoeffType >::operator()(), set_zero(), tester(), and zero_clone().
 {
   // We can't just use setZero here with arbitrary _Scalar types
   if (ex.size())
     return
       _Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>
         (ex.rows(), ex.cols()).setConstant(zero_clone(ex[0]));
   return
     _Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>
       (ex.rows(), ex.cols());
 }
template<typename T1 , typename T2 > void Antioch::zero_clone (T1 & output, const T2 & example) inline
template<typename T > vex::vector< T > Antioch::zero_clone (const vex::vector< T > & example) inline
Definition at line 152 of file vexcl_utils.h.
 {
   vex::vector<T> returnval(example.queue_list(), example.size());
   returnval.clear();
   return returnval;
 }
template<typename T1 , typename T2 > void Antioch::zero_clone (vex::vector< T1 > & output, const vex::vector< T2 > & example) inline
Definition at line 162 of file vexcl_utils.h.
 {
   output.resize(example.queue_list(), example.size());
   output = 0;
 }
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols, typename Scalar2 > void Antioch::zero_clone (_Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & output, const _Matrix< Scalar2, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & ex) inline
Definition at line 167 of file eigen_utils.h.
References zero_clone().
 {
   // We can't just use setZero here with arbitrary _Scalar types
   output.resize(ex.rows(), ex.cols());
   output.setConstant(zero_clone(ex[0]));
 }
template<typename T > std::valarray< T > Antioch::zero_clone (const std::valarray< T > & example) inline
Definition at line 167 of file valarray_utils.h.
References zero_clone().
 {
   if (example.size())
     return std::valarray<T>(zero_clone(example[0]),example.size());
   else
     return std::valarray<T>();
 }
template<typename T1 , typename T2 > void Antioch::zero_clone (std::valarray< T1 > & output, const std::valarray< T2 > & example) inline
Definition at line 178 of file valarray_utils.h.
References zero_clone().
 {
   const std::size_t sz = example.size();
   output.resize(sz);
   for (std::size_t i=0; i != sz; ++i)
     Antioch::zero_clone(output[i], example[i]);
 }