antioch-0.0.7: test/constant_lewis_unit.C File Reference
constant_lewis_unit.C File Reference
#include <iostream>
#include <cmath>
#include <limits>
#include "antioch/constant_lewis_diffusivity.h"
Functions
template<typename Scalar >
int test_val (const Scalar val, const Scalar val_exact, const Scalar tol, const std::string &val_name)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
int main ()
Definition at line 81 of file constant_lewis_unit.C.
 {
   return ( tester<double>()  ||
            tester<long double>() ||
            tester<float>()
            );
 }
template<typename Scalar > int test_val (const Scalar val, const Scalar val_exact, const Scalar tol, const std::string & val_name)
Definition at line 38 of file constant_lewis_unit.C.
Referenced by tester().
 {
   using std::abs;
   int return_flag = 0;
   const Scalar rel_error = abs( (val - val_exact)/val_exact);
   if( rel_error  > tol )
     {
       std::cerr << "Error: Mismatch in " << val_name << std::endl
                 << val_name << "    = " << val << std::endl
                 << val_name+"_exact = " << val_exact << std::endl
                 << "rel_error = " << rel_error << std::endl
                 << "tol = " << tol << std::endl;
       return_flag = 1;
     }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 60 of file constant_lewis_unit.C.
References cp(), and test_val().
 {
   const Scalar Le = 1.4;
   Antioch::ConstantLewisDiffusivity<Scalar> diff( Le );
   const Scalar rho = 3.14;
   const Scalar cp = 2.71;
   const Scalar k = 42.0;
   const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 2;
   const Scalar D = diff.D( rho, cp, k );
   const Scalar D_exact = Le*k/(rho*cp);
   return test_val( D, D_exact, tol, std::string("D") );
 }