antioch-0.0.7: test/eucken_thermal_cond_unit.C File Reference
eucken_thermal_cond_unit.C File Reference
#include <iostream>
#include <cmath>
#include "antioch/stat_mech_thermo.h"
#include "antioch/eucken_thermal_conductivity.h"
Functions
template<typename Scalar >
int test_k (const Scalar k, const Scalar k_exact, const Scalar tol)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
int main ()
Definition at line 115 of file eucken_thermal_cond_unit.C.
 {
   return (tester<double>() ||
 //         tester<long double>() ||
           tester<float>());
 }
template<typename Scalar > int test_k (const Scalar k, const Scalar k_exact, const Scalar tol)
Definition at line 38 of file eucken_thermal_cond_unit.C.
Referenced by tester().
 {
   using std::abs;
   int return_flag = 0;
   const Scalar rel_error = abs( (k - k_exact)/k_exact);
   if( rel_error  > tol )
     {
       std::cerr << "Error: Mismatch in thermal conductivity" << std::endl
                 << "k       = " << k << std::endl
                 << "k_exact = " << k_exact << std::endl
                 << "rel_error = " << rel_error << std::endl
                 << "tol = " << tol << std::endl;
       return_flag = 1;
     }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 60 of file eucken_thermal_cond_unit.C.
References test_k(), and Antioch::EuckenThermalConductivity< ThermoEvaluator >::trans().
 {
   std::vector<std::string> species_str_list;
   const unsigned int n_species = 5;
   species_str_list.reserve(n_species);
   species_str_list.push_back( "N2" );
   species_str_list.push_back( "O2" );
   species_str_list.push_back( "N" );
   species_str_list.push_back( "O" );
   species_str_list.push_back( "NO" );
   Antioch::ChemicalMixture<Scalar> chem_mixture( species_str_list );
   const Scalar R_N2 = Antioch::Constants::R_universal<Scalar>()/28.016;
   const Scalar R_O2 = Antioch::Constants::R_universal<Scalar>()/32.0;
   const Scalar R_N = Antioch::Constants::R_universal<Scalar>()/14.008;
   const Scalar R_O = Antioch::Constants::R_universal<Scalar>()/16.0;
   const Scalar R_NO = Antioch::Constants::R_universal<Scalar>()/30.008;
   Antioch::StatMechThermodynamics<Scalar> thermo( chem_mixture );
   Antioch::EuckenThermalConductivity<Antioch::StatMechThermodynamics<Scalar> > k( thermo );
   const Scalar mu = 3.14e-3;
   // octave gives
   const Scalar k_N2_trans_exact = 2.5*mu*1.5*R_N2;
   const Scalar k_N_trans_exact = 2.5*mu*1.5*R_N;
   const Scalar k_O2_trans_exact = 2.5*mu*1.5*R_O2;
   const Scalar k_O_trans_exact = 2.5*mu*1.5*R_O;
   const Scalar k_NO_trans_exact = 2.5*mu*1.5*R_NO;
   int return_flag = 0;
   const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 2;
   int return_flag_temp = 0;
   return_flag_temp = test_k( k.trans(0, mu), k_N2_trans_exact, tol );
   if( return_flag_temp != 0 ) return_flag = 1;
   return_flag_temp = test_k( k.trans(1, mu), k_O2_trans_exact, tol );
   if( return_flag_temp != 0 ) return_flag = 1;
   return_flag_temp = test_k( k.trans(2, mu), k_N_trans_exact, tol );
   if( return_flag_temp != 0 ) return_flag = 1;
   return_flag_temp = test_k( k.trans(3, mu), k_O_trans_exact, tol );
   if( return_flag_temp != 0 ) return_flag = 1;
   return_flag_temp = test_k( k.trans(4, mu), k_NO_trans_exact, tol );
   if( return_flag_temp != 0 ) return_flag = 1;
   return return_flag;
 }