antioch-0.0.7: test/vanthoff_rate_vec_unit.C File Reference
vanthoff_rate_vec_unit.C File Reference
#include "antioch_config.h"
#include <valarray>
#include "antioch/eigen_utils_decl.h"
#include "antioch/metaphysicl_utils_decl.h"
#include "antioch/valarray_utils_decl.h"
#include "antioch/vanthoff_rate.h"
#include "antioch/eigen_utils.h"
#include "antioch/metaphysicl_utils.h"
#include "antioch/valarray_utils.h"
#include <cmath>
#include <limits>
Functions
template<typename PairScalars >
int vectester (const PairScalars &example)
int main ()
Function Documentation
int main ()
Definition at line 134 of file vanthoff_rate_vec_unit.C.
References vectester().
 {
   int returnval = 0;
   returnval = returnval ||
     vectester (std::valarray<float>(2));
   returnval = returnval ||
     vectester (std::valarray<double>(2));
   returnval = returnval ||
     vectester (std::valarray<long double>(2));
 #ifdef ANTIOCH_HAVE_EIGEN
   returnval = returnval ||
     vectester (Eigen::Array2f());
   returnval = returnval ||
     vectester (Eigen::Array2d());
   returnval = returnval ||
     vectester (Eigen::Array<long double, 2, 1>());
 #endif
 #ifdef ANTIOCH_HAVE_METAPHYSICL
   returnval = returnval ||
     vectester (MetaPhysicL::NumberArray<2, float> (0));
   returnval = returnval ||
     vectester (MetaPhysicL::NumberArray<2, double> (0));
   returnval = returnval ||
     vectester (MetaPhysicL::NumberArray<2, long double> (0));
 #endif
   return returnval;
 }
template<typename PairScalars > int vectester (const PairScalars & example)
Definition at line 58 of file vanthoff_rate_vec_unit.C.
References Antioch::KineticsType< CoeffType >::derivative(), and std::pow().
 {
   using std::abs;
   using std::exp;
   using std::pow;
   typedef typename Antioch::value_type<PairScalars>::type Scalar;
   const Scalar Cf = 1.4;
   const Scalar eta = 1.2;
   const Scalar Ea = 5.0;
   const Scalar D = -2.5;
   Antioch::VantHoffRate<Scalar> vanthoff_rate(Cf,eta,Ea,D,1.,1.);
   // Construct from example to avoid resizing issues
   PairScalars T = example;
   T[0] = 1500.1;
   T[1] = 1600.1;
   const Scalar rate_exact0 = Cf*pow(Scalar(1500.1),eta)*exp(-Ea/1500.1+D*1500.1);
   const Scalar rate_exact1 = Cf*pow(Scalar(1600.1),eta)*exp(-Ea/1600.1+D*1600.1);
   const Scalar derive_exact0 = Cf * pow(Scalar(1500.1),eta) * exp(-Ea/Scalar(1500.1) + D*Scalar(1500.1)) * (D + eta/Scalar(1500.1) + Ea/(Scalar(1500.1)*Scalar(1500.1)));
   const Scalar derive_exact1 = Cf * pow(Scalar(1600.1),eta) * exp(-Ea/Scalar(1600.1) + D*Scalar(1600.1)) * (D + eta/Scalar(1600.1) + Ea/(Scalar(1600.1)*Scalar(1600.1)));
   int return_flag = 0;
   const PairScalars rate = vanthoff_rate(T);
   const PairScalars deriveRate = vanthoff_rate.derivative(T);
   const Scalar tol = std::numeric_limits<Scalar>::epsilon()*10;
   if( abs( (rate[0] - rate_exact0)/rate_exact0 ) > tol )
     {
       std::cout << "Error: Mismatch in rate values." << std::endl
                 << "rate(T0)   = " << rate[0] << std::endl
                 << "rate_exact = " << rate_exact0 << std::endl
                 << "difference = " << rate[0] - rate_exact0 << std::endl;
       return_flag = 1;
     }
   if( abs( (rate[1] - rate_exact1)/rate_exact1 ) > tol )
     {
       std::cout << "Error: Mismatch in rate values." << std::endl
                 << "rate(T1)   = " << rate[1] << std::endl
                 << "rate_exact = " << rate_exact1 << std::endl
                 << "difference = " << rate[1] - rate_exact1 << std::endl;
       return_flag = 1;
     }
   if( abs( (deriveRate[0] - derive_exact0)/derive_exact0 ) > tol )
     {
       std::cout << std::scientific << std::setprecision(16)
                 << "Error: Mismatch in rate derivative values." << std::endl
                 << "drate_dT(T0) = " << deriveRate[0] << std::endl
                 << "derive_exact = " << derive_exact0 << std::endl;
       return_flag = 1;
     }
   if( abs( (deriveRate[1] - derive_exact1)/derive_exact1 ) > tol )
     {
       std::cout << std::scientific << std::setprecision(16)
                 << "Error: Mismatch in rate derivative values." << std::endl
                 << "drate_dT(T1) = " << deriveRate[1] << std::endl
                 << "derive_exact = " << derive_exact1 << std::endl;
       return_flag = 1;
     }
   std::cout << "Van't Hoff rate: " << vanthoff_rate << std::endl;
   return return_flag;
 }